### ISSUE TITLE
[openhabcloud] Connection recovery issue

### ISSUE THREAD

**Issue by paulianttila** [openhab/openhab2-addons#5247] opened 2019-03-25 20:11 UTC
There was a hotfix deployment at last week to myopenHAB cloud service. I was a holiday trip during that time and my cloud connector didn't recover from restart immediately but after several days. 

<img width="728" alt="Screenshot 2019-03-25 at 21 44 53" src="https://user-images.githubusercontent.com/5506533/54950201-622f8880-4f49-11e9-96ca-18b090bf87bf.png">

1. Remote connection from iPhone app was working fine before cloud service restart.
2. After cloud service hotfix deployment, connection didn't work but connection from iPhone app was always timeout.
3. Myopenhab status was green (online).
4. After 4 days connection started to work automatically.

So, I guess that there is bug in the cloud connector. I have seen similar issue before (cloud connector bundle restart from Karaf console recover situation immediately). Other users have meet same problem as well (https://community.openhab.org/t/myopenhab-hotfix-deployment-happening-now/70740).

```
openhab> bundle:list org.openhab.io.openhabcloud
START LEVEL 100 , List Threshold: 50
 ID │ State  │ Lvl │ Version │ Name
────┼────────┼─────┼─────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
279 │ Active │  80 │ 2.4.0   │ openHAB Cloud Connector Bundle
```

```
2019-03-21 03:50:57.410 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = xxxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxx, base URL = http://localhost:8080)
2019-03-21 03:51:04.818 [ERROR] [io.openhabcloud.internal.CloudClient] - Socket.IO error: {}
io.socket.engineio.client.EngineIOException: xhr poll error
	at io.socket.engineio.client.Transport.onError(Transport.java:71) [279:org.openhab.io.openhabcloud:2.4.0]
	at io.socket.engineio.client.transports.PollingXHR.access$100(PollingXHR.java:19) [279:org.openhab.io.openhabcloud:2.4.0]
	at io.socket.engineio.client.transports.PollingXHR$6$1.run(PollingXHR.java:124) [279:org.openhab.io.openhabcloud:2.4.0]
	at io.socket.thread.EventThread$2.run(EventThread.java:80) [279:org.openhab.io.openhabcloud:2.4.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.io.IOException: 400
	at io.socket.engineio.client.transports.PollingXHR$Request$1.run(PollingXHR.java:218) ~[?:?]
	... 1 more
2019-03-21 03:51:04.821 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = xxxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxx, base URL = http://localhost:8080)
2019-03-21 03:51:20.453 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID = xxxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxx, base URL = http://localhost:8080)
2019-03-21 03:52:33.161 [WARN ] [okhttp3.OkHttpClient                ] - A connection to https://myopenhab.org/ was leaked. Did you forget to close a response body?


...

2019-03-25 09:58:42.159 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = xxxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxx, base URL = http://localhost:8080)
2019-03-25 10:00:11.231 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID = xxxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxx, base URL = http://localhost:8080)
```

**Comment by wborn** [comment] 2019-03-25 20:25
I think this is just a duplicate of your other issue https://github.com/openhab/openhab-cloud/issues/134.
See also my analysis in the last comment of that issue.

**Comment by paulianttila** [comment] 2019-03-25 20:31
Hah, I didn't remember that at all.

**Comment by wborn** [comment] 2019-03-25 20:33
It think it's in my top 3 of most frustrating OH issues. :wink:

**Closed** 2019-03-25 20:35 UTC
Labels: duplicate, io: openhabcloud
