### ISSUE TITLE
[MQTT]  Incoming messages/topics/values not processed

### ISSUE THREAD

**Issue by vdraack** [openhab/openhab2-addons#6572] opened 2019-12-11 13:54 UTC
# Current Behaviour
Incoming messages/values of topics set by "MQTT State Topic" of "Generic MQTT Thing" channels of new MQTT binding are either not received or processed (tried with and without JSONPATH transformation) or not forwarded for state change to linked items. Rules does not fire because state change does not happen (window/contact open/close does no longer trigger power-plug/switch ON/OFF)

Sending commands with the "MQTT Command Topic" still works.
# Expected Behaviour
Incoming messages of configured topics/values should change the state of linked items. This has worked with former 2.5 Milestones 
# Environment:
HW: Raspberry 3b
OS: Raspbian Jessie
JRE: Oracle JRE 1.8.0_201-b09
OH: OpenHAB 2.5RC1

**Comment by J-N-K** [comment] 2019-12-11 14:08
Duplicate of #6562

**Closed by J-N-K** 2019-12-11 14:08 UTC
