### ISSUE TITLE
Astro Binding - Internal job queue full? Thread Pool?

### ISSUE THREAD

**Issue by APajonk** [openhab/openhab2-addons#2553] opened 2017-08-14 07:45 UTC
Hi guys,

with the current Astro Binding in openHAB 2 I observed a bug regarding Thread Pool and recurring events.

The longer openHAB runs, the more messages like:

`2017-08-12 23:15:00.580 [INFO ] [Manager$ExpressionThreadPoolExecutor] - Expression '0 15 23 12 8 ? 2017' has no future executions anymore`

I get. And having openHAB running for some days, without rebooting or restarting it then you should get this:

`2017-08-13 00:00:00.609 [INFO ] [thome.binding.astro.internal.job.Job] - Scheduled Astro event-jobs for thing astro:moon:local
2017-08-13 00:00:00.631 [ERROR] [thome.binding.astro.internal.job.Job] - Queue full
java.lang.IllegalStateException: Queue full
        at java.util.AbstractQueue.add(AbstractQueue.java:98)[:1.8.0_131]
        at org.eclipse.smarthome.binding.astro.handler.AstroThingHandler.addJobToQueue(AstroThingHandler.java:314)[188:org.eclipse.smarthome.binding.astro:0.9.0.b5]
        at org.eclipse.smarthome.binding.astro.internal.job.Job.schedule(Job.java:58)[188:org.eclipse.smarthome.binding.astro:0.9.0.b5]
        at org.eclipse.smarthome.binding.astro.internal.job.Job.scheduleEvent(Job.java:94)[188:org.eclipse.smarthome.binding.astro:0.9.0.b5]
        at org.eclipse.smarthome.binding.astro.internal.job.Job.scheduleRange(Job.java:115)[188:org.eclipse.smarthome.binding.astro:0.9.0.b5]
        at org.eclipse.smarthome.binding.astro.internal.job.DailyJobSun.run(DailyJobSun.java:56)[188:org.eclipse.smarthome.binding.astro:0.9.0.b5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
`
Seems like a bug for me. Someone missed "releasing/deleting old" events? Something like a clean up? I´m not that deep in the code here but it looks like this.

Best regards,
Artur

**Comment by kaikreuzer** [comment] 2017-08-14 07:57
Looks like a duplicate of https://github.com/eclipse/smarthome/issues/3728, which has already been fixed a while ago.
Please always provide the exact version that you are using. Also note that the Astro binding lives at ESH, so the issue tracker is https://github.com/eclipse/smarthome/issues. If you are running the very latest 2.2.0-SNAPSHOT distro and you still have issues, feel free to report an issue there.

**Closed by kaikreuzer** 2017-08-14 07:57 UTC
