### ISSUE TITLE
HueEmulation binding not working with Docker

### ISSUE THREAD

**Issue by eschizoid** [openhab/openhab2-addons#1317] opened 2016-10-11 04:23 UTC
Seems that the way this `binding` was thought, is not going to work with `Docker`. I'm getting the following log messages:

```
23:13:16.069 [TRACE] [tion.internal.HueEmulationUpnpServer] - Got SSDP Discovery packet from 172.17.0.3:50883
23:13:16.070 [TRACE] [tion.internal.HueEmulationUpnpServer] - Sending to 172.17.0.3 : HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
EXT:
LOCATION: http://172.17.0.3:8080/api/discovery.xml
SERVER: FreeRTOS/7.4.2 UPnP/1.0 IpBridge/1.10.0
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:601df881-c2ed-476e-a741-1fa0313d9b39::urn:Belkin:device:**
```

Even after setting the property `discoveryIp`, the binding is assigning an internal docker ip which is obviously not exposed and thus it will never going to be reach out by the `Amazon Echo`.
##

**Comment by eschizoid** [comment] 2016-10-11 04:24
@digitaldan Any ideas would be greatly appreciated.

**Comment by kaikreuzer** [comment] 2016-10-11 06:51
Isn't this rather something that needs to be addressed in the docker container and thus should be reported at https://github.com/openhab/openhab-docker? The container needs to provide an IP address under which the system is accessible externally; if it keeps the content of the container isolated, there is no chance for the hue emulation to be accessible.

**Comment by eschizoid** [comment] 2016-10-11 14:48
@kaikreuzer 
>Isn't this rather something that needs to be addressed in the docker container and thus should be reported at https://github.com/openhab/openhab-docker? 

I don't think that should be the case and let me explain why. 

if you see the `docker-compose.yml` file or the run command for a normal `docker` startup, both have as parameters `net: "host"` and `--net=host` respectively. Meaning that the network ip its being shared between the container and host.

>The container needs to provide an IP address under which the system is accessible externally; if it keeps the content of the container isolated, there is no chance for the hue emulation to be accessible.
I can access the Paper UI using my raspberry pi network address. However, the hue emulation continues using an internal docker ip `172.x.x.x` even after setting the discovery `discoveryIp` address.

Let me know what you think.

**Comment by kaikreuzer** [comment] 2016-10-11 18:32
> Let me know what you think.

I am absolutely no expert on these things, so I will leave it to @digitaldan to comment :-)

**Comment by digitaldan** [comment] 2016-10-11 18:41
@eschizoid are you sure the property is being set properly?  I just checked the code, and it looks like we indeed use the address https://github.com/openhab/openhab2-addons/blob/57e29d39fad0413c56de4c8fe2d04772a6587f06/addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationUpnpServer.java#L82 if it is specified.  I have had another user successfully use this, I'm not sure why its not working here.  Also that discovery request is coming from the same docker internal network.  

Does upnp work for the docker container?  I always ran mine in host networking mode b/c of this..

**Comment by digitaldan** [comment] 2016-10-11 18:44
>both have as parameters net: "host" and --net=host respectively. 

Sorry, i missed this part.  The emulation binding is looking for the first non loopback address to send to, it must be finding the docker network even though it is not being used for this container.  Specifying the IP should work, what build are you on?  This was only added a week or two ago.

**Comment by eschizoid** [comment] 2016-10-11 18:51
@digitaldan 
>are you sure the property is being set properly?

positive. I try changing the property during runtime and during startup none of the work.

what build are you on? 

I pull from docker hub yesterday around 11:00 pm central time. Don't have the build number right now.

**Comment by eschizoid** [comment] 2016-10-12 01:45
@digitaldan I con push a docker image if that would help you to identify the problem. Let me know.

**Comment by eschizoid** [comment] 2016-10-14 15:50
@digitaldan Is there any other idea that you could suggest me to try?

**Comment by eschizoid** [comment] 2016-11-08 21:42
is this addon still under development?

**Comment by kaikreuzer** [comment] 2016-11-09 07:00
> Is there any other idea that you could suggest me to try?

Not using docker :-)

> is this addon still under development or is it dead?

It is, but your issue is very specific and apparently hard to reproduce. So the best would be if you yourself could do the analysis and suggest a fix with through a PR.

**Comment by michaelwoods** [comment] 2016-11-09 14:42
I too have come across this issue.

I am using net host with a supplied discoveryIp and I am able to access the discovery.xml from local network addresses (192.168.1.0/24). However any apps that scan for a bridge come up with no result.

The XML content has many null values, not sure if that's affecting things I'm not really familiar with Hue. I'm trying to add my lights into Google Home for a better integration over IFTTT.

```
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
    <specVersion>
        <major>1</major>
        <minor>0</minor>
    </specVersion>
    <URLBase>http://192.168.1.153:8080/</URLBase>
    <device>
        <deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
        <friendlyName>openHAB Hue Emulation</friendlyName>
        <manufacturer>Royal Philips Electronics</manufacturer>
        <manufacturerURL>http://www.philips.com</manufacturerURL>
        <modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
        <modelName>Philips hue bridge 2015</modelName>
        <modelNumber>929000226503</modelNumber>
        <modelURL>http://www.meethue.com</modelURL>
        <serialNumber>0017880ae670</serialNumber>
        <UDN>uuid:f434c270-96dc-4b81-93f8-c010d28bdf7b</UDN>
        <serviceList>
            <service>
                <serviceType>(null)</serviceType>
                <serviceId>(null)</serviceId>
                <controlURL>(null)</controlURL>
                <eventSubURL>(null)</eventSubURL>
                <SCPDURL>(null)</SCPDURL>
         </service>
        </serviceList>
        <presentationURL>index.html</presentationURL>
        <iconList>
            <icon>
                <mimetype>image/png</mimetype>
                <height>48</height>
                <width>48</width>
                <depth>24</depth>
                <url>hue_logo_0.png</url>
            </icon>
            <icon>
                <mimetype>image/png</mimetype>
                <height>120</height>
                <width>120</width>
                <depth>24</depth>
                <url>hue_logo_3.png</url>
            </icon>
        </iconList>
    </device>
</root>
```

**Comment by michaelwoods** [comment] 2016-11-09 15:03
Some additional information. Manually crafting a multicast UDP discovery packet resulted in the following response:

```
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=100
EXT:
LOCATION: http://192.168.1.153:8080/api/discovery.xml
SERVER: FreeRTOS/7.4.2 UPnP/1.0 IpBridge/1.10.0
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:f434c270-96dc-4b81-93f8-c010d28bdf7b::urn:Belkin:device:**

```

Monitoring the network traffic I see my OS X device performing searches and also receiving the above response.

**Comment by digitaldan** [comment] 2016-11-10 01:13
Hi, the binding is not dead, I just have not had time to look into this issue and unfortunately I do not have an ETA on when I will get to it.

**Comment by KevinTaron** [comment] 2016-12-05 19:21
Same problem here.
Seems to working fine but alexa can't find the items.

**Comment by bradleyscott** [comment] 2017-02-16 18:42
I'm also finding the same problem. I was previously running Home Assistant in docker and had some issues but resolved them when I found Hue was looking to find the emulator on port 80. Has anyone resolved this?

**Comment by jrbloemhof** [comment] 2017-03-28 16:25
I didn't have a chance to really look at this in-depth, but I would assume it's the same issue as was recently solved for Sonos Controller (see https://github.com/SoCo/SoCo/pull/444 ) - if the Hue Emulator is auto-detecting it's own IP address, it will be sending out the Docker container's local IP address rather than the host's ethernet IP, so it gets broadcast messages from devices, but then points the device to connect to a wrong / unreachable IP.

**Closed** 2018-11-27 07:21 UTC
