### ISSUE TITLE
[Chromecast] State update not working

### ISSUE THREAD

**Issue by TS-Tec** [openhab/openhab2-addons#1862] opened 2017-02-08 16:50 UTC
In some cases where ChromeCast Audio is controlled by other applications (e.g. Google Home or Spotify) the state ("PLAY", "PAUSE", etc.) is not updated.
In most cases where openHAB initialized the streaming and another app takes over control it works fine. But if the other app starts streaming, you have to send command "pause" and then "play" that status updates will work even from the other app.

In case the status is not updated, you always see a warning on the runtime log:

`17:43:56.020 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Unable to process request ID = 1, data: {"requestId":1,"status":{"applications":[{"appId":"CC32E753","displayName":"Spotify","isIdleScreen":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.broadcast"},{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.spotify.chromecast.secure.v1"}],"sessionId":"abdaf512-8c24-4900-9a21-6912a947e183","statusText":"Spotify","transportId":"abdaf512-8c24-4900-9a21-6912a947e183"}],"volume":{"controlType":"attenuation","level":0.4429999887943268,"muted":false,"stepInterval":0.05000000074505806}},"responseType":"RECEIVER_STATUS"}
`

In cases it works, the item state is updated correct without any warning.

**Comment by lolodomo** [comment] 2017-02-08 18:01
Duplicate of issue #1783

**Closed** 2017-02-08 18:22 UTC
Labels: duplicate
