### ISSUE TITLE
formatting exception for rfxcom temperature

### ISSUE THREAD

**Issue by pieterh** [openhab/openhab2-addons#620] opened 2016-01-12 22:53 UTC
The following warnings are displayed in the log. 
Exception while formatting value '17.900000000000002131628207280300557613372802734375' of item Temperatuur_Kamer with format '%d °C': java.util.IllegalFormatConversionException: d != java.math.BigDecimal
It seems to happen when the initial page is laded in baisc or clasic ui. At that stage the text ERR is displayed instead of the temperature. Later when the sensor gives an update, the temperature is displayed in both UIs. however... it is in the format of 17.900000000000002131628207280300557613372802734375
not that nice ;-) 
The org.openhab.binding.rfxcom/ESH-INF/thing/channels.xml file shows pattern "%d °C" Problably a format of "%.1f °C" would make more sense. Not sure though why there is a difference in error handling when the page is initially loaded versus when there is a temperature update.
used the build of today.

**Comment by watou** [comment] 2016-01-12 23:03
duplicate of #581.

**Closed** 2016-01-12 23:24 UTC
