### ISSUE TITLE
[knx] Telegrams of -control type items repeated

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab2-addons#4234] opened 2018-11-17 15:55 UTC
## Expected Behavior
openHAB should not automatically resend any received KNX telegram to the KNX bus.

## Current Behavior
I need some rules to trigger on "received command" events of my rollershutters, they can not be changed to "changed" events, this was not working with the "rollershutter" type items after migrating to KNX2. The suggested workaround was to use an additional "rullershutter-control" item, which I did:

`Thing device knx-1_1_76 [
...
    ] {
        Type rollershutter-control   : Rollaeden_EG_Taster    "Taster Rolläden EG"    [ upDown="0/4/20", stopMove="0/4/21" ]
...
    }

Thing device generic [
     ] {
...
        Type rollershutter           : Rollaeden_EG    "Rolläden EG"    [ upDown="0/4/20", stopMove="0/4/21", position="0/4/22" ]
...`

and 

`Rollershutter Rollaeden_EG              "Rolläden EG"    (gZentral_Rollaeden)    { channel="knx:device:bridge:generic:Rollaeden_EG" }

Rollershutter Rollaeden_EG_Taster    "Rolläden EG"                                           { channel="knx:device:bridge:knx-1_1_76:Rollaeden_EG_Taster" }`

With this setup I observe repeated telegrams, even after deactivating all rules:

`|27.10.2018 19:17:50 |3674 |low |0 |SF |6 |1.1.76 (Tastsensor 4fach Universal TSM) |0/4/20 GA (Rolläden EG (auf/ab)) |Down|

|27.10.2018 19:17:50 |3674 |low |0 |SF |6 |1.1.241 |0/4/20 GA (Rolläden EG (auf/ab)) |Down|`

## Steps to Reproduce (for Bugs)
See above: Create a rollershutter and a rollershutter-control item with the same KNX GA and send this GA to the KNX bus.

## Context
This may cause problems with other the KNX devices or logic engines on the bus. 

I also had a huge problem, when two openHAB instances where active at the same time (production and testing). These two instances send those telegrams with maximum rate to each other.

## Your Environment
This was tested with the KNX2 binding of the  Milestone 4 release of openHAB 2.4 on macOS 10.13 (High Sierra)
Java version:
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (Zulu 8.31.0.1-macosx) (build 1.8.0_181-b02)
OpenJDK 64-Bit Server VM (Zulu 8.31.0.1-macosx) (build 25.181-b02, mixed mode)

**Comment by lewie** [comment] 2018-12-12 21:11
@juelicher, that should be fixed with these adjustments #4258 and today #4357
...
> Second new behavior: (As supplement with e7e3247)
> Originally, control channels sent a GroupValueWrite telegram to KNX, no matter if the channel was 
> changed by openHAB (by UI etc.) or by a GroupValueWrite telegram from KNX. But if a 
> GroupValueWrite telegram from KNX was sent, openHAB must not answer for the same GA with a 
> GroupValueWrite. If KNX has sent GroupValueWrite, all participants listening to this GA are already 
> aware of the status change.
> So the second new behavior was, **to block this GroupValueWrite sent to KNX, if KNX itself triggered**
> **the change.**

**Comment by juelicher** [comment] 2018-12-12 21:44
Thanks for the information!

I would be gladbto test the new version of the binding, but I can not compile it myself. Is there any place I could get a binary version?

**Comment by lewie** [comment] 2018-12-12 21:56
@juelicher, [here is a binary.](https://github.com/lewie/openhab2/raw/KNX_IO_4352_from_Kai_testfilelewie-patch-1/org.openhab.binding.knx-2.4.0-SNAPSHOT.jar) :-)

**Comment by juelicher** [comment] 2018-12-13 10:13
Thanks! I will test it tomorrow!

**Comment by kaikreuzer** [comment] 2018-12-14 09:37
> Create a rollershutter and a rollershutter-control item with the same KNX GA

I think here lies your problem. You have to decide, whether the state is within openHAB (use a control channel in that case) or in KNX (use a "normal" channel in that case).

**Comment by juelicher** [comment] 2018-12-14 20:20
@lewie  
> @juelicher, that should be fixed with these adjustments #4258 and today #4357

I did some testing tonight and on the first glance it looks good! There are no repeated telegrams on the KNX Bus and my "received command" rules are triggered more than once (this has been a problem with the previous snapshot). 

I will keep using this version of the binding and report back if I find any issues!

Many thanks for your effort, that helps a lot!!

> I think here lies your problem. You have to decide, whether the state is within openHAB (use a control channel in that case) or in KNX (use a "normal" channel in that case).

The problem is, that with the "normal" channels and the KNX2 binding the "received command" triggers does not work for commands like "UP" or "STOP". But I need the information when a STOP or UP/DOWN telegram was send by one of the wall mounted switches for my rules. There is no "changed" trigger that could be used instead. On the other hand there where issues with sending commands to the KNX bus with -control type items. Using two items was a workaround suggested in the forum.  This has been discussed in this thread: [KNX 2: Received command rule trigger does not work](https://community.openhab.org/t/knx-2-received-command-rule-trigger-does-not-work/42857l)

**Comment by juelicher** [comment] 2018-12-20 12:11
@lewie 

Today I updated to the release version of openHAB 2.4.0. After checking the git log, I assumed that all the latest changes of the KNX binding where part of the release, but after testing it I again hat duplicated telegrams.

After switching back to the binding version from your post everything is fine again. Do I assume correctly, that I missed a change and that not all of the latest changes in the binding are part of the release?

Thanks for your help!

**Comment by kaikreuzer** [comment] 2018-12-20 12:19
@juelicher This is actually a feature, not a bug. The channel receives a state update from openHAB and has to make this available on KNX. It is just by chance that this telegram looks the same as the command that came from some KNX sensor previously - but there is not necessarily a relation between them.
The state update is created by openHAB through the auto-update feature. For rollershutters, this does not make much sense, so I would suggest to deactivate it by adding `autoupdate="false"` to your item definition. With this in place, no state updates are sent out to KNX after receiving a command.

**Closed by kaikreuzer** 2018-12-20 12:19 UTC
Labels: knx

**Comment by juelicher** [comment] 2018-12-20 13:20
Maybe I am a bit lost here and I don't understand the concepts, but I really do not understand why resending the same data to the KNX bus should be a feature. This really has caused me big trouble in the past when I had a second openHAB instance for testing and booth  where sending telegrams with maximum  rate to each other. Is there some documentation regarding these concepts, so that I get a better understanding of the background?

As everything works as expected (at least as I expected) with the snapshot binding from lewie's post 8 days ago I am wondering, if these changes have been intentionally reverted?

I will test the autoupdate="false" option, should it be added to the -control or the normal item? 

On the other hand this problem is caused because the "normal" items do not trigger on the commands received from the bus and the workarround to add -control items, maybe this should be reconsidered. I still think, that triggering on these commands is a relevant use case.

**Comment by juelicher** [comment] 2018-12-20 13:45
I tested adding autoupdate="false" to the -control items with the 2.4.0 release version of the binding and this seems to have the desired effect. I will do some more testing in the next days

**Comment by lewie** [comment] 2018-12-21 11:20
@juelicher,
if  `autoupdate="false"` is set, GUIs will not be updated anymore. It can only be regarded as a temporary solution. It is definitely not a clean solution.

I am with you!
> On the other hand this problem is caused because the "normal" items do not trigger on the commands received from the bus and the workarround to add -control items, maybe this should be reconsidered. I still think, that triggering on these commands is a relevant use case.

But here it is important to combine both concepts neatly. OpenHAB with State / Command and KNX bus with GroupValueWrite, GroupValueRead, GroupValueResponse and the corresponding KNX flags (CRTWU), how a group address should behave.

The current Thing `device` with `<` and `-control` channels of the KNX bundle is a basic Thing, which should provide the basic functionality. The function that should have prevented the sending back of the telegrams in this thing destroys the functionality of `autoupdate ="false"`. (In combination, only every second telegram was filtered). Therefore the apparent regression.

I am working on a new additional thing for the KNX bundle. This thing does not differentiate between normal and -control channels. Essentially, the group addresses are configured similarly here as happens in DTPs data points of the devices in the ETS. It uses KNX flags (CRTWU) to configure GAs. With such an extended flagdevice, then `autoupdate ="false"` will have to be excluded as a configuration option to avoid incompatibilities.

**Comment by udo1toni** [comment] 2018-12-21 15:16
> If autoupdate="false" is set, GUIs will not be updated anymore. 
But that is only half the truth ;) 
In fact, a command sent by openHAB to knx should result in a status update for the channel by **knx**, _not_ by **openHAB itself**. If the configuration is correct, this should work regardless if autoUpdate is set to true or false.

**Comment by kaikreuzer** [comment] 2018-12-21 17:46
> In fact, a command sent by openHAB to knx should result in a status update for the channel by knx, not by openHAB itself

That's wrong in that case. -control channels mean that the state is maintained in openHAB, not KNX (i.e. the device is somewhere else, NOT in KNX). So if there's a command in openHAB, the device (e.g. a hue bulb) will change state, which is sent in openHAB and needs to be pushed out to KNX, so that a wallswitch can show the updated state (e.g. by LEDs in the wallswitch).

**Comment by jo47011** [comment] 2019-02-17 13:27
> I am working on a new additional Thing for the KNX bundle. This Thing does not differentiate between normal and -control channels.

Are you still working on it?  Is it gonna be part of the official package or how can others benefit from your potential solution/improvement?  I understand the architectural constraints but the current approach is not user friendly at all for some scenarios.  Until then I will switch back to KNX1 :(

**Comment by lewie** [comment] 2019-02-17 13:57
@jo47011, it's still in profress and I can't tell when I can run first official tests. There are still some architecture issues to be solved to run it as an extension of the KNX2 bundle. Waiting for it doesn't make sense.

Maybe I can help you how to implement your requirements with the current KNX2 bundle?!

**Comment by jo47011** [comment] 2019-02-17 16:45
@lewie thanks a lot four your offer :)  Finally I got it working.  Not an easy task at all.  I needed the -control items to get events from my wall mounted switches.  Well I might have something to help others:
I have a **python script** that reads in KNX1 item files and the ETS (**knxproj**) file and then generates KNX2 item files and the knx.thing file.  Is there a code share area where I can upload it?  I don't think it belongs into the binding itself as it will not work out of the box for everybody but it will be a good start for anyone who wants to automate their migration.  Any proposal?

**Comment by lewie** [comment] 2019-02-18 07:38
@jo47011, cool!, this is your work. Then you should publish the script under your name. Welcome to the world of open source developers! :-)
Go to https://github.com/jo47011?tab=repositories and open a new Repository. And upload your script directly or with Git from your PC.

Documentation: https://help.github.com/articles/creating-a-new-repository/

![grafik](https://user-images.githubusercontent.com/5707426/52935020-80a5d100-3358-11e9-9e01-8b2755da7984.png)

**Comment by jo47011** [comment] 2019-02-18 14:16
@lewie ok got me there.  Thanks for the nice welcome and the perfect description.  :) I will do so and publish it in the next few days.  Still needs some cleaning up.

**Comment by jo47011** [comment] 2019-02-24 19:43
Hi @lewie, I did it :) I just uploaded a 1st version of a **knx1** to **knx2** **conversion script**.  If you or anyone else find the time, I appreciate any kind of feedback.  See https://github.com/jo47011/knx-converter

One question about the license: shall I rather use the OpenHAB/Eclipse license?

**Comment by AntonWedemeier** [comment] 2019-03-30 15:32
Hi @jo47011, I did try the converter to day. I already had done my conversion last year, but I wanted to see if this conversion works. The script did the trick. I am working on a Windows 10 PC.
I don't have complex things in my installation, only switches and dimmers.

**Comment by jo47011** [comment] 2019-03-31 13:08
Hi Anton, thanks for the feedback.  Yes seems to work now on Unix, Mac and Windows.  Already helped another Windows users to get it run.  Great if it can help others...
