### ISSUE TITLE
[Xiaomi / MiHome] Sensors do nothing.

### ISSUE THREAD

**Issue by BrutalBirdie** [openhab/openhab2-addons#2459] opened 2017-07-13 08:58 UTC
## Expected Behavior
After adding the Xiaomi Bridge, according to wiki, all sensors linked to the Bridge show up inside the Inbox.
After adding a Sensor and Linking the Channels the Items should get its values from the Channel Link.

## Current Behavior
(2 VLANs, they can communicate with each other)
Xiaomi Bridge IP 192.168.111.4
openHAB IP 192.168.107.2

The Xiaomi Bridge does not show up inside the Inbox.
Added the Bridge myself with the IP and the DevKey, all according to the Wiki.
Bridge goes Online, Sensors appear inside the Inbox.
Added a Sensor makes them go Online.
Linking a Channel with an Item works, but does not deliver any Values.

## Steps to Reproduce (for Bugs)
1. 2 Networks 
2. openHAB and Xiaomi in different Network 
3. Install Xiaomi Binding
4. Search for Xiaomi things
5. Add the Bridge yourself
6. Add a Sensor
7. Link a Channel or more
8. Observe the void
9. Consult the openHAB Community
10. Nothing works, panic
11. Write and Issue on Github

## Your Environment
Linux smartoffice 4.9.28-v7+ # 998 SMP Mon May 15 16:55:39 BST 2017 armv7l GNU/Linux
Raspberry Pi 3 Model B
openHAB Version: 2.1.0 - release build -
Xiaomi: 250 | Active   |  80 | 2.1.0                  | Xiaomi Mi Smart Home Binding

Some logs: https://pastebin.com/idkBZnYJ

**Comment by BrutalBirdie** [comment] 2017-07-13 11:24
Tested within the same VLAN, with internet access for Xiamoi.
Now the Items are getting Values.

Follow up:
Testing with blocked communication for the Xiaomi Bridge.

**Comment by dimalo** [comment] 2017-07-15 09:02
Did you check if multicast traffic is correctly forwarded between the VLANs?

**Comment by BrutalBirdie** [comment] 2017-07-15 09:27
I will check that on Monday. But I am sure it is.

**Comment by dimalo** [comment] 2017-07-16 09:29
The bridge does not need an internet connection. Communication with the binding is done via multicast. When you already experienced it to work in the same vlan I'm pretty sure it has something to to with your network config.

**Comment by BrutalBirdie** [comment] 2017-07-27 21:33
I'm currently on vacation so I can't investigate into the issue after my vacation I will work on the issue again

**Comment by omribahumi** [comment] 2017-07-29 14:27
Not sure if this is the same issue, but I'm having a similar issue with the Xiaomi binding.

I have a button that functions properly and delivers events, but the magnet sensor events don't seem to be processed correctly.

I've enabled TRACE debugging for the `org.openhab.binding.mihome` logger and got this when I trigger the sensor:

```
2017-07-29 14:16:09.034 [DEBUG] [.mihome.internal.socket.XiaomiSocket] - Received Datagram from 192.168.1.225:4321 on Port 9898
2017-07-29 14:16:09.034 [DEBUG] [.mihome.internal.socket.XiaomiSocket] - Received Datagram from 192.168.1.225:4321 on Port 9898
2017-07-29 14:16:09.035 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"report","model":"magnet","sid":"XXXX","short_id":XXXX,"data":"{\"status\":\"open\"}"}
2017-07-29 14:16:09.037 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Updated "last time seen" for device XXXX
2017-07-29 14:16:09.037 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"report","model":"magnet","sid":"XXXX","short_id":XXXX,"data":"{\"status\":\"open\"}"}
2017-07-29 14:16:09.039 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Updated "last time seen" for device XXXX
2017-07-29 14:16:09.042 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Data received and notified 1 listeners
2017-07-29 14:16:09.043 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Thread Thread[Thread-982,5,main] waiting for data on port 9898
2017-07-29 14:16:09.043 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Data received and notified 1 listeners
2017-07-29 14:16:09.045 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Thread Thread[Thread-91,5,main] waiting for data on port 9898
```

But I don't get anything in the events.log.

When the button is double pressed, this is what I get in the log:
```
2017-07-29 14:22:58.021 [DEBUG] [.mihome.internal.socket.XiaomiSocket] - Received Datagram from 192.168.1.225:4321 on Port 9898
2017-07-29 14:22:58.021 [DEBUG] [.mihome.internal.socket.XiaomiSocket] - Received Datagram from 192.168.1.225:4321 on Port 9898
2017-07-29 14:22:58.023 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"report","model":"switch","sid":"XXXX","short_id":XXXX,"data":"{\"status\":\"double_click\"}"}
2017-07-29 14:22:58.025 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Updated "last time seen" for device XXXX
2017-07-29 14:22:58.023 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"report","model":"switch","sid":"XXXX","short_id":XXXX,"data":"{\"status\":\"double_click\"}"}
2017-07-29 14:22:58.027 [TRACE] [g.mihome.handler.XiaomiBridgeHandler] - Updated "last time seen" for device XXXX
2017-07-29 14:22:58.030 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Data received and notified 1 listeners
2017-07-29 14:22:58.033 [DEBUG] [home.handler.XiaomiDeviceBaseHandler] - Item got update: {"cmd":"report","model":"switch","sid":"XXXX","short_id":XXXX,"data":"{\"status\":\"double_click\"}"}
2017-07-29 14:22:58.038 [DEBUG] [home.handler.XiaomiDeviceBaseHandler] - Item got update: {"cmd":"report","model":"switch","sid":"XXXX","short_id":XXXX,"data":"{\"status\":\"double_click\"}"}
2017-07-29 14:22:58.043 [TRACE] [.mihome.internal.socket.XiaomiSocket] - Thread Thread[Thread-91,5,main] waiting for data on port 9898
```

And in the events.log:
```
2017-07-29 14:22:58.045 [ChannelTriggeredEvent     ] - mihome:sensor_switch:XXXX:button triggered DOUBLE_PRESSED
```

**Comment by dimalo** [comment] 2017-08-07 19:00
@BrutalBirdie any progress on this one, otherwise I request to close the issue.
@omribahumi not really the place bit nevermind, next time find aome help in the forum. Please check your Item and Thing config. Seems the button sends reports but there is no thing for it configured...

**Comment by omribahumi** [comment] 2017-08-12 09:00
@dimalo please read my comment again.
The button works fine. The problem is with the magnetic switch.
I mentioned the button to clarify that it's not entirely broken, and that my config is ok.

**Comment by dimalo** [comment] 2017-08-12 10:03
Sorry I meant “the magnet sensor sends reports but there is no thing for it”. Also it seems you have the binding running twice somehow. In the log with the magnet sensor you receive everything twice and the last lines show there are two threads listening instead of one. Please check if you have the marketplace version and the official version installed or two jars...
I have the magnet sensors myself and they work perfectly. Please recheck your config and compare to the readme, also resolve the double binding registration.

@kaikreuzer shall we close this issue, since @BrutalBirdie is not responding?

**Comment by kaikreuzer** [comment] 2017-08-12 13:35
Well, he mentioned that he is on holiday, so it might be expected to not being able to answer.
But as he can reopen the issue at any time, let's close it for now.

**Closed by kaikreuzer** 2017-08-12 13:35 UTC

**Comment by icahbko** [comment] 2018-08-14 18:44
Hi, any changes?
