### ISSUE TITLE
[deconz] Buttonevent not triggered/working

### ISSUE THREAD

**Issue by maxlein** [openhab/openhab2-addons#4483] opened 2018-12-31 19:59 UTC
## Expected Behavior
When adding a switch and a rule for a buttonevent trigger on the channel, the rule shall be triggered when pressing a button.

## Current Behavior
The buttonevent is published by deconz but not handled by openhab.
When testing with a little websocket client, the buttonevent is received. Also via Rest call.
presencesensor or temperaturesensor is working.

## Possible Solution
None

## Steps to Reproduce (for Bugs)
Deconz thing: 

`Bridge deconz:deconz:homeserver [ host="phoscon.local", apikey="D25175CADC" ] { // 
    presencesensor kitchen-presence        [ id="2" ]
    powersensor osram-power           [ id="3" ]
    presencesensor dining-presence        [ id="6" ]
    switch remote-buttonevent        [ id="7" ]
    powersensor aqara1-power           [ id="8" ]
    temperaturesensor aqara1-temp           [ id="8" ]
    temperaturesensor aqara2-temp           [ id="11" ]
}`

Rule:

`rule "tradfri remote handling"
when
   Channel "deconz:switch:homeserver:remote-buttonevent:buttonevent" triggered
then
    logInfo("TradfriRemote", "Tradfri switch event {} was triggered", receivedEvent)
    switch(receivedEvent.getEvent()) {
        case "1002": {
            night_lights.sendCommand(ON)
        }
        case "2002": {
            night_lights.sendCommand(OFF)
        }
    }
end`

Response from websocket client:

`e: "changed"  
id: "7"
r: "sensors"
state: {buttonevent: 1002, lastupdated: "2018-12-31T19:53:36"}
t: "event"
uniqueid: "90:fd:9f:ff:fe:f4:e5:b7-01-1000"`

## Context
This bug occurs when using a Tradfri remote connected to deconz and trying to receive the button events by a rule.

## Your Environment

* Version used: openHAB 2.4.0-1
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
Release = Raspbian GNU/Linux 9 (stretch)
Kernel = Linux 4.14.79-v7+

**Comment by cweitkamp** [comment] 2019-01-02 19:31
This is a duplicate of #4402 which has been fixed with #4406.

**Closed by cweitkamp** 2019-01-02 19:31 UTC
