### ISSUE TITLE
[REST API] cannot access web interface in 2.4.0.M7

### ISSUE THREAD

**Issue by mattnl** [openhab/openhab2-addons#4302] opened 2018-12-02 11:33 UTC
When accessing the REST API ([http://10.100.100.210:8081/doc/index.html](url)) through a web browser with the 2.4.0.M7 build, I just get the following message:

`fetching resource list: http://10.100.100.210:8081/rest/swagger.json; Please wait.`

but nothing happens. I just did a clean install of the M7 build, same effect. My default port is set to 8081.

misc-restdocs - 2.4.0.M7 is installed.

Chrome dev tools show:

```
swagger-ui.min.js:3 Uncaught TypeError: Cannot read property '$ref' of undefined
    at t.exports.a.resolveTo (swagger-ui.min.js:3)
    at t.exports.a.resolveTo (swagger-ui.min.js:3)
    at t.exports.a.resolve (swagger-ui.min.js:2)
    at response (swagger-ui.min.js:2)
    at i (swagger-ui.min.js:2)
    at e.on.response (swagger-ui.min.js:2)
    at swagger-ui.min.js:2
    at f.callback (swagger-ui.min.js:13)
    at f.<anonymous> (swagger-ui.min.js:13)
    at f.r.emit (swagger-ui.min.js:13)
```

Please see also the community forum:
[https://community.openhab.org/t/oh-2-4-0-m7-testing-results/58475/25](url)

**Comment by kaikreuzer** [comment] 2018-12-02 16:04
Sounds similar to https://github.com/swagger-api/swagger-ui/issues/1677.
I have no clue, what has changed and when it last worked, though.

Anybody willing to look into it?

**Comment by AngelosF** [comment] 2018-12-02 16:12
I checked 2.4.0.M6 and it works there.
I haven't checked which snapshot build introduced this issue.
S1445 & S1447 have the same issue

I will try to identify the root-cause and report back with my findings

**Comment by kaikreuzer** [comment] 2018-12-02 16:14
Thanks. My best guess would be that it is related to https://github.com/openhab/openhab-core/pull/435 as this now prevents the rest/swagger bundles to be completely restarted.

**Comment by AngelosF** [comment] 2018-12-04 19:15
I haven't found the time to debug this one :(

openHAB 2.4.0 Build #1448 still has the same issue

I will try again now but someone needs to look into this since it should be fixed before the next Milestone (or 2.4 Release)

**Comment by bnjroos** [comment] 2018-12-06 05:55
I have the same issue, is there a way to downgrade from misc-restdocs - 2.4.0.M7 to a lower build just on that package ?
Thanks

**Comment by kaikreuzer** [comment] 2018-12-06 19:00
I have searched a lot and was luckily able to reproduce it in the IDE. It turned out that https://github.com/eclipse/smarthome/pull/6638 makes it work again.

**Comment by kaikreuzer** [comment] 2018-12-07 13:12
Just tested it on the latest distro snapshot and it seems to work fine again!

**Closed by kaikreuzer** 2018-12-07 13:12 UTC
Labels: help wanted
