### ISSUE TITLE
[exec] Binding suggestions

### ISSUE THREAD

**Issue by steve-bate** [openhab/openhab2-addons#1661] opened 2017-01-06 22:29 UTC
@kgoderis 

Based on discussions in the forums, users are having difficulty with the new Exec binding. Here are some recommendations based on those discussions and reviewing the implementation. This is primarily to start discussions. The list may not be complete.

* The "switch" use case should be supported better. This could either be direct support or could be made easier through some of the following suggestions. Currently, Switch items are not supported although a workaround is to use a String item and associate it with a Switch widget in the site map.
* Channel options are being specified at the thing-level. This can be confusing and error-prone. For example, the 'autorun' option only applies to the 'input' channel. As another example, the 'input' channel is command event-driven and doesn't need to be polled periodically so the 'interval' option (and maybe others) don't seem applicable to it.
* A missing 'interval' configuration should mean "no polling" rather than using a default interval of 60 seconds. See also #1533.
* The input channel behavior that ignores repeated commands should be reconsidered. It may be desirable to issue "repeated" commands if an item state is modified externally (e.g., a light switch with both manual and OH2 control). If input channel command event throttling is a desired feature we should make it an optional configuration parameter.
* The documentation needs improvement: at a minimum, there should be additional examples demonstrating all config options and a switch control example configuration.

See also: https://community.openhab.org/t/exec-binding-do-not-work/17599/50

**Comment by kgoderis** [comment] 2017-01-10 21:01
@kaikreuzer any thoughts on all of this? I am ok to improve things, but less comfortable hacking together stuff just to mimic OH1, potentially breaking away from any OH2/ESH standard code conduct. wdyt?

**Comment by kgoderis** [comment] 2017-01-10 21:02
@steve-bate just FYI, pls do not wait for me to propose a PR to improve things. I think it will be easier to discuss around actual code then hypothetical examples and use cases (here or on the forum...)

**Comment by steve-bate** [comment] 2017-01-11 11:28
@kgoderis These aren't hypothetical use cases. As you saw in the forums, users are actually trying to use the Exec binding in the ways I'm describing and are having difficulties. I understand that you may not have time to improve the binding. I also don't have time to create a PR just for discussion purposes. However, if you have questions about the suggestions I listed, I will to try to clarify any of them.

**Comment by kaikreuzer** [comment] 2017-01-11 12:08
> @kaikreuzer any thoughts on all of this? I am ok to improve things, but less comfortable hacking together stuff just to mimic OH1, potentially breaking away from any OH2/ESH standard code conduct. wdyt?

At a quick glace, it all sounds like fair requests. I don't see anything that would be against the general ESH architecture, but it rather looks like an evolution of the existing Exec 2 binding.

But I agree with you that you should not hack away those things as quickly as possible, but rather think about the best implementation. Meanwhile, existing Exec1 users should simply stick to that version of the binding - there is no reason not to use it.

**Comment by kgoderis** [comment] 2017-01-11 16:56
> @kgoderis These aren't hypothetical use cases.

I rather meant that the way these use cases are explained is sometimes unclear. 

Give me some time to reflect on all the issues raised.

**Comment by steve-bate** [comment] 2017-01-14 12:57
Thanks for the PR. I've made some comments on the documentation and code and I feel like this is definitely a move in the right direction. (Just for the record, I personally was fine with the String item, but several other users in the forum had complained about it so I included it in the suggestion list.)

I still think it would be better to use channel-level rather than thing-level configurations for the channel configurations (interval, runOnInput/autorun, etc.). It appears the platform supports that approach. See the systeminfo binding for a complex example.

Some additional suggestions:
* Define a channel group for all the new input channel types
* Commands to input channel always trigger execution
    * Remove autorun/runOnInput configuration (simplification)
    * Remove repeatEnabled (simplification)
* Commands to run channel uses current input channel state rather than previous command
* Don't use %2$s format specifier for lastInput (or current state). The inflexibility of this type of specifier will create difficulties for evolving the binding if we decide to support additional data for the command string. Several more flexible alternatives can be found [here](http://stackoverflow.com/questions/2286648/named-placeholders-in-string-formatting).

**Comment by steve-bate** [comment] 2017-01-14 15:02
@kgoderis, I've done some more testing and there is a problem. For example:
```
Thing exec:command:switch_control [command="/tmp/switch_control.sh %2$s" ]
Thing exec:command:switch_monitor [command="/tmp/switch_control.sh check"]
```
```
Switch ExecSwitch {channel="exec:command:switch_control:switchInput", channel="exec:command:switch_monitor:stringOutput", autoupdate=false }
```
The stringOutput channel cannot write the StringType state update to the Switch item (it's not one of the accepted types). Log entries:
```
2017-01-14 09:30:11.393 [DEBUG] [.c.thing.internal.ThingManager:399  ] - Delegating update 'ON' for item 'ExecSwitch' to handler for channel 'exec:command:switch_monitor:output'
2017-01-14 09:30:11.393 [DEBUG] [s.c.internal.items.ItemUpdater:72   ] - Received update of a not accepted type (StringType) for item ExecSwitch
```
@kai, is there any possibility to support a channel that operates on _any_ channel type?

**Comment by kgoderis** [comment] 2017-01-14 15:21
Ah... That is not a real issue I am afraid. It is up to the user to define a channel in the .items that *is* compatible with the choose Item. This is by design and holds true for every binding in fact. 

Now, cfr your example, you should use the switchOutput channel on the switch_monitor thing to make it work

**Comment by kgoderis** [comment] 2017-01-14 15:24
> Define a channel group for all the new input channel types

That is not possible, as channels and channel groups can not be combined

> Commands to input channel always trigger execution
> Remove autorun/runOnInput configuration (simplification)
> Remove repeatEnabled (simplification)

well, I want to cover all scenario's, these are configurable and have a default value

> Commands to run channel uses current input channel state rather than previous command

I am not sure I understand this one. Why would a trigger on "run" have to use the previous command?

> Don't use %2$s format specifier for lastInput (or current state). The inflexibility of this type of specifier will create difficulties for evolving the binding if we decide to support additional data for the command string. Several more flexible alternatives can be found here.

This is in here because it was also the case in the OH1 binding. What alternative are you thinking about?

K

**Comment by steve-bate** [comment] 2017-01-14 15:57
> Ah... That is not a real issue I am afraid. It is up to the user to define a channel in the .items that is compatible with the choose Item. This is by design and holds true for every binding in fact.
> Now, cfr your example, you should use the switchOutput channel on the switch_monitor thing to make it work

Thanks. That's a good point. I may have overlooked something but it looks like the SwitchOutput channel is only updated when there's an exception.  The StringOutput is always updated.

**Comment by steve-bate** [comment] 2017-01-14 16:07
>> Define a channel group for all the new input channel types

> That is not possible, as channels and channel groups can not be combined

What do you mean?  What's the purpose of channel groups? It seems to be used that way in the systeminfo binding.

```
	<channel-group-type id="memoryGroup">
		<label>Physical memory</label>
		<description>Physical memory information</description>
		<channels>
			<channel id="total" typeId="total" />
			<channel id="available" typeId="available" />
			<channel id="used" typeId="used" />
			<channel id="availablePercent" typeId="availablePercent" />
		</channels>
	</channel-group-type>
```
> well, I want to cover all scenario's, these are configurable and have a default value

I think the scenarios are supported in other ways without the extra configurations and using the changes I suggested. I can't be certain since I don't know which types of scenarios you have in mind.

> I am not sure I understand this one. Why would a trigger on "run" have to use the previous command?

Good question. I don't think it should. Maybe I'm misunderstanding something but isn't that how it is currently implemented? A run channel ON command causes the "periodicExecutionRunnable" (a one-shot in this case) to execute. In that scheduler callback, the "lastInput" is provided to the command formatter if it's not null (and I think it might never be null now that it's initialized to an empty string). The "lastInput" is the most recent stringified Command sent to the input channel, right?

If you continue to use lastInput, you probably don't want to initialize it to an empty string but instead use an empty string only for formatting purposes if lastInput is null. For example, removing the if/then statement conditioned on lastInput != null and instead do something like...

```
commandLine = String.format(commandLine, Calendar.getInstance().getTime(), lastInput != null ? lastInput : "");
```
> What alternative are you thinking about?

See the link in the my previous response.

**Comment by kaikreuzer** [comment] 2017-01-16 09:23
> @kai, is there any possibility to support a channel that operates on any channel type?

I guess you mean on any item type, right? No, this is not possible.
BUT, I still do not think that we need to declare [all these different channel types](https://github.com/kgoderis/openhab2/blob/48743cc63f5301901a53ff84e4b67d4c26d38e06/addons/binding/org.openhab.binding.exec/ESH-INF/thing/thing-types.xml#L60-L119).

Instead, the binding could simply support ["custom channels" defined on the Thing](https://github.com/eclipse/smarthome/blob/master/docs/documentation/features/dsl.md#defining-channels) (not its type).

This means that you could simply define your Thing as
```
Thing exec:command:switch_control [command="switch_control.sh %2$s", runOnInput=true, repeatEnabled=true] {
    Channels:
        Switch : input
        Switch : output
}

Thing exec:command:apc [command="/usr/local/bin/apcaccess  status", interval=15, timeout=5] {
    Channels:
        String : output
}
```
Your channel ids will always be "input" resp. "output", but depending on your Thing they can be linked to different item types.

**Comment by steve-bate** [comment] 2017-01-16 10:12
> I guess you mean on any item type, right?

Yes, that's what I meant.

> Instead, the binding could simply support "custom channels" defined on the Thing (not its type).

Sounds interesting. Thanks!

**Comment by kgoderis** [comment] 2017-01-17 19:27
@kaikreuzer @steve-bate 
> BUT, I still do not think that we need to declare all these different channel types.

I think you are definitely right, although the custom channels are very elegant indeed, they might confuse users a bit more as well wrt the migration from OH1 to OH2. Now, it would certainly add a bit more complexity in the binding in the sense that one has to do checks on the existence of certain channels (e.g. is there an input channel,..), and do some Type conversions as well (e.g. the output from a script i.e. "ON" -> OnOffType is the chosen Type is a Switch, and so forth) 

What direction shall we take?

**Comment by kgoderis** [comment] 2017-01-17 19:29
> What do you mean? What's the purpose of channel groups? It seems to be used that way in the systeminfo binding.

@steve-bate FYI, https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/bindings/thing-definition.md : "A thing can only have direct channels or channel groups, but not both"

**Comment by kgoderis** [comment] 2017-01-17 19:30
> Good question. I don't think it should. Maybe I'm misunderstanding something but isn't that how it is currently implemented?

"lastInput" = in the sense of the most recent input. Elsewhere in the code I use previousInput for the input before the last Input ;-)

**Comment by steve-bate** [comment] 2017-01-17 21:45
>> Good question. I don't think it should. Maybe I'm misunderstanding something but isn't that how it is currently implemented?

> "lastInput" = in the sense of the most recent input. Elsewhere in the code I use previousInput for the input before the last Input ;-)

I understood the "last" part of the variable name. The "input" part is ambiguous: it could be the last command or the last state update. Of course, if someone digs into the code enough they'll figure out how it's actually used. In any case, I was answering your question...

> Why would a trigger on "run" have to use the previous command?

Since "lastInput" is the previous command sent to the linked item, it will be non-null if a command was ever sent to the input channel item. That previous Command string will be used for the exec command formatting whether the execution is triggered by an input channel autorun or a run item ON command. This could be quite confusing for a user if they expect the input state to be provided to the command. For example,

1. Configure a thing with a %2$s specifier.
1. Set the input channel item state to "foo".
2. Send an ON command to the run channel item, expecting "foo" to be provided to script.
3. ERROR: failed execution since no command was ever sent to input item and formatting fails (or, with the recent PR, a empty string would be provided instead).

**Comment by steve-bate** [comment] 2017-01-17 21:52
> What direction shall we take?

I prefer the custom channel approach compared to the other options. However, it is going to be verbose even for relatively simple use cases. Also, I've noticed it's easy to mistype the syntax and the result are cryptic NPE's in the log file rather than a meaningful parser error message.

**Comment by kgoderis** [comment] 2017-01-18 14:14
> Configure a thing with a %2$s specifier.
> Set the input channel item state to "foo".
> Send an ON command to the run channel item, expecting "foo" to be provided to script.
> ERROR: failed execution since no command was ever sent to input item and formatting fails (or, with the recent PR, a empty string would be provided instead).

Ok - that means we have to flesh out/copy&paste the handleUpdate() then.

**Comment by steve-bate** [comment] 2017-01-25 11:34
@kgoderis Following up on the command formatting, its looks like the Apache commons [strSubstitutor](https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/text/StrSubstitutor.html) could be useful. If you created a custom [StrLookup](https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/text/StrLookup.html) implementation you could have command templates like:
```
/bin/myscript.sh ${input} ${time:%tY-%tm-%td}
```
where the placeholders are named. With a little extra effort, you could support inserting the state of *any* item (including multiple "input" items) by refererencing its name. The only need for an explicit input channel would be for auto-triggering the command execution when an item command is sent.

**Comment by semaro** [comment] 2017-02-03 14:36
I hope its the right place to post this.
For the use with "init-script"-like implementations it would be helpful, if the things definition would be done with one definition and when linked to an switch-item do three things:
-send the (in the thing-definition) given command line with an following "ON" when turn the switch on
-send the given command with following "OFF" when turn the switch off
-refresh the status of the switch by reading the "status" when the given command is sent with following "status"

From what i have read in the openHAB-Forum thats something, more people have used the old exec-Binding for, doing all in one line:
`Switch so_pin29 "Schalter 29"  {exec=">[ON:/opt/openhab/scripts/relais29.sh ON] >[OFF:/opt/openhab/scripts/relais29.sh OFF] <[/opt/openhab/scripts/relais29.sh status:6000:REGEX((.*?))]"}`

So just as suggestion would it be possible to organize new behavior in this way:
Things:
`exec:command:relais29 [command="/opt/openhab/scripst/relai29.sh %2$s", transform="REGEX((.*?))", oncommand="ON", offcommand="OFF", statuscommand="status", statusrefresh=true/false, refreshinterval=1]`
(the commands maybe only optional only if wanted something else then the given standard values, the statusrefresh decides if the switch uses the above mentioned third command)
 and the the item declaration as:
Switch so_pin29 "Schalter 29" {channel="exec:command:relais29:switch"}

I am not sure if it is possible to work in this way, maybe in a bit different declaration.

**Comment by kgoderis** [comment] 2017-02-03 16:27
@semaro Your suggestion narrows down the exec binding to switches. That is just a use case amongst many others.....

@steve-bate Will look into the StrLookup stuff asap

**Comment by semaro** [comment] 2017-02-03 18:12
@kgoderis ahh, of course i didn't mean my suggestion as just the only option to use.
What i have in mind was more to create one channel (like it is now with "output" or "run"), that, when a thing is declared the "switch"-channel could be used in this way.

**Comment by davidgraeff** [comment] 2019-03-18 08:49
Not sure, but I think those kind of discussions now go into the community forum. And there doesn't seem to be any progress as well. Closing for now. Please also open individual Issues instead of a conglomeration. Thanks.

**Closed by davidgraeff** 2019-03-18 08:49 UTC
Labels: discussion
