### ISSUE TITLE
[max] Change of set temperature not working for items

### ISSUE THREAD

**Issue by cubistico** [openhab/openhab2-addons#4217] opened 2018-11-11 17:55 UTC
## Expected Behavior

When changing a set temperature through the UI, the new temperature should be set at the thermostat.

## Current Behavior

I've set up up a new openHAB installation with the latest openHabian image. I've added the MAX! binding and added some of the discovered Things, like radiator thermostats and wall thermostats. I've added new items - among others - for setting the temperature from within PaperUI.

However, when I change the temperature, the change will be sent according to the log, but it does not seem to arrive at the thermostat device. 

I finally got this working by editing the item without actually changing something. After the edit, the temperature could be set as expected. This behaviour was reproducable with two thermostats.

## Possible Solution

I assume that, when creating the Thing automatically from the UI, some setting is not properly set or defaulted incorrectly. In the UI however, it looks okay, so probably the incorrect value is not displayed or defaulted in the display. 

It looks like editing and saving the Item, the incorrect value gets corrected, as after that, the set temperature started to work as expected.

## Steps to Reproduce (for Bugs)

1. Create a new set temperature Item from a MAX! thermostat from within the Things list
2. Try to set the temperature -> does not work
3. Edit and save the Item without changing it
4. Setting temperature now works

## Context

openHAB with MAX! Bindung using MAX! Cube with radiator and wall thermostats.

## Your Environment

* openHAB 2.3.0 Release Build
* openhabianpi-raspbian-201804031720

**Comment by cubistico** [comment] 2018-11-11 19:15
I‘ve seen the other issue, but decided to open a new one, because it refers to an upgrade problem, while the one I described has occurred in a completely fresh installation.

**Comment by cubistico** [comment] 2018-11-11 23:16
After a reboot, the issue re-occurred. The above mentioned work-around (editing without changing) worked again. 

After the edit, the set temperature is NULL before it‘s set.

**Comment by cubistico** [comment] 2018-11-14 23:16
Forgive me if I'm nagging, but doesn't anyone have an idea how to track down the problem? It's driving me nuts, especially because it now occurs each time after the set temperature was changed.
I'm ready and willing to provide any details. Any log trace recommended?

**Comment by wborn** [comment] 2018-11-15 22:42
Maybe @marcelrv knows if this is a known issue or fixed in 2.4.0-SNAPSHOT?

**Comment by marcelrv** [comment] 2018-11-16 16:39
I updated today my environment as in in a clean setup this issue is not reproducable...
Upgrading from 2.3 I also encountered this issue.

The fix: delete your thermostat thing and add it again, that at least did the trick for me
There is still something weird going on as it queues the command twice when I update in paperUI... but at least it works.


```
17:34:09.275 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'Max_St_Set' received command 25
17:34:09.276 [INFO ] [arthome.event.ItemStatePredictedEvent] - Max_St_Set predicted to become 25
17:34:09.278 [INFO ] [smarthome.event.ItemStateChangedEvent] - Max_St_Set changed from 24.0 to 25
17:34:09.278 [DEBUG] [internal.handler.MaxCubeBridgeHandler] - Command queued id 19 (KEQ0648949-set_temp:25).
17:34:09.278 [DEBUG] [internal.handler.MaxCubeBridgeHandler] - Command queued id 18 (KEQ0145172-set_temp:25 °C).
17:34:09.279 [DEBUG] [internal.handler.MaxCubeBridgeHandler] - Command org.openhab.binding.max.internal.handler.SendCommand@45948fab[id=18,channelUID=max:thermostat:KEQ0565026:KEQ0145172:set_temp,command=25 °C,cubeCommand=<null>,serialNumber=KEQ0145172,key=KEQ0145172-set_temp,commandText=25 °C] sent to MAX! Cube at IP: 192.168.3.9
17:34:09.280 [DEBUG] [internal.handler.MaxCubeBridgeHandler] - Sending request #104 to MAX! Cube
17:34:09.280 [TRACE] [internal.handler.MaxCubeBridgeHandler] - Write string to Max! Cube 192.168.3.9: s:AABAAAAAB7bnADI=

```

**Comment by cubistico** [comment] 2018-11-16 18:06
> Upgrading from 2.3 I also encountered this issue.

Sorry, I don't get it - so which version are you running now? 2.3.0? And I am using a clean setup with nothing in it but the MAX! Cube with this binding and items for two of its thermostats. I was starting my setup from scratch when I ran into this problem.

Deleting and adding had done the trick for me, too, but only at first! After 2 days (!), it stopped working again. Seems like a problem that isn't easy to track down.

**Comment by cubistico** [comment] 2018-11-16 18:42
Removing an readding the Item, also removing and readding the Thing, both don't help me here. After doing so, I can set temperature just once: 
`[vent.ItemStateChangedEvent] - WandthermostatKino_SetTemperature changed from NULL to 23.0 ℃`
After that, I see the log, but it does not work:
`[vent.ItemStateChangedEvent] - WandthermostatKino_SetTemperature changed from 23.0 ℃ to 20 ℃`

It seems to me as if works only as long as the internal value is NULL?!

**Comment by marcelrv** [comment] 2018-11-16 19:02
I think it all has to do with the introduction of the QuantityType #3506 & #4114.
It ignores all set temps that are DecimalType which is how older versions will send it

**Comment by cweitkamp** [comment] 2018-11-16 20:16
We incorporated a lot of changes in the binding since OH2.3 release. One of them was the support of the UoM. If you try to use an Item of item type `Number:Temperature` with the binding version of OH2.3 release it will not work. You have to use item type `Number`. @cubistico can you please double check if your setup fulfills these restrictions?

**Comment by cubistico** [comment] 2018-11-16 21:36
I had indeed set up the Items as Number:Temperature (which seemed only natural). I've changed it to plain Number, and setting the temperature seems to work now! I'll make some more tests, but I am fairly confident that this fixes my problems. Thanks!

Taking another look at the docs, I find that they state Number:Temperature as the correct item type, but looking closer that's in the the lastest version, while when I select version 2.3.0, it states Number.

I was not aware and find it quite confusing that by default, the docs obviously explain the current development version, and not the last stable version!

**Comment by cweitkamp** [comment] 2018-11-21 13:42
Shall we consider to close this issue?

We have another confirmation in the community that it is working again with OH 2.4.0 M6 (milestone build).

https://community.openhab.org/t/maxcubebridgehandler-io-error-occurred-during-execution-read-timed-out/48414/36

**Comment by cubistico** [comment] 2018-11-21 13:47
Okay for me. Should I close it myself?

**Comment by cubistico** [comment] 2018-11-21 13:50
However, I'd like to open an issue for displaying the documentation page for the latest release by default, not the current development version, which - for me - would have clarified things without opening this issue first. Not sure though where to do that?

**Comment by cweitkamp** [comment] 2018-11-21 13:53
@cubistico Please file an issue for discussion over here: https://github.com/openhab/openhab-docs/issues. Thanks.

**Closed by cweitkamp** 2018-11-21 13:53 UTC
