### ISSUE TITLE
[chromecast] Jenkins created bundle with outdated XML files causing IllegalStateException

### ISSUE THREAD

**Issue by ScottKinSF** [openhab/openhab2-addons#4468] opened 2018-12-28 18:02 UTC
When I restart OH2, I see numerous exceptions thrown by the chromecast binding.

## Expected Behavior
No exceptions thrown by the chromecast binding on startup

## Current Behavior
Multiple exceptions thrown by the chromecast binding at startup. Once startup is complete, simple tests of the chromecast binding indicate it is functioning correctly.

## Possible Solution
No clue.

## Steps to Reproduce (for Bugs)
1. Stop currently running OH2.
2. Update to OH2 2.5.0 SNAPSHOT #1479.
3. Clear contents of /var/lib/openhab2/{cache,tmp}/*
4. Start OH2.
5. Re-start OH2 multiple times, exceptions are found in the logs on every start.

## Your Environment
My system is an RPi 3B running up-to-date OpenHABian.
Installed version of openHAB is 2.5.0 SNAPSHOT #1479. 
The chromecast binding is installed via /etc/openhab2/services/addons.cfg. There are no jar files present in /usr/share/openhab2/addons/.
```
openhab> bundle:list | grep -i chromecast
253 │ Active   │  80 │ 2.5.0.201812250308     │ Chromecast Binding
```
[chromecast-binding-errors.log](https://github.com/openhab/openhab2-addons/files/2715407/chromecast-binding-errors.log)

**Comment by wborn** [comment] 2018-12-29 10:10
It's probably some local hiccup cause I can't reproduce this with:

```
openhab> bundle:list | grep -i chromecast
222 │ Active   │  80 │ 2.5.0.201812281027     │ Chromecast Binding
```

**Comment by wborn** [comment] 2018-12-29 15:59
The Chromecast Binding JAR inside [openhab-addons-2.5.0-SNAPSHOT.kar](https://ci.openhab.org/job/openHAB-Distribution/1479/artifact/distributions/openhab-addons/target/openhab-addons-2.5.0-SNAPSHOT.kar) for build # 1479 contains generated XML files that were generated in some previous build:

![org openhab binding chromecast-2 5 0-snapshot jar _004](https://user-images.githubusercontent.com/12213581/50540008-4f93f600-0b8a-11e9-95aa-99fcf8bb23d7.png)

The files from December 20th should not be there and contain references to classes that were moved to another package. That explains the exceptions in the log file:

```
Caused by: java.lang.IllegalStateException: Could not load implementation object class org.openhab.binding.chromecast.internal.ChromecastHandlerFactory
```

Maybe we can cleanup all modified/untracked files from the Jenkins workspace before building @kaikreuzer ?

**Comment by ScottKinSF** [comment] 2018-12-29 16:44
Ich danke dir,@wborn. Great to get to the bottom of that problem. Is it possible that the 2.4.0 stable release had the same issue, as others are reporting symptoms similar to mine after upgrading to 2.4.0 stable?

**Comment by cweitkamp** [comment] 2019-02-11 13:00
@ScottKinSF @wborn The issue is solved, right? Can we close it?

**Comment by ScottKinSF** [comment] 2019-02-11 14:14
> The issue is solved, right? Can we close it?

Indeed, it is solved for me, running snapshot S1502 here.

**Closed** 2019-02-11 15:57 UTC
