### ISSUE TITLE
sysinfo binding: CPU temperature not delivered on a Raspberry PI 2

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab2-addons#1324] opened 2016-10-13 15:16 UTC
The sysinfo binding provides a lot of useful information on my RPi2, but obviously not the CPU temperature while other values work pretty well:
![2016-10-13 15_05_22-home](https://cloud.githubusercontent.com/assets/22266373/19354797/4a67bee4-9168-11e6-9d80-42106703db34.png)
Someone said, it may not possible on Raspberrys - but other simple workarounds deliver the desired information easily.

In my loginfo I found only this hint:
22:32:12.601 [ERROR] [platform.linux.LinuxCentralProcessor] - Couldn't find physical processor count. Assuming 1.
22:32:12.898 [ERROR] [platform.linux.LinuxCentralProcessor] - Unable to parse /proc/77/stat

Item definition:
`Number RaspberryCPUTemp                 "Temperatur RPi2 [%.1f °C]"                             { channel="systeminfo:computer:openHABianPi:sensors#cpuTemp" }`

PS: I'm running the latest snapshot via openHABian

**Comment by svilenvul** [comment] 2016-11-29 09:48
@Boby71 
Could you please try with the latest version ?
If the issue is still present, should be reported to https://github.com/oshi/oshi.

**Comment by Halvhjearne** [comment] 2016-12-29 01:07
just fyi, it still does not work for some reason, not sure if there is a diffrence cause i installed with default raspbian img, but it seems a lot of the systeminfo options does not return anything, or it returns invalid readings, for me ...

**Comment by rtvb** [comment] 2017-01-06 13:51
My RPi also returns 0 degrees temperature.

```
bundle:list
188 | Active   |  80 | 2.0.0.201701061129    | Systeminfo Binding
```

**Comment by rtvb** [comment] 2017-01-16 17:58
Entering
```
log:set DEBUG org.openhab.binding.systeminfo
```

(or even `TRACE`) does not show any additional logging, so I can't tell what's happening.

**Comment by rtvb** [comment] 2017-01-16 18:34
The channel `sensors#cpuVoltage` also report `0` on the RPi2.

**Comment by cweitkamp** [comment] 2017-04-27 08:42
Hi all,

I just checked cpu temperature and voltage with the latest version of the systeminfo binding on a RPi2. Both channels return no values for me. I am going to open an issue in `https://github.com/oshi/oshi`.

It is possible to read those values on my rasbian - maybe on openhabian too- with the following two shell commands. I am really sure that they can be read somehow by the oshi library too.
```
pi@raspberry-openhab:~ $ vcgencmd measure_temp
temp=37.9'C
```
and
```
pi@raspberry-openhab:~ $ vcgencmd measure_volts
volt=1.3125V
```

**Comment by cweitkamp** [comment] 2017-07-07 06:36
@svilenvul There was a new release of the OSHI library (version 3.4.3) which includes a partial fix for this issue (reading temperature values on RPi's). Would you like to update it in the systeminfo binding?

**Comment by svilenvul** [comment] 2017-07-10 07:24
If there are no API changes, the process is straightforward and well described - https://github.com/openhab/openhab2-addons/tree/d930fd4113f71c4112fb4c3b69e8a52400f68c73/addons/binding/org.openhab.binding.systeminfo#updating-this-binding. 

Please feel free to open a PR.

**Comment by cweitkamp** [comment] 2017-07-10 18:21
PR #2449

**Comment by martinvw** [comment] 2017-07-13 04:56
It should be fixed in the last snapshot or partly, maybe @cweitkamp can explain more about that.

**Closed** 2017-07-13 04:56 UTC

**Comment by cweitkamp** [comment] 2017-07-13 05:13
On Raspberry PIs (in detail on linux based OS) the channel `sensors#cpuTemp` now returns the current measured temperature of the CPU correctly.
The channel `sensors#cpuVoltage` returns 0 as before.
