### ISSUE TITLE
[chromecast] Items are updated every few seconds even if nothing changed

### ISSUE THREAD

**Issue by s4y** [openhab/openhab2-addons#4277] opened 2018-11-25 14:18 UTC
## Expected Behavior
The Chromecast binding posts updates to its channels when (and only when) state changes.

## Current Behavior
The Chromecast binding posts updates to several of its channels (status, App, AppId, AppStatus, Idling, and Volume) every ~30 seconds, even if their values haven't changed. This causes extra work for programs that, for example, consume the `/rest/events` stream.

The periodic updates look like this:

```
event: message
data: {"topic":"smarthome/things/chromecast:chromecast:xxx/status","payload":"{\"status\":\"ONLINE\",\"statusDetail\":\"NONE\"}","type":"ThingStatusInfoEvent"}

event: message
data: {"topic":"smarthome/items/Chromecast_App/state","payload":"{\"type\":\"String\",\"value\":\"Backdrop\"}","type":"ItemStateEvent"}

event: message
data: {"topic":"smarthome/items/Chromecast_AppId/state","payload":"{\"type\":\"String\",\"value\":\"E8C28D3C\"}","type":"ItemStateEvent"}

event: message
data: {"topic":"smarthome/items/Chromecast_AppStatus/state","payload":"{\"type\":\"String\",\"value\":\"\"}","type":"ItemStateEvent"}

event: message
data: {"topic":"smarthome/items/Chromecast_Idling/state","payload":"{\"type\":\"OnOff\",\"value\":\"ON\"}","type":"ItemStateEvent"}

event: message
data: {"topic":"smarthome/items/Chromecast_Volume/state","payload":"{\"type\":\"Percent\",\"value\":\"100\"}","type":"ItemStateEvent"}
```

## Possible Solution
I'm not sure if there's a standard way to handle this in bindings, but one option is for the binding to only update each of its channels if the value has changed.

Another option would be for OpenHAB to drop item updates that don't change their values, either from `/rest/events` or when receiving updates from bindings. I'm new to OpenHAB and assuming there's a reason things don't work this way now 🙂.

## Steps to Reproduce (for Bugs)
1. Install the Chromecast binding on a network with a Chromecast.
2. Add the discovered Chromecast thing, set up an item that tracks its Volume channel.
3. `curl http://127.0.0.1:8080/rest/events`, and wait 30s or so.

## Context
I sometimes use `/rest/events` for debugging, and it's annoying to have to look past a pile of Chromecast updates. My other bindings don't seem to do this, so it's *just* updates from this binding that are adding noise. I'm also experimenting with, e.g. battery-powered control panels that consume the event stream, and for power reasons I would prefer if they didn't have to process these extra messages.

## Your Environment
* Version used: openHAB 2.4.0 Milestone Build, Chromecast binding 2.4.0.M5.
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): *I'm not sure where to find this information and what would be relevant.*
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Raspbian stretch, RPi 3.

**Comment by davidgraeff** [comment] 2018-12-03 10:22
Usually you don't keep the state in your binding, so you can't compare to a previous value in a binding. This is the task of the framework (openHAB -> Eclipse Smarthome).

**Comment by cweitkamp** [comment] 2019-02-11 13:03
Closing this issue.

**Closed by cweitkamp** 2019-02-11 13:03 UTC

**Comment by s4y** [comment] 2019-02-11 15:18
Sorry for not following up on this. It still “feels wrong” (and obviously my own instincts here are limited!) that the Chromecast binding is the only one I’ve seen that spams out `ItemStateEvent`s every few seconds while nothing is changing. Is there any other better behavior, or a reason why the Chromecast binding in particular should behave this way?

**Comment by davidgraeff** [comment] 2019-02-11 15:21
Just ignore `ItemStateEvent`s. You are actually interested in `ItemChangeEvent`s. The core is just logging everything although this is really not worth logging. But it does the right think. It compares the last state to the current one and only emits a change event if actually something changed.

**Comment by s4y** [comment] 2019-02-11 16:21
All right. Just to make sure we’re on the same page, this isn’t logs, it’s what I get as a client of `/rest/events`.

**Comment by davidgraeff** [comment] 2019-02-11 16:28
Hm. How should I explain it differently.

The architecture of OH is so that bindings do not keep state. If they are required to poll a remote device to find out about its state those bindings are supposed to send all those refreshed (but not necessarily changed) states to the openHAB event bus. So the chromecast binding is doing correctly.

The eventbus on the other hand in our very naive implementation posts everything (like everything!) to server-send-event clients (on /events) and the log file. So the issue is actually in the core. It should have a filter to conserve bandwidth and disk space.
