### ISSUE TITLE
exec problem in openhab2

### ISSUE THREAD

**Issue by ich92** [openhab/openhab2-addons#1568] opened 2016-12-12 18:46 UTC
Hello,

I installed the exec 1.9.0.b4 plugin via paperui
I also installed exec transformation 0.9.0.SNAPSHOT and Regex Transformation 0.9.0.SNAPSHOT.

my default.items:
`Number TEMP_WOHNZIMMER "Temperatur Mein Zimmer [%.1f °C]" {exec="<sudo sh /etc/openhab2/scripts/dht22.sh TEMP:60000:RGEX((.*?))]"}`

I'm not getting any data no loggin in /var/log/openhab.log
In the karaf console i ran exec sudo sh /etc/openhab/scripts/dht22.sh and it worked.
In default.items I have several switches defined via the openhab1.x syntax and they work very well.

What is the problem with the item?
I don't know why there is no logging, nothing...

Hope anybody can help me.

Markus

**Comment by nighti** [comment] 2016-12-12 20:39
You posted in the openhab2-addon repo. So probably you should give the exec2.0 binding a try.  I successfully migrated the Last weekend from oh1 to oh2 , and convert my exec commands to the 2.0 binding

**Comment by ich92** [comment] 2016-12-12 20:41
Yeah, I posted in the openhab2-addon repo.
In the paperUI I can't find exec 2.0 
Where can I find it?

**Comment by nighti** [comment] 2016-12-12 20:51
Oh, it seems only be part of the oh2 snapshot. Do you use beta?

**Comment by ich92** [comment] 2016-12-12 20:54
Yeah, I use beta 
I don't Know if I should switch
Can You help me with These New things? 
How to make switches? 
How to make something like this?

Thanks a Lot
Markus

**Comment by nighti** [comment] 2016-12-12 21:10
For exec binding take a look here: https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.exec

**Comment by ich92** [comment] 2016-12-13 10:26
how to compile the .jar and where to put it in the apt-get installed oh2?

**Comment by ich92** [comment] 2016-12-13 16:57
It's now working with the exec1.9 extension.
I forgot the 2 in my path to the script ...

**Comment by ich92** [comment] 2016-12-26 13:56
I've tried exec2 now.
I'm running into some problems:

default.things:

`Thing exec:command:TEMP [command="/etc/openhab2/scripts/dht22.sh TEMP", intervavl=60, timeout=10, autorun=false]
Thing exec:command:HUM [command="/etc/openhab2/scripts/dht22.sh HUM", interval=60, timeout=10, autorun=false]`

default.items:

`Number TEMP_WOHNZIMMER "Temperatur Mein Zimmer [%.1f °C]" <temperature> (Temperatur) {channel="exec:command:TEMP:output"}
Number LUFT_WOHNZIMMER "Luftfeuchtigkeit Mein Zimmer [%.1f %%]" <humidity> (Temperatur) {channel="exec:command:HUM:output"}`

openhab.log:

`2016-12-26 14:42:50.274 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '18.00' for item 'TEMP_WOHNZIMMER' to handler for channel 'exec:command:TEMP_WOHNZIMMER:output', because no thing with the UID 'exec:command:TEMP_WOHNZIMMER' could be found.
2016-12-26 14:42:51.289 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '' for item 'LUFT_WOHNZIMMER' to handler for channel 'exec:command:LUFT_WOHNZIMMER:output', because no thing with the UID 'exec:command:LUFT_WOHNZIMMER' could be found.
2016-12-26 14:42:53.856 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '18.00' for item 'TEMP_WOHNZIMMER' to handler for channel 'exec:command:TEMP_WOHNZIMMER:output', because no thing with the UID 'exec:command:TEMP_WOHNZIMMER' could be found.
2016-12-26 14:43:54.404 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '' for item 'TEMP_WOHNZIMMER' to handler for channel 'exec:command:TEMP_WOHNZIMMER:output', because no thing with the UID 'exec:command:TEMP_WOHNZIMMER' could be found.
2016-12-26 14:43:54.529 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '53.50' for item 'LUFT_WOHNZIMMER' to handler for channel 'exec:command:LUFT_WOHNZIMMER:output', because no thing with the UID 'exec:command:LUFT_WOHNZIMMER' could be found.
2016-12-26 14:44:55.390 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '' for item 'LUFT_WOHNZIMMER' to handler for channel 'exec:command:LUFT_WOHNZIMMER:output', because no thing with the UID 'exec:command:LUFT_WOHNZIMMER' could be found.
2016-12-26 14:44:56.754 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '18.00' for item 'TEMP_WOHNZIMMER' to handler for channel 'exec:command:TEMP_WOHNZIMMER:output', because no thing with the UID 'exec:command:TEMP_WOHNZIMMER' could be found.
2016-12-26 14:45:57.315 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '' for item 'TEMP_WOHNZIMMER' to handler for channel 'exec:command:TEMP_WOHNZIMMER:output', because no thing with the UID 'exec:command:TEMP_WOHNZIMMER' could be found.
2016-12-26 14:45:59.633 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update '53.40' for item 'LUFT_WOHNZIMMER' to handler for channel 'exec:command:LUFT_WOHNZIMMER:output', because no thing with the UID 'exec:command:LUFT_WOHNZIMMER' could be found.`

Any Ideas?
My Number is not updating.
The error message is right. But I don't use the thing exec:command:LUFT_WOHNZIMMER.

**Comment by Homey-GER** [comment] 2016-12-29 14:05
I think it only works if you use STRING for the exec commands if you use the :output parameter.
I had similar errors when using NUMBER or SWITCH in the item definition.

Try it with STRING instead NUMBER one time in your items file and see if it works and errors go away. I think the exec item just works with STRING items ...

**Comment by ich92** [comment] 2016-12-31 14:09
Then it's a big step backwards to exec1 binding.
I don't unterstand why I ask for a number, I get a number and I have to say it's a string...

I want to make a request for changing this. Should I?

**Comment by ich92** [comment] 2016-12-31 14:10
It's working with a string...

**Comment by wborn** [comment] 2018-03-24 19:04
Closing this issue because it is a duplicate of https://github.com/openhab/openhab2-addons/issues/2149.

**Closed by wborn** 2018-03-24 19:04 UTC
