### ISSUE TITLE
[rfxcom] Exception when updating .things file

### ISSUE THREAD

**Issue by netjordan** [openhab/openhab2-addons#1239] opened 2016-09-17 19:47 UTC
After updating a .things file I get the following messages in the log and commands are no longer sent

```
2016-09-17 20:43:04.425 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling thing updated at ThingHandler 'org.openhab.binding.rfxcom.handler.RFXComBridgeHandler@34ef92c8: null
java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)[:1.8.0_101]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:186)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:79)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:63)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
        at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:556)[102:org.eclipse.smarthome.core.thing:0.9.0.201609151119]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:226)[102:org.eclipse.smarthome.core.thing:0.9.0.201609151119]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:149)[102:org.eclipse.smarthome.core.thing:0.9.0.201609151119]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)[102:org.eclipse.smarthome.core.thing:0.9.0.201609151119]
        at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:167)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
        at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
        at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListenersAboutUpdatedElement(AbstractProvider.java:82)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$3(GenericThingProvider.java:1)[127:org.eclipse.smarthome.model.thing:0.9.0.201609151119]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:741)[127:org.eclipse.smarthome.model.thing:0.9.0.201609151119]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$18.apply(GenericThingProvider.java:1)[127:org.eclipse.smarthome.model.thing:0.9.0.201609151119]
        at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)[140:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)[140:org.eclipse.xtext.xbase.lib:2.9.2]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.modelChanged(GenericThingProvider.java:746)[127:org.eclipse.smarthome.model.thing:0.9.0.201609151119]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:210)[116:org.eclipse.smarthome.model.core:0.9.0.201609151119]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:124)[116:org.eclipse.smarthome.model.core:0.9.0.201609151119]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:267)[116:org.eclipse.smarthome.model.core:0.9.0.201609151119]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.access$1(FolderObserver.java:261)[116:org.eclipse.smarthome.model.core:0.9.0.201609151119]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver$WatchQueueReader.processWatchEvent(FolderObserver.java:142)[116:org.eclipse.smarthome.model.core:0.9.0.201609151119]
        at org.eclipse.smarthome.core.service.AbstractWatchQueueReader.run(AbstractWatchQueueReader.java:95)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
2016-09-17 20:43:11.624 [WARN ] [g.rfxcom.handler.RFXComBridgeHandler] - No response received from transceiver
2016-09-17 20:43:11.624 [WARN ] [ome.core.thing.internal.ThingManager] - Handler for thing 'rfxcom:lighting5:usb0:000101_1' takes more than 5000ms for processing event
2016-09-17 20:43:11.625 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@71d2b8d0' takes more than 5000ms.
2016-09-17 20:43:14.067 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@71d2b8d0' takes more than 5000ms.
2016-09-17 20:43:16.627 [WARN ] [ome.core.thing.internal.ThingManager] - Handler for thing 'rfxcom:lighting5:usb0:000101_1' takes more than 5000ms for processing event
2016-09-17 20:43:16.629 [WARN ] [g.rfxcom.handler.RFXComBridgeHandler] - No response received from transceiver
2016-09-17 20:43:21.635 [WARN ] [ome.core.thing.internal.ThingManager] - Handler for thing 'rfxcom:lighting5:usb0:000002_1' takes more than 5000ms for processing event
2016-09-17 20:43:21.635 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@71d2b8d0' takes more than 5000ms.
2016-09-17 20:43:21.636 [WARN ] [g.rfxcom.handler.RFXComBridgeHandler] - No response received from transceiver
```

**Comment by lolodomo** [comment] 2016-09-19 09:01
I would not be surprised if the problem is due to the close connection that blocks, leading to a timeout in the thing manager and a serial connection that cannot be reused because not properly closed.
I will try to reproduce and analyze.

**Comment by erlendfalch** [comment] 2016-11-30 15:09
Any progress on this? If I press about 6 buttons, things start to slow down, and  I get these:
```
2016-11-30 16:08:02.666 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@6769ae' takes more than 5000ms.
2016-11-30 16:08:03.418 [WARN ] [ome.core.thing.internal.ThingManager] - Handler for thing 'rfxcom:lighting2:3a698b45:22866_2' takes more than 5000ms for processing event
2016-11-30 16:08:04.272 [WARN ] [g.rfxcom.handler.RFXComBridgeHandler] - No response received from transceiver
2016-11-30 16:08:04.293 [WARN ] [g.rfxcom.handler.RFXComBridgeHandler] - Sequence number '-1' does not match, expecting number '1'
2016-11-30 16:08:05.275 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@6769ae' takes more than 5000ms.
2016-11-30 16:08:05.275 [WARN ] [ome.core.thing.internal.ThingManager] - Handler for thing 'rfxcom:lighting2:3a698b45:22866_2' takes more than 5000ms for processing event
```

**Comment by nilzen** [comment] 2016-12-25 17:52
Same thing happens for me...

**Comment by martinvw** [comment] 2017-05-21 08:49
Can you check whether this resolved your problem?

https://github.com/openhab/openhab2-addons/issues/1611#issuecomment-300638667

**Comment by martinvw** [comment] 2017-05-30 15:59
@netjordan @erlendfalch Can you check whether the latest snapshot resolved this problems for you?

**Comment by wborn** [comment] 2018-12-20 10:45
No good news is good news. So I'll close this issue. If it doesn't work we can always reopen it. :wink:

**Closed by wborn** 2018-12-20 10:45 UTC
Labels: awaiting feedback
