### ISSUE TITLE
Support VSX-529

### ISSUE THREAD

**Issue by Sschhsd** [openhab/openhab2-addons#1531] opened 2016-12-06 16:12 UTC
Is it possible to support the pioneer VSX-529?

It is possible to control power, mute and input-source, but the control of the volume doesnt work.

For the VSX-529 the following commands (OpenHab 1) are working fine:
pioneeravr="*:livingroom:#VD"
pioneeravr="*:livingroom:#VU"

Could you please provide me the syntax for openhab2?
Could you please provide me the syntax for rule-commands for openhab2?

**Comment by Stratehm** [comment] 2016-12-06 16:23
Please see the same issue #1344: Pioneer Binding Volume set for VSX 528 like AVRs

**Comment by Sschhsd** [comment] 2016-12-06 16:28
Oh, sorry for opening a second issue.

Thank you!

**Comment by Stratehm** [comment] 2017-10-21 11:47
This issue is a duplicate of #1344. Should be closed.

**Comment by martinvw** [comment] 2017-11-10 21:56
@Stratehm thanks for mentioning

**Closed** 2017-11-10 21:55 UTC
