### ISSUE TITLE
[Homematic] HM-CC-RT-DN doesnt accept switch to auto-mode on rule

### ISSUE THREAD

**Issue by MrVorragend** [openhab/openhab2-addons#1713] opened 2017-01-16 09:34 UTC
Hello :)

i´m using the homematic binding with openhab2 and homegear. I want to migrate the following oh1-rule:
- change the modus of my heating to manu-mode (5 centigrade) after open the window
- change the modus of my heating to auto-mode after close the window

My rule works on the first change of my window state. On the second change there are no reactions. You can find the log and the rule on the bottom of my post.

After some tests I tried my script without Automode - only WZ_Heizung_Manu. This was working - the problem is only on auto-mode =|

=== rule ===
import org.openhab.core.library.types.*

rule "Fenster Wohnzimmer"
when
Item WZ_Fenster_State changed
then
logInfo("heizung-wohnzimmer", "Status verändert")
if(WZ_Fenster_State.state == OPEN) {
WZ_Heizung_Manu.sendCommand(5.0)
logInfo("heizung-wohnzimmer", "Fenster ist auf - Manu-Modus aktiviert " + WZ_Heizung_SetTemp.state)
} else {
WZ_Heizung_Auto.sendCommand(ON)
logInfo("heizung-wohnzimmer", "Fenster ist zu - Auto-Modus aktiviert")
}
end

=== First Change ===
18:52:56.479 [INFO ] [ome.event.GroupItemStateChangedEvent] - gFenster changed from CLOSED to UNDEF through WZ_Fenster_State
18:52:56.480 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Fenster_State changed from CLOSED to OPEN
18:52:57.138 [INFO ] [home.model.script.heizung-wohnzimmer] - Status ver?ndert
18:52:57.158 [INFO ] [home.model.script.heizung-wohnzimmer] - Fenster ist auf - Manu-Modus aktiviert 21.00
18:52:57.754 [INFO ] [smarthome.event.ItemCommandEvent ] - Item 'WZ_Heizung_Manu' received command 5.0
18:52:57.756 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Heizung_Manu changed from NULL to 5.0
18:52:57.758 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Heizung_RSSI changed from -36 to -37
18:52:57.761 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Heizung_Mode changed from AUTO-MODE to MANU-MODE
18:52:57.762 [INFO ] [ome.event.GroupItemStateChangedEvent] - gHeatMode changed from AUTO-MODE to UNDEF through WZ_Heizung_Mode
18:52:57.763 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Heizung_SetTemp changed from 21.00 to 5.00
18:52:57.763 [INFO ] [ome.event.GroupItemStateChangedEvent] - gHeatSet changed from 18.33 to 13.00 through WZ_Heizung_SetTemp
18:52:58.962 [INFO ] [ome.event.GroupItemStateChangedEvent] - gFenster changed from UNDEF to CLOSED through WZ_Fenster_State
18:52:58.963 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Fenster_State changed from OPEN to CLOSED
18:52:58.977 [INFO ] [home.model.script.heizung-wohnzimmer] - Status ver?ndert
18:52:58.983 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Heizung_Auto changed from NULL to ON
18:52:58.985 [INFO ] [home.model.script.heizung-wohnzimmer] - Fenster ist zu - Auto-Modus aktiviert
18:52:59.559 [INFO ] [ome.event.GroupItemStateChangedEvent] - gHeatMode changed from UNDEF to AUTO-MODE through WZ_Heizung_Mode
18:52:59.560 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Heizung_Mode changed from MANU-MODE to AUTO-MODE
18:52:59.563 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Heizung_SetTemp changed from 5.00 to 21.00
18:52:59.564 [INFO ] [ome.event.GroupItemStateChangedEvent] - gHeatSet changed from 13.00 to 18.33 through WZ_Heizung_SetTemp
18:52:59.586 [INFO ] [smarthome.event.ItemCommandEvent ] - Item 'WZ_Heizung_Auto' received command ON

=== Second Change ===
18:53:00.468 [INFO ] [ome.event.GroupItemStateChangedEvent] - gFenster changed from CLOSED to UNDEF through WZ_Fenster_State
18:53:00.469 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Fenster_State changed from CLOSED to OPEN
18:53:00.478 [INFO ] [home.model.script.heizung-wohnzimmer] - Status ver?ndert
18:53:00.484 [INFO ] [smarthome.event.ItemCommandEvent ] - Item 'WZ_Heizung_Manu' received command 5.0
18:53:00.487 [INFO ] [home.model.script.heizung-wohnzimmer] - Fenster ist auf - Manu-Modus aktiviert 21.00
18:53:01.587 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Heizung_Auto changed from ON to OFF
18:53:03.961 [INFO ] [ome.event.GroupItemStateChangedEvent] - gFenster changed from UNDEF to CLOSED through WZ_Fenster_State
18:53:03.963 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Fenster_State changed from OPEN to CLOSED
18:53:03.971 [INFO ] [home.model.script.heizung-wohnzimmer] - Status ver?ndert
18:53:03.974 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Heizung_Auto changed from OFF to ON
18:53:03.975 [INFO ] [home.model.script.heizung-wohnzimmer] - Fenster ist zu - Auto-Modus aktiviert
18:53:04.579 [INFO ] [smarthome.event.ItemCommandEvent ] - Item 'WZ_Heizung_Auto' received command ON
18:53:06.581 [INFO ] [marthome.event.ItemStateChangedEvent] - WZ_Heizung_Auto changed from ON to OFF
18:53:10.655 [INFO ] [marthome.event.ItemStateChangedEvent] - BD_Heizung_ActTemp changed from 17.70 to 17.80
18:53:10.659 [INFO ] [ome.event.GroupItemStateChangedEvent] - gHeatAct changed from 19.33 to 19.37 through BD_Heizung_ActTemp

**Comment by Andirs55** [comment] 2017-01-16 16:47
I have a similar problem but the other way around.
Switching to Auto works without a problem, but switching to Manu does not work.
In Issue [#1671](https://github.com/openhab/openhab2-addons/issues/1671) comment number 10 i shortly addressed that behaviour.

**Comment by gerrieg** [comment] 2017-01-16 17:15
This seems to be the local binding cache. Please enable forceUpdate in the Automode Channel parameters.
I think i will remove the binding cache, it causes more problems than it is useful

**Comment by Pax90** [comment] 2017-01-17 07:29
Okay. I will test it at evening. The problem is, that I want to configure all things in textfiles. Can you please implement forceUpdate on text-files?

**Comment by MrVorragend** [comment] 2017-01-17 08:34
Okay. I will test it at evening. The problem is, that I want to configure all things in textfiles. Can you please implement forceUpdate on text-files?

**Comment by MrVorragend** [comment] 2017-01-17 19:04
Hello :)
i tried to manipulate ESH-INF/config/config.xml as follow:
`	<parameter name="forceUpdate" type="boolean" required="false">
	    <label>forceUpdate</label>
	    <description>If true, the new value is always sent to the Homematic gateway even it equals the current value</description>
	    <default>true</default>
	</parameter>`

Now all works fine. Not the best solution, but a solution :)

**Comment by gerrieg** [comment] 2017-01-17 19:06
I removed forceUpdate with https://github.com/openhab/openhab2-addons/pull/1622

**Comment by MHerbst** [comment] 2017-02-18 17:47
@MrVorragend Can you retest with the latest snapshot and close the issue if it is solved.

**Comment by MHerbst** [comment] 2017-05-21 08:48
@MrVorragend Is this problem still open?

**Comment by MHerbst** [comment] 2017-06-14 18:47
No answer to my question for more than 3 weeks. @martinvw I think we can close this issue.

**Closed** 2017-06-14 21:39 UTC
Labels: homematic
