### ISSUE TITLE
openHab 2 CometVisu PHP binding not working

### ISSUE THREAD

**Issue by rene54321** [openhab/openhab2-addons#1281] opened 2016-10-01 10:36 UTC
Hi,

even if loaded over the PaperUI the cometvisu PHP is not working. See KNX forum thread:

[KNX Userforum Thread](https://knx-user-forum.de/forum/supportforen/cometvisu/954821-probleme-mit-openhab2-beta-3-und-cometvisu-0-9-2)

We tried several things. But all php related scripts like editor, icon overview or rss-log are not working. Only an blank page is shown.

regards René
##

**Comment by kaikreuzer** [comment] 2016-10-04 09:21
@peuter Could you please have a look?

**Comment by peuter** [comment] 2016-10-04 11:30
As I mentioned in the linked thread, this is nothing I am able so solve. The screenshot in the thread shows that openhab is not able to dowloed the quercus-bundle from jcenter.bintray.com. And I do not have access to the bintray-repo and also no knowledge about the whole packaging at all. 

So I suggested the reporter to open an issue here, because the problem has to be inspected by someone who has the rights and knowledge to do so.

**Comment by kaikreuzer** [comment] 2016-10-05 11:53
Ok, sorry, I didn't read all the details of the linked thread. Anyhow, the problem should better be described here on the issue itself.
The exception is only visible in a jpg that is only accessible for registered users on the external forum... I have attached it here FTR:

![image_52726](https://cloud.githubusercontent.com/assets/3244965/19112077/1b5455a6-8b03-11e6-9ddf-77fc34af64c4.jpg)

**Comment by kaikreuzer** [comment] 2016-10-05 12:10
I just tested the installation on the latest snapshot distro (offline) and from the log file, all looks good:
```
14:07:10.893 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-cometvisu' has been installed.
14:07:11.207 [INFO ] [ab.ui.cometvisu.servlet.CometVisuApp] - Started CometVisu UI at /cometvisu serving ../../../CometVisu/src/
14:07:20.234 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'ui-cometvisu-php' has been installed.
```

**Comment by kaikreuzer** [comment] 2016-10-06 07:15
"not working" means a blank page or the exception from above or both?
If it is not about the exception above, it sounds to me like a startup order issue (the binding might make the wrong assumptions) and thus I would think it is something @peuter could look into after all.

**Comment by peuter** [comment] 2016-10-06 17:39
Sorry I have absolutely no idea how to help here. I can't even get the coemtvisu itself running (getting 404 errors). Since the change to karaf and the extraction of the php-stuff from the cometvisu bundle I am totally clueless how things are working and have no idea where to even start looking for the problem.

**Comment by peuter** [comment] 2016-10-06 18:36
After a fresh install of the ide I was able to get the cometvisu running from within eclipse, but I do not see the php-bundle in there and don't know how to activate it. The Paper UI just shows nonsense binding names like: 
aZHcl Ui
ui5 - 1.0

Blbid Ui
ui6 - 1.0

so giving up here.

**Comment by kaikreuzer** [comment] 2016-10-06 20:04
I guess the best thing will be [remote debugging](https://community.openhab.org/t/debugging-openhab-2-or-how-to-view-threads/8329) on the live distro - this way it is best to track what exactly is going on.

I personally don't have the time right now to dig into this, so I hope that someone else that is familiar with debugging Java applications would lend a helping hand.

**Comment by peuter** [comment] 2016-10-07 17:53
I can't get remote debugging to work. Eclipse can not connect to the remote process, although I started openHAB in debug mode. So I tried the hard way, adding lots of debug-logging to the cometvisu bundle compile it and load the fresh compiled bundle, but I have not idea how to replace a single bundle in a local installation.

Building the offline-distro seems to download all bundles from somewhere and package them, so my local one does not get used. So I thought I just copy it to the addons-folder, but then I get errors and the new one does not get loaded. I even tried to delete every single cometvisu.jar from the runtime folder and my local .m2-folder, but still the local cometvisu.jar ind addons is not used.

So of there is any way to replace a bundle I would try to debug it the hard way, if not someone else has to jump in here.

**Comment by rene54321** [comment] 2017-01-21 13:29
Hi,

looks like the problem is still not fixed. I have the snapshot 723 of OH2. I still need to restart manually the cometvisu bundle after OH2 has started to get PHP working.

Any updates here?

best regards René

**Comment by Caprisna** [comment] 2017-01-28 22:27
Hi,

same problem here.
I use the latest OH2 2.0.0.1 stable build.
Cometvisu addon + Cometvisu PHP addon was installed successfully, but i always get a white page when i try to open Cometvisu Editor or Config Manager.

**Comment by rene54321** [comment] 2017-02-15 07:00
Hi,

any updates here. The latest stable version has exactly the same problem. I still need to restart manually the cometvisu bundle after OH2 has started to get PHP working.

**Comment by peuter** [comment] 2017-02-15 18:17
This is more an osgi problem I think. What I can say is that, when the php-bundle has been loaded the cometvisu bundle does not get notified. I added a debug message in the setPHProvider method that is defined in the osgi-XML file, but all I see is:

```
18:38:52.018 [DEBUG] [org.openhab.ui.cometvisu            ] - BundleEvent INSTALLED - org.openhab.ui.cometvisu
18:38:52.030 [DEBUG] [org.openhab.ui.cometvisu.php        ] - BundleEvent INSTALLED - org.openhab.ui.cometvisu.php
18:38:52.325 [DEBUG] [org.openhab.ui.cometvisu.php        ] - BundleEvent RESOLVED - org.openhab.ui.cometvisu.php
18:38:52.464 [DEBUG] [org.openhab.ui.cometvisu.php        ] - BundleEvent STARTING - org.openhab.ui.cometvisu.php
18:38:52.466 [DEBUG] [org.openhab.ui.cometvisu.php        ] - BundleEvent STARTED - org.openhab.ui.cometvisu.php
18:38:52.512 [DEBUG] [org.openhab.ui.cometvisu.php        ] - ServiceEvent REGISTERED - {org.openhab.ui.cometvisu.php.PHProvider}={component.name=org.openhab.ui.cometvisu.php, component.id=230, service.id=390, service.bundleid=220, service.scope=bundle} - org.openhab.ui.cometvisu.php
18:38:52.761 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed uninstalling 'openhab-ui-cometvisu': Feature named 'openhab-ui-cometvisu/0.0.0' is not installed
```

The debug message is missing, I have no clue what the error means. Maybe some osgi expert can have a look at this.

**Comment by peuter** [comment] 2017-02-17 17:40
There might be something wrong in the feature/dependecies description of the two cometvisu bundles. It would help if someone who is familiar with the topic could have a look at those descriptions, to make this line work:
https://github.com/openhab/openhab2-addons/blob/master/addons/ui/org.openhab.ui.cometvisu/OSGI-INF/cv-frontend-app.xml#L24

Maybe something has to be changed here:
https://github.com/openhab/openhab2-addons/blob/master/features/openhab-addons/src/main/feature/feature.xml#L382-L397

But I don't really know how its done right. Should be minimal effort for an expert, at least to take a look and confirm that everything is alright there and we have so search somewhere else, or fix it.

@kaikreuzer Could you take a look or assign this issue to someone who can?

**Comment by kaikreuzer** [comment] 2017-02-22 15:01
I might have an idea. If I get you right, the problem is that the setPHPProvider method is not called, if the php bundle is installed AFTER the cometvisu bundle - this is actually the standard behavior as the dependency is [declared as optional](https://github.com/openhab/openhab2-addons/blob/master/addons/ui/org.openhab.ui.cometvisu/OSGI-INF/cv-frontend-app.xml#L249), so the component is happy without it.

If you change the [schema from v1.1.0 to v1.2.0](https://github.com/openhab/openhab2-addons/blob/master/addons/ui/org.openhab.ui.cometvisu/OSGI-INF/cv-frontend-app.xml#L24), you can declare the additional property `policyOption="greedy"` in [this line](https://github.com/openhab/openhab2-addons/blob/master/addons/ui/org.openhab.ui.cometvisu/OSGI-INF/cv-frontend-app.xml#L24) - the behavior is explained [here](http://stackoverflow.com/a/30454061).

Hope this helps!

**Comment by peuter** [comment] 2017-02-22 17:24
Thanks for the hint, that helped a lot. I additionaly had to change the policy to `dynamic` to make it work, adding the `policyOption="greedy"` alone did not fix the problem.

**Comment by rene54321** [comment] 2017-02-22 18:07
Hi,

that sounds good. Thanks for the fix. Will the fix be included automatically in the next release?

cheers Rene

**Comment by peuter** [comment] 2017-02-22 18:11
When it gets merged before the next openHAB release, then yes.

**Closed** 2017-02-23 08:23 UTC
