### ISSUE TITLE
[Homekit] Some warn since OH 2.5.0 build 1602

### ISSUE THREAD

**Issue by grzegorz914** [openhab/openhab2-addons#5655] opened 2019-05-29 06:54 UTC
Hello,

after update OH 2.5.0 to build 1602, 1603 some warn appear during OH start and HomeKit accessory are not present in HomeKit app:

RPI 3 with openHABian, OH 2.5.0 build 1603.

*.items

```
Group     BiuroTemp          "Biuro temperatura"  [ "Thermostat" ]
Number    PLC_BiuroTempA      "Biuro temp. [%.1f°C]"  <temperature> (Termostaty, BiuroTemp) ["CurrentTemperature"]   { simatic="plc:DB28.DBD30:float" }
Number    PLC_BiuroTempZ     "Biuro temp. zadana [%.1f°C]"  <temperature> (Termostaty, BiuroTemp) ["homekit:TargetTemperature"]      { simatic="plc:DB6.DBD136:float" }
String    PLC_BiuroTermTryb  "Biuro tryb [%s]" <text> (Termostaty, BiuroTemp) ["homekit:TargetHeatingCoolingMode"]
String    PLC_BiuroTermTrybAktualny  "Biuro tryb aktualny [%s]" <text> (Termostaty, BiuroTemp) ["homekit:CurrentHeatingCoolingMode"]
```

Warn:
```
2019-05-29 08:08:05.006 [INFO ] [internal.service.FeaturesServiceImpl] -   org.openhab.io.homekit/2.5.0.201905290440
2019-05-29 08:08:05.153 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device PrzedpokojMalyTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.157 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device LazienkaPietroTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.161 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device PrzedpokojDuzyTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.166 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device CwuTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.172 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device BiuroTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.175 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device PokojTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.180 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device SypialniaTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.186 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device JadalniaTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.191 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device GarderobaTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.196 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device KamilaTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.202 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device LazienkaParterTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.208 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device KuchniaTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.215 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device SalonTemp: Thermostats need a CurrentTemperature accessory
```

**Comment by J-N-K** [comment] 2019-05-30 12:28
I can't reproduce that. I took exactly your items from above and got:

```
21:55:13.851 [DEBUG] [omekit.internal.HomekitChangeListener] - Adding homekit device BiuroTemp
21:55:13.856 [DEBUG] [l.accessories.HomekitAccessoryFactory] - Constructing BiuroTemp of accessoryType THERMOSTAT
21:55:33.739 [DEBUG] [l.accessories.HomekitAccessoryFactory] - BiuroTemp: isGroup? true, isMember? false
21:55:45.225 [DEBUG] [kit.internal.HomekitAccessoryRegistry] - Added accessory 1258650771
21:55:45.232 [DEBUG] [omekit.internal.HomekitChangeListener] - Added homekit device BiuroTemp
```

**Comment by grzegorz914** [comment] 2019-05-30 12:53
OK,

I have uninstalled and installed HomeKit binding again, this WARN does not appear anymore.

I have also observed, if Thermostat items are not connected to any channel (in my case with simatic) then this Thermostat accessory in HomeKit app is present but does not respond.

Thanks

**Comment by J-N-K** [comment] 2019-05-30 12:58
That is also a limitation of the way we interact with homekit. Or the way OH sees initialized items. If we do not have a valid state, we return null to the homekit-library. This is translated to „not responding“. Once there is a valid value (if set by a rule, by user interaction or a binding), they immediately change to a working state.

Since this seems to work, closing here. If something new pops up, feel free to open a new issue.

**Closed by J-N-K** 2019-05-30 12:58 UTC
Labels: io: homekit
