### ISSUE TITLE
Resolved: [squeezebox] favoritesLists from LMS not shown on basic UI but visible in android app.

### ISSUE THREAD

**Issue by fmalfatto** [openhab/openhab2-addons#4228] opened 2018-11-14 20:20 UTC
I have several airplay speakers managed from LMS. I defined them firstly in PAPER UI and they work. Now I moved to text files configuration and in Basic UI I cannot see the favoritesList fetched from the LMS. The page become gray and not list is displayed. The same configuration works from the android Openhab application

Sitemap:
...
Group item=lavanderia  {
                Default         item=Lavanderia_volume                  label="Spk lavanderia"
                Default         item=Lavanderia_control
                Selection       item=Lavanderia_PlayFavorite            label="Stazioni"
                Default         item=Lavanderia_title
                }
...

Things:
Bridge squeezebox:squeezeboxserver:PI2server [ ipAddress="192.168.1.15", webport=9000, cliport=9090 ]
{
....
        Thing squeezeboxplayer Lavanderia       "Spk lavanderia"        @ "AirPlay"     [ mac="aa:aa:eb:23:f9:70" ]
....
}

**Comment by mhilbush** [comment] 2018-11-14 20:54
Thanks for reporting this.

Can you include the item definitions for completeness?

And, can you clarify what exactly in Basic UI becomes gray?

**Comment by fmalfatto** [comment] 2018-11-14 22:29
//
Dimmer          Lavanderia_volume               "Volume"                        (Airplay, lavanderia)   {channel="squeezebox:squeezeboxplayer:PI2server:Lavanderia:volume"}
String          Lavanderia_PlayFavorite         "Stazioni preferite [%s]"       (Airplay, lavanderia)   {channel="squeezebox:squeezeboxplayer:PI2server:Lavanderia:playFavorite"}
String          Lavanderia_title                "Titolo"                        (Airplay, lavanderia)   {channel="squeezebox:squeezeboxplayer:PI2server:Lavanderia:title"}
Player          Lavanderia_control              "Control"                       (Airplay, lavanderia)   {channel="squeezebox:squeezeboxplayer:PI2server:Lavanderia:control"}

The whole page background turns from white to gray when I click on the selection triangle, instead of showing the dropbox with favorites. It happens both in Chrome and Firefox. A second click resets all to white.
This is concerned html:

<div class="mdl-form__row mdl-cell mdl-cell--6-col mdl-cell--8-col-tablet mdl-form__link ">
--
  | <span class="mdl-form__icon">
  | <img data-icon="selection" src="../icon/selection?state=NULL&format=svg" />
  | </span>
  | <span  class="mdl-form__label">
  | Stazioni
  | </span>
  | <span  class="mdl-form__value">
  |  
  | </span>
  | <div
  | class="mdl-form__control mdl-form__selection"
  | data-control-type="selection"
  | data-item="Lavanderia_PlayFavorite"
  | data-value-map="{}"
  | data-widget-id="02000402"
  | >
  | 
  | <i class="material-icons">&#xE5C5;</i>
  | <script type="text/html" class="mdl-form__selection-rows">
  | <div class="mdl-radio__group">
  |  
  | </div>
  | </script>
  | </div>
  | </div>

**Comment by mhilbush** [comment] 2018-11-14 23:34
Thanks. Very strange. Looks like the selection list is not being populated into the HTML.

And, if I understand what you said above...  With this same configuration, when loading the same sitemap into the openHAB Android app, the selection list renders correctly. Is that right?

By any chance, do you use HABpanel? If so, could you create a dashboard that contains a selection widget for your Lavanderia_PlayFavorite item? I'm curious to see what happens in HABpanel.

**Comment by mhilbush** [comment] 2018-11-15 00:03
Also, what version of openHAB are you running?

I tried to reproduce this on the latest snapshot release (build 1423), and it's working as expected.

I have this in things file
```
Bridge squeezebox:squeezeboxserver:36b70fd1 [ ipAddress="192.168.45.90", webport=9000, cliport=9090 ]
{
    Thing squeezeboxplayer b827eb163f1e  "Office Player" @ "Basement Office"  [ mac="b8:27:eb:16:3f:1e" ]
}
```
This in items file
```
String Office_PlayFavorite  "Favs Play [%s]"  { channel="squeezebox:squeezeboxplayer:36b70fd1:b827eb163f1e:playFavorite" }
```
And this in sitemap
```
    Frame label="Favorites" icon="none" {
        Selection item=Office_PlayFavorite label="Play a Favorite" icon="none"
    }
```

**Comment by fmalfatto** [comment] 2018-11-15 08:47
Our files look exactly the same. I also tried to put selection in frame in sitemap, nothing changes.
You understood perfectly my poor english, yes, the same sitemap file renders correctly in smartphone app!
The only small problem is the basic ui html not populated by favorite list.
My openhab2 pkg is this:
# dpkg --list | grep openhab
ii  openhab2                              2.3.0-1                           all          openhab2
ii  openhab2-addons                       2.3.0-1                           all          openhab2-addons

I'm new to OH2, so I still do not know how to use HABpanel. I'll try in the next days. TY for now!

**Comment by mhilbush** [comment] 2018-11-15 08:58
You also might want to consider upgrading to a more recent version of openHAB to see if the problem goes away. The 2.3 release is about 5 months old, and there have been **a lot** of changes to the core framework since then. 

Milestone release 2.4.0 M5 is pretty recent (a week ago) and stable. 
https://community.openhab.org/t/openhab-2-4-milestone-builds/50359/59

The current snapshot builds also are quite stable as well, since we're getting pretty close to a 2.4 stable release.

**Comment by mhilbush** [comment] 2018-11-15 09:03
Actually, given that 2.3 was released in May, and the [PR for the Selection widget functionality](https://github.com/eclipse/smarthome/pull/5667) was merged in June, I don't think this functionality is in 2.3.

**Comment by fmalfatto** [comment] 2018-11-15 10:42
Perfect! Upgrading to 2.4.0~M5-1 resolved the problem. I was just started with OH2 so I was thinking to stay on stable release until I had learned enough ...
You were really kind and effective. My congratulations!

**Comment by mhilbush** [comment] 2018-11-15 12:15
Thanks. Glad we got it sorted out.

Could you please close the issue?

**Closed** 2018-11-15 12:55 UTC
