### ISSUE TITLE
[imperihome] Tags error on update

### ISSUE THREAD

**Issue by ahielg** [openhab/openhab2-addons#3656] opened 2018-06-12 11:14 UTC
When I update items and save I see those error in the logs:
[WARN ] [thome.core.common.registry.AbstractManagedProvider] - Could not update element with key _tags:toiletPlug in ManagedMetadataProviderImpl, because it does not exists.

example of the item is:
Switch   toiletPlug "Toilet plug" <poweroutlet> (gWallPlug,gBathRoom)  ["iss:room:Lavatory", "iss:type:DevSwitch", "iss:link:energy:toiletPlugWatts"] { channel="zwave:device:Zwave:node18:switch_binary" }

I assume, the result of the error is that imperiHab binding not working. items not mapped to imperihome devices and no devices found in imperihome...

 
I'm working on OH2.3 release.

**Comment by wborn** [comment] 2018-06-12 12:33
This looks like a duplicate of https://github.com/eclipse/smarthome/issues/5670 which was fixed recently.  According to that issue it is a harmless warning. It should be part of the 2.4.0-SNAPSHOT builds when the next ESH stable is created.

**Comment by ahielg** [comment] 2018-06-12 12:38
In this issue it is mentioned that this log message is completely harmless. But as far as I see there is a problem with the imperiHome binding. I'm not sure it has anything to do with it, but it smells like that.

**Comment by wborn** [comment] 2018-06-12 12:51
Maybe @pdegeus knows of any issues with ImperiHome and openHAB 2.3.0?

**Comment by roswennen** [comment] 2018-09-02 05:34
@ahielg agree and it's not only the imperiHome binding, exactly same issue with Homekit binding.  I updated  (https://github.com/eclipse/smarthome/issues/5670) with logs for the Homekit issue.

**Comment by davidgraeff** [comment] 2019-03-18 08:24
Fixed in core. Please reopen if still valid.

**Closed by davidgraeff** 2019-03-18 08:24 UTC
