### ISSUE TITLE
[HABPANEL] stops work when "HTTP/1.1 503 Service Not Available"

### ISSUE THREAD

**Issue by zacofany** [openhab/openhab2-addons#2142] opened 2017-04-09 20:12 UTC
Hi,
I have Foscam cameras at home. I use happabel's IMAGE and Template widget to view MJPEG streams from these cameras.
Sometimes MJPEG stream goes down, but camera still works in h.264 stream. However if something like this happen then I get the following WARN in openhab2 log:
[WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
for example:
2017-04-09 21:55:53.902 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:55:53.926 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:55:58.643 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:55:58.679 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:03.384 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:03.416 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:08.185 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:08.211 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:12.927 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:12.957 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:17.695 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:17.733 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:22.451 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:22.479 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:27.115 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:27.155 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:31.893 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:31.930 [WARN ] [org.openhab.io.net.http.HttpUtil    ] - Method failed: HTTP/1.1 503 Service Not Available
2017-04-09 21:56:36.942 [INFO ] [eclipse.smarthome.model.script.Rules] - Converting temperatures

In such situation Habpanel stops refresh itself and says in red colour  that it's disconnected from Openhab. All goes back to normal after restarting camera. I believe it's bug.

**Comment by wborn** [comment] 2018-03-25 11:29
@ghys Do you think this is a (known) HABPanel issue? It could also be an issue in ESH.

**Comment by ghys** [comment] 2018-03-25 15:56
I remember this one: it's a duplicate of https://github.com/openhab/org.openhab.ui.habpanel/issues/168

I believe the camera was bringing the whole openHAB server down somehow. Probably not a HABPanel issue.

**Comment by kaikreuzer** [comment] 2018-03-25 17:57
I any case, the right issue tracker would be https://github.com/openhab/org.openhab.ui.habpanel/issues - so if the problem still exists, please open it there.

**Closed by kaikreuzer** 2018-03-25 17:57 UTC
