### ISSUE TITLE
[Netatmo] not updating outdoor module 

### ISSUE THREAD

**Issue by rene54321** [openhab/openhab2-addons#1499] opened 2016-11-28 12:52 UTC
Hi,

the Netatmo OH2 binding is not updating my outdoor module. I get the following errors during startup:

`2016-11-28 13:31:07.633 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property signalLevels
2016-11-28 13:31:07.634 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property signalLevels
2016-11-28 13:31:07.640 [WARN ] [.handler.AbstractNetatmoThingHandler] - Unable to load property batteryMax
2016-11-28 13:31:07.642 [WARN ] [netatmo.handler.NetatmoModuleHandler] - Battery levels were not correctly initialised - reported values will be inconsistent
2016-11-28 13:31:08.824 [WARN ] [netatmo.handler.NetatmoBridgeHandler] - An error occured while calling station API : null
2016-11-28 13:31:08.964 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null`

OH2 latest Snaphot ( From 28.11 )

Any idea what wents wrong here?

best regards René

**Comment by hakan42** [comment] 2016-11-28 12:57
I had a similiar problem when setting up my netatmo modules via a things and items files. After removing my items file, and configuring the modules via discovery (and explicitly adding channels via Paper UI), all my modules started updating again.

For the record, the full exception is:

    2016-11-26 20:46:59.356 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
    java.lang.NullPointerException
            at org.openhab.binding.netatmo.handler.station.NAModule4Handler.getNAThingProperty(NAModule4Handler.java:36)[177:org.openhab.binding.netatmo:2.0.0.201611261251]
            at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:111)[177:org.openhab.binding.netatmo:2.0.0.201611261251]
            at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:157)[177:org.openhab.binding.netatmo:2.0.0.201611261251]
            at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[177:org.openhab.binding.netatmo:2.0.0.201611261251]
            at org.openhab.binding.netatmo.handler.station.NAModule4Handler.handleCommand(NAModule4Handler.java:1)[177:org.openhab.binding.netatmo:2.0.0.201611261251]
            at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:206)[103:org.eclipse.smarthome.core.thing:0.9.0.201611241831]
            at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:126)[177:org.openhab.binding.netatmo:2.0.0.201611261251]
            at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[177:org.openhab.binding.netatmo:2.0.0.201611261251]
            at org.openhab.binding.netatmo.handler.station.NAModule4Handler.channelLinked(NAModule4Handler.java:1)[177:org.openhab.binding.netatmo:2.0.0.201611261251]
            at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:263)[103:org.eclipse.smarthome.core.thing:0.9.0.201611241831]
            at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)[103:org.eclipse.smarthome.core.thing:0.9.0.201611241831]
            at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201611241831]
            at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[96:org.eclipse.smarthome.core:0.9.0.201611241831]
            at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201611241831]
            at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201611241831]
            at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)[96:org.eclipse.smarthome.core:0.9.0.201611241831]
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
            at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]

**Comment by rene54321** [comment] 2016-11-28 13:00
Hi,

ok I try this. But I like the text based configuration. As after an complete installation it is much more easier to get all back running. So I hope it will be fixed. But thanks for the workaround I will try it.

**Comment by hakan42** [comment] 2016-11-28 13:11
I know, that's why I experimented with text-based configuration for netatmo for nearly the whole of saturday. In the end, I gave up, but will try again after understanding a bit more about the interplay between things, items and channels

**Comment by rene54321** [comment] 2016-11-28 13:41
In my case it has not helped. I have added the netatmo api over the discovery tab. Than my in and outdoor module appeared. Therse ones I have added also and linked them to an item. But it is still not updating and shows strange values which are not the current ones:

2016-11-28 14:39:21.218 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null

**Comment by rene54321** [comment] 2016-11-28 13:46
This is how it looks like in the PaperUI:

![grafik](https://cloud.githubusercontent.com/assets/15846090/20670498/633b7692-b579-11e6-8e51-4575586695b3.png)

**Comment by svenvanlierde** [comment] 2016-12-15 16:14
i have the same error, build version = 643?

**Comment by jensihnow** [comment] 2017-01-07 13:59
Any updates on this issue?

I ran into this today while migrating to OH2 (fresh install, latest beta) and for me this is a blocker before moving on.

I activated the netatmo binding and configured credentials. Modules are discovered correctly, but using their values in a item file under /etc/openhab2/items is not working. Main station works fine, but Rain Gauge and Outdoor module aren't giving any data even though they are linked e.g.

```
2017-01-07 14:50:23.640 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Rain_Batteryvp-netatmo:NAModule3:xxx:xxx:BatteryVP' has been added.
2017-01-07 14:50:23.673 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Indoor_Humidex-netatmo:NAMain:xxx:xxx:Humidex' has been added.
...
2017-01-07 14:50:23.696 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Outdoor_Batterylow-netatmo:NAModule1:xxx:xxx:LowBattery' has been added.
...
2017-01-07 14:50:23.702 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Rain_Gauge-netatmo:NAModule3:xxx:xxx:Rain' has been added.
```

Same errors as already reported:

```
2017-01-07 14:50:35.378 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-01-07 14:50:35.507 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-01-07 14:50:35.622 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-01-07 14:50:35.751 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-01-07 14:50:35.917 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-01-07 14:50:36.035 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
```

Modules are online:

```
2017-01-07 14:50:36.037 [hingStatusInfoChangedEvent] - 'netatmo:NAMain:xxx:xxx' changed from INITIALIZING to ONLINE
2017-01-07 14:50:36.073 [hingStatusInfoChangedEvent] - 'netatmo:NAModule1:xxx:xxx' changed from INITIALIZING to ONLINE
2017-01-07 14:50:36.092 [hingStatusInfoChangedEvent] - 'netatmo:NAModule3:xxx:xxx' changed from INITIALIZING to ONLINE
```

**Comment by rene54321** [comment] 2017-01-07 14:36
Hi,

Its working now. Issue can be closed sorry for the late response.

**Comment by jensihnow** [comment] 2017-01-09 18:30
I'm running on 2.0.0.b5 (/usr/share/openhab2/runtime/system/org/openhab/binding/org.openhab.binding.netatmo/2.0.0.b5/org.openhab.binding.netatmo-2.0.0.b5.jar) right now and it doesn't look fixed in this release.

Looking at the Release https://github.com/openhab/openhab2-addons/commits/55cbdb90df6374412a1e0431a5c59909a9d3b83b commits, both PRs seems to be included:

https://github.com/openhab/openhab2-addons/commit/6532717c4acd51f4f26481ee42bd844ef85d1905

https://github.com/openhab/openhab2-addons/commit/80695484e194e512a4a324536121e7738a748065

Did I missed something?

@rene54321 Which version did you tested ok on?

**Comment by jensihnow** [comment] 2017-01-18 09:27
Seems to be the same in the recently releases Release Candidate.

@kaikreuzer Not sure if this is going to be a blocking issue since it is a binding and not a core issue.
Would be nice to get it fixed before final Release of 2.0

Anything I can help with?

**Comment by kaikreuzer** [comment] 2017-01-18 12:52
> @kaikreuzer Not sure if this is going to be a blocking issue 

No, binding issues are not blocking; it will be possible to regularly provide patches for them.

**Comment by jensihnow** [comment] 2017-02-06 16:15
@clinique Do you have an idea why we still see the issue?

At some point it logs _... Successfully updated device readings! Now updating channels ..._ and starts failing on updates. Main Unit is having all values, the rain gauge and outdoor sensor is failing.

Please see latest DEBUG output (events and openhab.log in one listing):

```
2017-02-06 16:56:23.382 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Rain_Batteryvp-netatmo:NAModule3:f******2:0**********a:BatteryVP' has been added.
2017-02-06 16:56:23.420 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Indoor_Humidex-netatmo:NAMain:f******2:7**********6:Humidex' has been added.
2017-02-06 16:56:23.442 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Indoor_Humidity-netatmo:NAMain:f******2:7**********6:Humidity' has been added.
2017-02-06 16:56:23.465 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Outdoor_Batterylow-netatmo:NAModule1:f******2:0**********4:LowBattery' has been added.
2017-02-06 16:56:23.470 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Indoor_wifi-netatmo:NAMain:f******2:7**********6:WifiStatus' has been added.
2017-02-06 16:56:23.471 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Indoor_Temperature-netatmo:NAMain:f******2:7**********6:Temperature' has been added.
2017-02-06 16:56:23.473 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Rain_Gauge-netatmo:NAModule3:f******2:0**********a:Rain' has been added.
2017-02-06 16:56:23.474 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Outdoor_Humidex-netatmo:NAModule1:f******2:0**********4:Humidex' has been added.
2017-02-06 16:56:23.506 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Outdoor_Temperature-netatmo:NAModule1:f******2:0**********4:Temperature' has been added.
2017-02-06 16:56:23.509 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Outdoor_Batteryvp-netatmo:NAModule1:f******2:0**********4:BatteryVP' has been added.
2017-02-06 16:56:23.512 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Indoor_Noise-netatmo:NAMain:f******2:7**********6:Noise' has been added.
2017-02-06 16:56:23.514 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Rain_Rfstatus-netatmo:NAModule3:f******2:0**********a:RfStatus' has been added.
2017-02-06 16:56:23.517 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Outdoor_Rfstatus-netatmo:NAModule1:f******2:0**********4:RfStatus' has been added.
2017-02-06 16:56:23.536 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Indoor_CO2-netatmo:NAMain:f******2:7**********6:Co2' has been added.
2017-02-06 16:56:23.540 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Outdoor_Humidity-netatmo:NAModule1:f******2:0**********4:Humidity' has been added.
2017-02-06 16:56:23.545 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Rain_Batterylow-netatmo:NAModule3:f******2:0**********a:LowBattery' has been added.
2017-02-06 16:56:23.548 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Indoor_Heatindex-netatmo:NAMain:f******2:7**********6:HeatIndex' has been added.
2017-02-06 16:56:23.557 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Outdoor_Heatindex-netatmo:NAModule1:f******2:0**********4:HeatIndex' has been added.
2017-02-06 16:56:23.559 [ItemChannelLinkAddedEvent ] - Link 'Netatmo_Indoor_Pressure-netatmo:NAMain:f******2:7**********6:Pressure' has been added.
2017-02-06 16:56:24.493 [ThingAddedEvent           ] - Thing 'netatmo:netatmoapi:f******2' has been added.
2017-02-06 16:56:24.536 [ThingAddedEvent           ] - Thing 'netatmo:NAMain:f******2:7**********6' has been added.
2017-02-06 16:56:24.544 [ThingAddedEvent           ] - Thing 'netatmo:NAModule1:f******2:0**********4' has been added.
2017-02-06 16:56:24.557 [ThingAddedEvent           ] - Thing 'netatmo:NAModule3:f******2:0**********a' has been added.
2017-02-06 16:56:34.093 [DEBUG] [org.openhab.binding.netatmo         ] - BundleEvent STARTING - org.openhab.binding.netatmo
2017-02-06 16:56:34.107 [DEBUG] [org.openhab.binding.netatmo         ] - BundleEvent STARTED - org.openhab.binding.netatmo
2017-02-06 16:56:34.207 [DEBUG] [org.openhab.binding.netatmo         ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=325, service.bundleid=207, service.scope=singleton} - org.openhab.binding.netatmo
2017-02-06 16:56:34.248 [DEBUG] [org.openhab.binding.netatmo         ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={component.name=org.openhab.binding.netatmo.internal.NetatmoHandlerFactory, component.id=195, service.id=324, service.bundleid=207, service.scope=bundle} - org.openhab.binding.netatmo
2017-02-06 16:56:34.253 [hingStatusInfoChangedEvent] - 'netatmo:NAMain:f******2:7**********6' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2017-02-06 16:56:34.256 [hingStatusInfoChangedEvent] - 'netatmo:NAModule1:f******2:0**********4' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2017-02-06 16:56:34.258 [hingStatusInfoChangedEvent] - 'netatmo:NAModule3:f******2:0**********a' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2017-02-06 16:56:34.521 [hingStatusInfoChangedEvent] - 'netatmo:netatmoapi:f******2' changed from UNINITIALIZED to INITIALIZING
2017-02-06 16:56:34.522 [DEBUG] [netatmo.handler.NetatmoBridgeHandler] - Initializing Netatmo API bridge handler.
2017-02-06 16:56:36.533 [hingStatusInfoChangedEvent] - 'netatmo:netatmoapi:f******2' changed from INITIALIZING to ONLINE
2017-02-06 16:56:36.605 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Initializing Netatmo Device '7*:**:**:**:**:*6'
2017-02-06 16:56:36.605 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - setting device '7*:**:**:**:**:*6' online
2017-02-06 16:56:36.609 [hingStatusInfoChangedEvent] - 'netatmo:NAMain:f******2:7**********6' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
2017-02-06 16:56:36.612 [hingStatusInfoChangedEvent] - 'netatmo:NAModule3:f******2:0**********a' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
2017-02-06 16:56:36.613 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - scheduling update channel thread to run every 600000 ms
2017-02-06 16:56:36.614 [hingStatusInfoChangedEvent] - 'netatmo:NAModule3:f******2:0**********a' changed from INITIALIZING to ONLINE
2017-02-06 16:56:36.616 [hingStatusInfoChangedEvent] - 'netatmo:NAMain:f******2:7**********6' changed from INITIALIZING to ONLINE
2017-02-06 16:56:36.617 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAModule3:f******2:0**********a:Rain
2017-02-06 16:56:36.618 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAMain:f******2:7**********6:Co2
2017-02-06 16:56:36.618 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Trying to update channels on device 7*:**:**:**:**:*6
2017-02-06 16:56:36.620 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Trying to update channels on device 7*:**:**:**:**:*6
2017-02-06 16:56:36.633 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAModule3:f******2:0**********a:LowBattery
2017-02-06 16:56:36.660 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAModule3:f******2:0**********a:BatteryVP
2017-02-06 16:56:36.678 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAModule3:f******2:0**********a:RfStatus
2017-02-06 16:56:36.682 [hingStatusInfoChangedEvent] - 'netatmo:NAModule1:f******2:0**********4' changed from INITIALIZING to ONLINE
2017-02-06 16:56:36.683 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAModule1:f******2:0**********4:Temperature
2017-02-06 16:56:36.687 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAModule1:f******2:0**********4:Humidity
2017-02-06 16:56:36.691 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAModule1:f******2:0**********4:Humidex
2017-02-06 16:56:36.714 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAModule1:f******2:0**********4:HeatIndex
2017-02-06 16:56:36.736 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAModule1:f******2:0**********4:LowBattery
2017-02-06 16:56:36.796 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAModule1:f******2:0**********4:BatteryVP
2017-02-06 16:56:36.819 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAModule1:f******2:0**********4:RfStatus
2017-02-06 16:56:36.848 [hingStatusInfoChangedEvent] - 'netatmo:NAModule1:f******2:0**********4' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
2017-02-06 16:56:36.961 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Successfully updated device readings! Now updating channels
2017-02-06 16:56:37.011 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-02-06 16:56:37.023 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAMain:f******2:7**********6:Temperature
2017-02-06 16:56:37.028 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Trying to update channels on device 7*:**:**:**:**:*6
2017-02-06 16:56:37.178 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Successfully updated device readings! Now updating channels
2017-02-06 16:56:37.220 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-02-06 16:56:37.221 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAMain:f******2:7**********6:Noise
2017-02-06 16:56:37.221 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Trying to update channels on device 7*:**:**:**:**:*6
2017-02-06 16:56:37.223 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Successfully updated device readings! Now updating channels
2017-02-06 16:56:37.231 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-02-06 16:56:37.353 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Successfully updated device readings! Now updating channels
2017-02-06 16:56:37.377 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-02-06 16:56:37.384 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAMain:f******2:7**********6:Pressure
2017-02-06 16:56:37.386 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Trying to update channels on device 7*:**:**:**:**:*6
2017-02-06 16:56:37.526 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Successfully updated device readings! Now updating channels
2017-02-06 16:56:37.606 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-02-06 16:56:37.608 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAMain:f******2:7**********6:Humidity
2017-02-06 16:56:37.609 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Trying to update channels on device 7*:**:**:**:**:*6
2017-02-06 16:56:37.821 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Successfully updated device readings! Now updating channels
2017-02-06 16:56:37.867 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-02-06 16:56:37.873 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAMain:f******2:7**********6:Humidex
2017-02-06 16:56:37.878 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Trying to update channels on device 7*:**:**:**:**:*6
2017-02-06 16:56:38.009 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Successfully updated device readings! Now updating channels
2017-02-06 16:56:38.045 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-02-06 16:56:38.055 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAMain:f******2:7**********6:HeatIndex
2017-02-06 16:56:38.059 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Trying to update channels on device 7*:**:**:**:**:*6
2017-02-06 16:56:38.175 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Successfully updated device readings! Now updating channels
2017-02-06 16:56:38.226 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-02-06 16:56:38.227 [DEBUG] [.handler.AbstractNetatmoThingHandler] - Refreshing netatmo:NAMain:f******2:7**********6:WifiStatus
2017-02-06 16:56:38.228 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Trying to update channels on device 7*:**:**:**:**:*6
2017-02-06 16:56:38.365 [DEBUG] [netatmo.handler.NetatmoDeviceHandler] - Successfully updated device readings! Now updating channels
2017-02-06 16:56:38.375 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
```

Thanks a lot!

**Comment by clinique** [comment] 2017-02-06 18:25
No, I don't have such things in my logs.

**Comment by jensihnow** [comment] 2017-02-07 16:59
What can we do to get to the root of this problem?
Adding some more logging to understand what is happening?

**Comment by jensihnow** [comment] 2017-02-07 22:06
I've played a bit with the items file (removed entirely, configured an item using PaperUI), no change. I'm getting the exact same errors which means this might be unrelated to where the Items are coming from. What makes sense since they all get set correctly and are listed within the different UIs as expected. Unfortunately this isn't helping me much with the root cause of this issue. :-/

It looks like the initial issue is fixed (not getting the NPE anymore) and we have another issue causing the Binding to fail on [handler/NetatmoDeviceHandler.java#L95](https://github.com/openhab/openhab2-addons/blob/9f9df84d80e27f5402f9e7c7d1b9d16ae22c45f5/addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoDeviceHandler.java#L95) of following.

I'm currently running on:

```java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by clinique** [comment] 2017-02-07 22:21
Will try to take a look at what could cause this. Can you please control that your. Station is updated with last firmware version ?

**Comment by jensihnow** [comment] 2017-02-08 07:25
Ok, did the firmware update from 102 to 124 for the station, Outdoor module from 43 to 44 and rain sensor didn't changed (8). Restarted openhab and have the same issues as before. Was the assumtion that some fields weren't populated by the API so the binding fails on reading them?
Shall I publish one of the API outputs so you can compare with yours?

I'm going to do a fresh install on another system later today to see if this is realted to API or the stations data.

**Comment by jensihnow** [comment] 2017-02-08 10:17
Just did fresh install on a MacBook followed by Expert package selection. Afterwards installed the Binding using PaperUI and configured Netatmo API. Moved on to Discovery and added all three modules. Then I did linked the outdoor temperature as an item using PaperUI and running into the exact same issue again. Did the same with main station indoor temperature and it works just fine.

Thinking about API differences I did created a new app on dev.netatmo.com and executed re-configured the Binding from scratch like described above. Still having the exact same issue.

When I call getstationsdata the response is this: 

```
{
    "devices": [
        {
            "_id": "7*:**:**:**:**:*6",
            "cipher_id": "***",
            "co2_calibrating": false,
            "dashboard_data": {
                "AbsolutePressure": 1027.5,
                "CO2": 465,
                "Humidity": 29,
                "Noise": 34,
                "Pressure": 1029.9,
                "Temperature": 23.3,
                "date_max_temp": 1486508484,
                "date_min_temp": 1486545909,
                "max_temp": 24.2,
                "min_temp": 23.3,
                "pressure_trend": "up",
                "temp_trend": "stable",
                "time_utc": 1486548323
            },
            "data_type": [
                "Temperature",
                "CO2",
                "Humidity",
                "Noise",
                "Pressure"
            ],
            "date_setup": 1359763200,
            "firmware": 124,
            "friend_users": [
                "5***********3"
            ],
            "last_setup": 1359763200,
            "last_status_store": 1486548335,
            "last_upgrade": 1439971816,
            "module_name": "Innen",
            "modules": [
                {
                    "_id": "02:**:**:**:**:24",
                    "battery_percent": 72,
                    "battery_vp": 5319,
                    "dashboard_data": {
                        "Humidity": 90,
                        "Temperature": -0.5,
                        "date_max_temp": 1486508444,
                        "date_min_temp": 1486532620,
                        "max_temp": 0,
                        "min_temp": -0.6,
                        "temp_trend": "stable",
                        "time_utc": 1486548307
                    },
                    "data_type": [
                        "Temperature",
                        "Humidity"
                    ],
                    "firmware": 44,
                    "last_message": 1486548333,
                    "last_seen": 1486548307,
                    "last_setup": 1350298655,
                    "module_name": "Aussen",
                    "rf_status": 67,
                    "type": "NAModule1"
                },
                {
                    "_id": "05:**:**:**:**:da",
                    "battery_percent": 92,
                    "battery_vp": 5808,
                    "dashboard_data": {
                        "Rain": 0,
                        "sum_rain_1": 0,
                        "sum_rain_24": 0,
                        "time_utc": 1486548313
                    },
                    "data_type": [
                        "Rain"
                    ],
                    "firmware": 8,
                    "last_message": 1486548333,
                    "last_seen": 1486548326,
                    "last_setup": 1404233492,
                    "module_name": "Regensensor",
                    "rf_status": 80,
                    "type": "NAModule3"
                }
            ],
            "place": {
                "altitude": 20,
                "city": "Hamburg",
                "country": "DE",
                "location": [
                    **.*****,
                    **.*****
                ],
                "timezone": "Europe/Berlin"
            },
            "station_name": "*****",
            "type": "NAMain",
            "wifi_status": 50
        }
    ],
    "user": {
        "administrative": {
            "country": "DE",
            "feel_like_algo": 0,
            "lang": "de-DE",
            "reg_locale": "de-DE",
            "unit": 0,
            "windunit": 0
        },
        "mail": "*****@*****"
    }
}
```

**Comment by clinique** [comment] 2017-02-15 16:09
You're a lucky guy, now my netatmo binding also has this error :) - I'll be able to try to fix

**Comment by jensihnow** [comment] 2017-02-15 16:45
Well, more likely you are unlucky as well... at least I don't feal dumb anymore.

**Comment by jensihnow** [comment] 2017-03-02 14:03
Any updates?

**Comment by clinique** [comment] 2017-03-05 07:56
Unfortunately no, this effect disappeared by itself :( it seems to come from varying answers from Netatmo API and to say the truth, I do not have much time currently.

**Comment by njogu01** [comment] 2017-11-24 15:52
No news? I have the same problem ...

**Comment by clinique** [comment] 2017-11-24 16:46
@njogu01 : I'm finalizing the complete review of the binding (PR in code review). Hopefully, you'll not face this anymore - or at least we'll all be on the same codebase.

**Comment by zmeglic** [comment] 2017-11-28 18:14
For no reason at all, my outdoor module also stopped working

==> /var/log/openhab2/openhab.log <==
2017-11-28 19:03:30.048 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-11-28 19:03:30.051 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null
2017-11-28 19:03:30.510 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null

**Closed** 2017-12-16 19:37 UTC
