### ISSUE TITLE
[network] Arping functionality either not working or not enough documentation

### ISSUE THREAD

**Issue by claell** [openhab/openhab2-addons#2581] opened 2017-08-22 15:44 UTC
I have setup a thing for an Android device with the new network binding. Unfortunately it is still not discovered when going to sleep. I installed arping on my device (Raspberry Pi 3) and also tested it manually (it works, but has to be executed using sudo).

So either it does not work with the binding for me or I need to set up some things (tell the binding to use arping?). In that case the steps should be added to the Readme.

@davidgraeff

**Comment by davidgraeff** [comment] 2017-08-22 15:58
@claell Naturally arping needs elevated access rights. I'm using fedora and arping is a suid app here. If you use debian, you may want to make your arp suid as well (chmod u+s arping).

I'm not sure if this should go into the documentation, it depends on the distro. On linux you could also set ACLs, sudo exceptions etc pp to provide arping with proper rights.

The binding does not need any setup. If arping can be found in the PATH, it will be used.

**Comment by claell** [comment] 2017-08-22 17:32
@davidgraeff I didn't know how the binding handles arping, so I didn't know that it is a problem that arping has to be executed as sudo, thanks for the hint.

I needed to use `sudo chmod u+s /usr/sbin/arping` (took me a while to find the correct path) since `chmod u+s arping` didn't work for me.

Regarding adding some information to the Readme:

- To use the functionality, installing arping is a dependency. I think it is also relevant, how this dependency needs to be setup in order to work correctly with the binding, else I'd expect it works out of the box.

- I guess there are many users who use a Debian based Linux (as many use an RPi), so adding some more documentation might be helpful in order to get it running.

- Also note that there are probably many much less tech and Linux experienced users using OpenHAB, so I think it is a good practise in general to have a well documented Readme instead of needing to search the forum for more or less good solutions to the problem.

**Comment by claell** [comment] 2017-08-22 17:47
Unfortunately detection still does not work for me with the binding.

**Comment by davidgraeff** [comment] 2017-08-23 03:36
Google restricted background apps and the network stack more and more with Android 6, then 7, now 8. I doubt that presence detection will still work in the future because the phone is basically off when in standby. But "Unfortunately detection still does not work for me with the binding." is not helpful. Could you please elaborate?

Or if it is not a bug, close this issue and start a discussion in the community forum about effective presence detection mechanisms?

**Comment by claell** [comment] 2017-08-23 07:39
I can "ping" the device with arping, so that works. Unfortunately openHAB shows the device as offline.

**Comment by davidgraeff** [comment] 2017-08-23 08:09
Can you look up the thing in PaperUI and check the properties? Does it say, that arping is used?

**Comment by claell** [comment] 2017-08-23 08:16
You probably mean "uses_arp_pings | On"? So yes that is shown.

**Comment by claell** [comment] 2017-08-23 08:20
The property "presence_detection_type" is empty until the phone is discovered as online. Then it says
"ICMP_PING".

**Comment by davidgraeff** [comment] 2017-08-23 08:25
Can you check `arping -w 2 -c 1 -I interfaceName 192.168.1.200`?
This is the command line that the binding executes. "interfaceName" is the interface you can find with "ifconfig".

**Comment by claell** [comment] 2017-08-23 08:30
I get this (without any delay):
```
arping -w 2 -c 1 -I wlan0 192.168.1.200
ARPING 192.168.1.200
Timeout

--- 192.168.1.200 statistics ---
1 packets transmitted, 0 packets received, 100% unanswered (0 extra)
```

**Comment by claell** [comment] 2017-08-23 08:37
Same for `arping -w 5 -c 1 -I wlan0 192.168.1.200`

**Comment by claell** [comment] 2017-08-23 08:39
```
pi@raspberrypi:~ $ arping
ARPing 2.14, by Thomas Habets <thomas@habets.se>
usage: arping [ -0aAbdDeFpPqrRuUv ] [ -w <us> ] [ -W <sec> ] [ -S <host/ip> ]
              [ -T <host/ip ] [ -s <MAC> ] [ -t <MAC> ] [ -c <count> ]
              [ -C <count> ] [ -i <interface> ] <host/ip/MAC | -B>
For complete usage info, use --help or check the manpage.
pi@raspberrypi:~ $ arping -W 5 -c 1 -I wlan0 192.168.1.200
ARPING 192.168.1.200
42 bytes from f0:d7:aa:00:7e:9d (192.168.1.200): index=0 time=46.603 msec

--- 192.168.1.200 statistics ---
1 packets transmitted, 1 packets received,   0% unanswered (0 extra)
rtt min/avg/max/std-dev = 46.603/46.603/46.603/0.000 ms
```

**Comment by claell** [comment] 2017-08-23 08:40
Related to #2577?

**Comment by davidgraeff** [comment] 2017-08-23 08:43
Nope not related, the other issue is about MacOS. If have No idea what goes wrong here. The classes are all unit tested and if arping works, it should make the thing online. I need to investigate this, but don't have time rn.

_Sent from my Lge LG-F700K using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by claell** [comment] 2017-08-23 08:45
`-w` seems to be for microseconds, while `-W` has to be used for seconds!

**Comment by claell** [comment] 2017-08-23 08:48
```
-w usec
    Time to wait between pings, in microseconds.
-W sec 
    Same as -w, but in floating point seconds.
```

**Comment by davidgraeff** [comment] 2017-08-23 08:56
Oh that would explain. Unfortunately there exists two arping. I don't know if the other arping has the same command line interface.

**Comment by claell** [comment] 2017-08-23 09:37
`sudo apt-get install iputils-arping` installs a working version. Before I installed `arping`, which did not work with the binding.

Now my smartphone is detected by the binding, great!

I'd recommend to add a hint in the Readme or add support for the other (regarding to [Wikipedia](https://en.wikipedia.org/wiki/Arping) also better) arping.

**Closed** 2017-08-28 19:55 UTC

**Comment by rzwarts74** [comment] 2018-04-20 09:42
I cannot make out if arping should be working now on MacOS. But for me it isn't. And it's not detecting phones now. Should it work?

**Comment by davidgraeff** [comment] 2018-04-20 09:52
@rzwarts74 It should work. Arping need to be installed, in the PATH (executable without providing the full pathname) and executable by you / the openhab user respectively without sudo.

**Comment by rzwarts74** [comment] 2018-04-20 10:24
It works from the command line. I had to add a u+s to arping to get it
working.

But when doing a scan using the binding it reports it cannot find arping.
It's in the runtime \bin directory



Op vr 20 apr. 2018 om 11:52 schreef David Gräff <notifications@github.com>

**Comment by davidgraeff** [comment] 2018-04-20 10:42
Open a MacOS terminal and type "arping". It that works, the binding can use it. Do not move the binary to the openhab bin directory.

**Comment by rzwarts74** [comment] 2018-04-20 23:06
@davidgraeff  From a terminal it works as it's in the path. But these are the results... But it looks like it's not working:
``

presence_detection_type |  
-- | --
arp_state | THOMAS_HABERT_ARPING_WITHOUT_TIMEOUT
uses_ios_wakeup | On
icmp_state | MAC_OS_PING
uses_arp_pings | no

**Comment by rzwarts74** [comment] 2018-04-24 11:33
It works from the commandline, but it's not detecting any phones using ARP. Looks like it's not even using it... Is there a way to debug the network binding ?

**Comment by rzwarts74** [comment] 2018-04-26 08:51
@davidgraeff Opened: https://github.com/openhab/openhab2-addons/issues/3514 #3514

**Comment by potyt** [comment] 2018-07-25 20:22
My Android phone properties look like this in PaperUI:

```
uses_dhcp_listen | no
dhcp_state | Running normally
presence_detection_type | ARP_PING
arp_state | THOMAS_HABERT_ARPING_WITHOUT_TIMEOUT
uses_ios_wakeup | On
icmp_state | IPUTILS_LINUX_PING
uses_arp_pings | no
```
So apparently not using DHCP listen or ARP, what do I have to do to enable them?

Thing config:
```
Thing network:pingdevice:lg_g6 "LG G6" @ "Mobile" [
    hostname="192.168.0.103",
    uses_dhcp_listen=true,
    uses_arp_pings=true,
    refreshInterval=60000,
    timeout=5000,
    retry=5
]

```
Thing is, since I added the properties in above, it does seem to stay "online" when sleeping now, so I think it may be working, and just PaperUI is talking nonsense when reporting above.

I have setsuid arping (/usr/sbin/arping) and it works from the command line (below) and I have also put the full path in services/network.cfg
```
/usr/sbin/arping 192.168.0.103
ARPING 192.168.0.103
60 bytes from dc:0b:34:cb:33:40 (192.168.0.103): index=0 time=53.329 msec
60 bytes from dc:0b:34:cb:33:40 (192.168.0.103): index=1 time=50.813 msec
60 bytes from dc:0b:34:cb:33:40 (192.168.0.103): index=2 time=25.509 msec
...
```

So, do I need to do something else, is this a bug in PaperUI, or something else?
Ideas welcome.

**Comment by thomaswwp** [comment] 2018-11-02 08:13
I have set it up solely with paperui. The phones I am tracking are both Samsung Galaxy S7 on Android 8 (Oreo).  I am running max2play on a Raspberry Pi 3.

I installed iputils-arping and changed the permssions so anyone could execute it

`
sudo apt-get install iputils-arping
sudo chmod u+s /usr/bin/arping
`

I think it now works (12 hours later!), but like @potyt PaperUI reports that arp is not switched on.

`uses_dhcp_listen | no
-- | --
dhcp_state | No access right for port 67. Bound to port 6767 instead. Port forwarding necessary!
presence_detection_type |  
arp_state | IPUTILS_ARPING
uses_ios_wakeup | On
icmp_state | IPUTILS_LINUX_PING
uses_arp_pings | no
`
