### ISSUE TITLE
ZWave broken in for anything past snapshot 1132

### ISSUE THREAD

**Issue by bigbasec** [openhab/openhab2-addons#2958] opened 2017-12-14 16:50 UTC
Zwave no longer functions past startup.  

https://community.openhab.org/t/problems-z-wave-with-1134-snapshot/37288

https://community.openhab.org/t/oh2-2-s1133-zwave-error/37268

2017-12-14 11:43:03.359 [DEBUG] [org.openhab.binding.zwave           ] - BundleEvent STARTED - org.openhab.binding.zwave
2017-12-14 11:43:03.727 [ERROR] [ig.xml.osgi.XmlDocumentBundleTracker] - Could not send adding finished event for the module 'org.openhab.binding.zwave'!
java.lang.IllegalArgumentException: UID must have at least 2 segments.
        at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:70) [116:org.eclipse.smarthome.core.thing:0.10.0.201712141004]
        at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:48) [116:org.eclipse.smarthome.core.thing:0.10.0.201712141004]
        at org.eclipse.smarthome.core.thing.type.ChannelTypeUID.<init>(ChannelTypeUID.java:40) [116:org.eclipse.smarthome.core.thing:0.10.0.201712141004]
        at org.eclipse.smarthome.core.thing.xml.internal.ChannelXmlResult.toChannelDefinition(ChannelXmlResult.java:121) [117:org.eclipse.smarthome.core.thing.xml:0.10.0.201712141004]
        at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toChannelDefinitions(ThingTypeXmlResult.java:96) [117:org.eclipse.smarthome.core.thing.xml:0.10.0.201712141004]
        at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.getBuilder(ThingTypeXmlResult.java:148) [117:org.eclipse.smarthome.core.thing.xml:0.10.0.201712141004]
        at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toThingType(ThingTypeXmlResult.java:156) [117:org.eclipse.smarthome.core.thing.xml:0.10.0.201712141004]
        at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlProvider.addingFinished(ThingTypeXmlProvider.java:151) [117:org.eclipse.smarthome.core.thing.xml:0.10.0.201712141004]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.addingFinished(XmlDocumentBundleTracker.java:218) [108:org.eclipse.smarthome.config.xml:0.10.0.201712141004]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.parseDocuments(XmlDocumentBundleTracker.java:358) [108:org.eclipse.smarthome.config.xml:0.10.0.201712141004]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.processBundle(XmlDocumentBundleTracker.java:336) [108:org.eclipse.smarthome.config.xml:0.10.0.201712141004]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.access$3(XmlDocumentBundleTracker.java:331) [108:org.eclipse.smarthome.config.xml:0.10.0.201712141004]
        at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker$2.run(XmlDocumentBundleTracker.java:307) [108:org.eclipse.smarthome.config.xml:0.10.0.201712141004]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
2017-12-14 11:43:03.754 [DEBUG] [ing.zwave.handler.ZWaveSerialHandler] - Initializing ZWave serial controller.
2017-12-14 11:43:03.755 [DEBUG] [zwave.handler.ZWaveControllerHandler] - Initializing ZWave Controller.
2017-12-14 11:43:03.755 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.zwave.handler.ZWaveSerialHandler@1bc3ac80': null
java.lang.NullPointerException: null
        at org.openhab.binding.zwave.internal.ZWaveConfigProvider.getThingTypeConfig(ZWaveConfigProvider.java:398) [250:org.openhab.binding.zwave:2.2.0.201712141125]
        at org.openhab.binding.zwave.handler.ZWaveControllerHandler.initialize(ZWaveControllerHandler.java:95) [250:org.openhab.binding.zwave:2.2.0.201712141125]
        at org.openhab.binding.zwave.handler.ZWaveSerialHandler.initialize(ZWaveSerialHandler.java:78) [250:org.openhab.binding.zwave:2.2.0.201712141125]
        at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.201712141004]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.201712141004]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
2017-12-14 11:43:03.756 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while initializing handler of thing 'zwave:serial_zstick:886f5053': null
java.lang.NullPointerException: null
        at org.openhab.binding.zwave.internal.ZWaveConfigProvider.getThingTypeConfig(ZWaveConfigProvider.java:398) [250:org.openhab.binding.zwave:2.2.0.201712141125]
        at org.openhab.binding.zwave.handler.ZWaveControllerHandler.initialize(ZWaveControllerHandler.java:95) [250:org.openhab.binding.zwave:2.2.0.201712141125]
        at org.openhab.binding.zwave.handler.ZWaveSerialHandler.initialize(ZWaveSerialHandler.java:78) [250:org.openhab.binding.zwave:2.2.0.201712141125]
        at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.201712141004]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.201712141004]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]

## Your Environment
* Version used: OH2.2 SN1136
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Ubuntu

**Comment by kaikreuzer** [comment] 2017-12-14 16:54
Duplicate of https://github.com/openhab/org.openhab.binding.zwave/issues/767

**Closed by kaikreuzer** 2017-12-14 16:54 UTC
