### ISSUE TITLE
[opendaikin] Add OpenDaikin Binding

### ISSUE THREAD

**Issue by caffineehacker** [openhab/openhab2-addons#3039] opened 2017-12-27 20:49 UTC
There exists a binding for Daiking AC units that uses JDaikin, but that library is hosted on bitbucket and requires a few patches to build correctly. I propose making a proper OpenHAB2 binding for these units. I'm working on an implementation now (this is more of a tracking bug in case others are doing the same) using the documentation and reverse engineering found [here](https://github.com/ael-code/daikin-control/wiki/API-System).

Note that I only own the BRP controller and therefore will only be able to test using that controller. The name of the binding will be OpenDaikin to differentiate from the existing 1.x addon (feel free to suggest an alternative name).

**Comment by caffineehacker** [comment] 2017-12-28 22:11
Pull request for a new binding for this: https://github.com/openhab/openhab2-addons/pull/3044

**Comment by Boby71** [comment] 2018-03-05 20:08
@caffineehacker , thank you very much for your effort. Looking forward to test it on my two Daikin AC units

**Comment by Boby71** [comment] 2018-04-17 19:15
Hi,
since I got fed up with losing things after various updates, I tried to configure everything via things files.
It works so far, but in the logs I found the following warning:

`
2018-04-17 21:09:49.992 [hingStatusInfoChangedEvent] - 'opendaikin:ac_unit:192_168_1_61' changed from INITIALIZING to ONLINE
2018-04-17 21:09:50.398 [WARN ] [ikin.handler.OpenDaikinAcUnitHandler] - Received command of wrong type for thing 'opendaikin:ac_unit:192_168_1_61' on channel power
2018-04-17 21:09:50.464 [WARN ] [ikin.handler.OpenDaikinAcUnitHandler] - Received command of wrong type for thing 'opendaikin:ac_unit:192_168_1_61' on channel settemp
2018-04-17 21:09:50.604 [WARN ] [ikin.handler.OpenDaikinAcUnitHandler] - Received command of wrong type for thing 'opendaikin:ac_unit:192_168_1_61' on channel mode
2018-04-17 21:09:50.663 [WARN ] [ikin.handler.OpenDaikinAcUnitHandler] - Received command of wrong type for thing 'opendaikin:ac_unit:192_168_1_61' on channel fanspeed
```
Any idea what I should change to get rid of this problem?
These are my current definitions:
things:
`Thing opendaikin:ac_unit:192_168_1_61 "Daikin AC Wohnzimmer" @ "Wohnzimmer"     [ host="192.168.1.61", refresh=60000 ] 
`
items:
`Switch  DaikinWZPower        "Power"                                                 {channel="opendaikin:ac_unit:192_168_1_61:power"}
Number  DaikinWZTemp         "Zieltemperatur [%.0f °C]"        <temperature>         {channel="opendaikin:ac_unit:192_168_1_61:settemp"}
Number  DaikinWZTempIn       "Innentemperatur [%.1f °C]"       <temperature_inside>  {channel="opendaikin:ac_unit:192_168_1_61:indoortemp"}
Number  DaikinWZTempOut      "Außentemperatur [%.1f °C]"       <temperature_outside> {channel="opendaikin:ac_unit:192_168_1_61:outdoortemp"}
String  NoDaikinWZTempOut    "Außentemperatur nicht verfügbar" <temperature_outside> 
String  DaikinWZMode         "Modus"                           <ac_mode>             {channel="opendaikin:ac_unit:192_168_1_61:mode"}
String  DaikinWZFan          "Lüfter"                          <fan>                 {channel="opendaikin:ac_unit:192_168_1_61:fanspeed"}
Switch  DaikinWZPowerSiri    "Klimaanlage Wohnzimmer"          ["Switchable"]        {channel="opendaikin:ac_unit:192_168_1_61:power"}
`
Thanks'

**Comment by extric99** [comment] 2018-10-08 20:15
I have the exact same issue as mentioned above so am also interested in a solution.

**Comment by caffineehacker** [comment] 2018-10-09 03:56
Do you have your [events.log](https://www.openhab.org/docs/administration/logging.html#file-system) file handy? I'm curious what that log is saying when you get the warnings in the log that the wrong type of data is being handed to the OpenDaikin system.

**Comment by nesys** [comment] 2019-05-04 10:31
I'm trying the 2.5.0 snapshot on openhabian (last release), and I've had the same warn at the beginning. Then I've added all items like below (even if some items are not reporting anything), and now it works like a charm, warn disappeared.

> Switch DaikinACUnit_Power "Power Switch" { channel="opendaikin:ac_unit:attic_ac:power" }
Number DaikinACUnit_SetPoint "AC Setpoint [%d]" { channel="opendaikin:ac_unit:attic_ac:settemp" }
String DaikinACUnit_Mode "Daikin Mode" { channel="opendaikin:ac_unit:attic_ac:mode" }
String DaikinACUnit_Fan "Fan Speed" { channel="opendaikin:ac_unit:attic_ac:fanspeed" }
String DaikinACUnit_FanSwing "Fan Swing" { channel="opendaikin:ac_unit:attic_ac:fandir" }
Number DaikinACUnit_IndoorTemperature "Indoor Temperature [%.1f °C]" { channel="opendaikin:ac_unit:attic_ac:indoortemp" }
Number DaikinACUnit_OutdoorTemperature "Outdoor Temperature [%.1f °C]"{ channel="opendaikin:ac_unit:attic_ac:outdoortemp" }
Number DaikinACUnit_IndoorHumidity "Humidity [%d %%]" { channel="opendaikin:ac_unit:attic_ac:humidity" }

**Comment by nesys** [comment] 2019-05-10 21:41
The issue is still there. Sorry

**Comment by mtraxiot** [comment] 2019-06-09 19:14
Also getting this error for power channel

**Comment by SinFulNard** [comment] 2019-06-15 07:38
Running into the same issue with a fresh build of openhabian and the binding installed from the Eclipse IoT market. Log entries during discovery, addition and then linking with the power switch:

```
==> /var/log/openhab2/events.log <==
2019-06-15 07:33:57.793 [me.event.InboxRemovedEvent] - Discovery Result with UID 'opendaikin:ac_unit:192_168_1_107' has been removed.
2019-06-15 07:33:57.814 [hingStatusInfoChangedEvent] - 'opendaikin:ac_unit:192_168_1_107' changed from UNINITIALIZED to INITIALIZING
2019-06-15 07:33:58.944 [hingStatusInfoChangedEvent] - 'opendaikin:ac_unit:192_168_1_107' changed from INITIALIZING to ONLINE
2019-06-15 07:34:10.735 [.ItemChannelLinkAddedEvent] - Link 'DaikinACUnit1921681107_Power-opendaikin:ac_unit:192_168_1_107:power' has been added.

==> /var/log/openhab2/openhab.log <==
2019-06-15 07:34:10.727 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.OnOffType
java.lang.ClassCastException: org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.OnOffType
	at org.openhab.binding.opendaikin.internal.handler.OpenDaikinAcUnitHandler.handleCommandInternal(OpenDaikinAcUnitHandler.java:80) ~[?:?]
	at org.openhab.binding.opendaikin.internal.handler.OpenDaikinAcUnitHandler.handleCommand(OpenDaikinAcUnitHandler.java:69) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:233) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:300) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

Happy to provide logs or test a new version as needed.

After a few minutes these an event is generated - but turning "On" fails:
```
==> /var/log/openhab2/events.log <==
2019-06-15 07:34:59.209 [vent.ItemStateChangedEvent] - DaikinACUnit1921681107_Power changed from NULL to OFF
2019-06-15 07:36:10.689 [ome.event.ItemCommandEvent] - Item 'DaikinACUnit1921681107_Power' received command ON
2019-06-15 07:36:10.696 [nt.ItemStatePredictedEvent] - DaikinACUnit1921681107_Power predicted to become ON
2019-06-15 07:36:10.711 [vent.ItemStateChangedEvent] - DaikinACUnit1921681107_Power changed from OFF to ON
2019-06-15 07:36:11.064 [vent.ItemStateChangedEvent] - DaikinACUnit1921681107_Power changed from ON to OFF
```

**Comment by SinFulNard** [comment] 2019-06-16 22:39
Ah, just realised I'm running the BRP15B61 and based on comments in the pull request: https://github.com/openhab/openhab2-addons/pull/3044 - its not supported yet.

**Comment by nesys** [comment] 2019-08-12 23:04
@caffineehacker thank you very much for your effort with OpenDaikin. It's definitely appreciated.

Now the binding on OH 2.5.0 is working (build #1657 here). But during startup I see always this log:

`2019-08-13 00:56:35.233 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.StringType
java.lang.ClassCastException: org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.StringType
	at org.openhab.binding.opendaikin.internal.handler.OpenDaikinAcUnitHandler.handleCommandInternal(OpenDaikinAcUnitHandler.java:93) ~[?:?]
	at org.openhab.binding.opendaikin.internal.handler.OpenDaikinAcUnitHandler.handleCommand(OpenDaikinAcUnitHandler.java:69) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:232) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:266) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2019-08-13 00:56:35.238 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.OnOffType
java.lang.ClassCastException: org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.OnOffType
	at org.openhab.binding.opendaikin.internal.handler.OpenDaikinAcUnitHandler.handleCommandInternal(OpenDaikinAcUnitHandler.java:80) ~[?:?]
	at org.openhab.binding.opendaikin.internal.handler.OpenDaikinAcUnitHandler.handleCommand(OpenDaikinAcUnitHandler.java:69) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:232) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:266) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2019-08-13 00:56:35.235 [WARN ] [rnal.handler.OpenDaikinAcUnitHandler] - Received command of wrong type for thing 'opendaikin:ac_unit:attic_ac' on channel indoortemp
2019-08-13 00:56:35.236 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.StringType
java.lang.ClassCastException: org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.StringType
	at org.openhab.binding.opendaikin.internal.handler.OpenDaikinAcUnitHandler.handleCommandInternal(OpenDaikinAcUnitHandler.java:87) ~[?:?]
	at org.openhab.binding.opendaikin.internal.handler.OpenDaikinAcUnitHandler.handleCommand(OpenDaikinAcUnitHandler.java:69) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:232) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:266) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2019-08-13 00:56:35.230 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.StringType
java.lang.ClassCastException: org.eclipse.smarthome.core.types.RefreshType cannot be cast to org.eclipse.smarthome.core.library.types.StringType
	at org.openhab.binding.opendaikin.internal.handler.OpenDaikinAcUnitHandler.handleCommandInternal(OpenDaikinAcUnitHandler.java:87) ~[?:?]
	at org.openhab.binding.opendaikin.internal.handler.OpenDaikinAcUnitHandler.handleCommand(OpenDaikinAcUnitHandler.java:69) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:232) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:266) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
`

Any clue?
thanks
Andrea

**Comment by Hilbrand** [comment] 2019-09-20 13:27
Binding has been merged. Closing issue.

**Closed by Hilbrand** 2019-09-20 13:27 UTC
Labels: new binding
