### ISSUE TITLE
[mqtt] MQTT binding cannot be installed with snapshot #1512

### ISSUE THREAD

**Issue by JohnBeton22** [openhab/openhab2-addons#4782] opened 2019-02-02 15:37 UTC
## Current Behavior
2019-02-02 15:27:58.896 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-mqtt': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-mqtt; type=karaf.feature; version="[2.5.0.SNAPSHOT,2.5.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-mqtt)(type=karaf.feature)(version>=2.5.0.SNAPSHOT)(version<=2.5.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-mqtt/2.5.0.SNAPSHOT: missing requirement [openhab-binding-mqtt/2.5.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.binding.mqtt.generic; type=osgi.bundle; version="[2.5.0.201901280820,2.5.0.201901280820]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.binding.mqtt.generic/2.5.0.201901280820: missing requirement [org.openhab.binding.mqtt.generic/2.5.0.201901280820] osgi.wiring.package; filter:="(osgi.wiring.package=org.apache.commons.net.util)"]]

## Possible Solution
Fix the missing requirement?

## Steps to Reproduce (for Bugs)
1. Install latest snapshot
2. Install MQTT binding (v2)

## Context
I need the binding to test another binding that depends on MQTT

## Your Environment
Ubuntu server 18.04 LTS, snapshot repo, zulu-8 java
Ubuntu server 18.04 LTS, openhabian snapshot

**Comment by cweitkamp** [comment] 2019-02-08 17:31
I will quote @wborn thankfully from similar issues:

This issue should be fixed in 2.5.0-SNAPSHOT with https://github.com/openhab/openhab-core/pull/545.

The workaround in 2.4.0 is to install the **Standard** package instead of the **Simple** package during [initial setup](https://www.openhab.org/docs/tutorial/1sttimesetup.html).

Another workaround is to add the commons-net feature dependency using [The Console](https://www.openhab.org/docs/administration/console.html#the-console):

`feature:install esh.tp-commons-net`

**Closed by cweitkamp** 2019-02-08 17:31 UTC

**Comment by Grumium** [comment] 2019-02-09 15:15
@cweitkamp sorry to bother you, but it's not. Just experienced this when upgrading to the latest snapshot **1581** using the **standard** package: 
`Failed installing 'openhab-misc-mqttbroker, openhab-binding-mqtt, openhab-persistence-rrd4j, openhab-ui-basic, openhab-ui-paper': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-mqtt; type=karaf.feature; version="[2.5.0.SNAPSHOT,2.5.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-mqtt)(type=karaf.feature)(version>=2.5.0.SNAPSHOT)(version<=2.5.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-mqtt/2.5.0.SNAPSHOT: missing requirement [openhab-binding-mqtt/2.5.0.SNAPSHOT] osgi.identity; osgi.identity=openhab-core-automation-api; type=karaf.feature]`

**Comment by cweitkamp** [comment] 2019-02-09 15:31
@Grumium the error message is different (see #4841). Sry for circumstances and thank you for your patience.
