### ISSUE TITLE
OH2 - NetAtmo2.0.0 - wrong humidity

### ISSUE THREAD

**Issue by LukaNoah** [openhab/openhab2-addons#1378] opened 2016-11-02 19:14 UTC
since 18:00 h the netatmo humidity is 0,88. Before it was 88. Has netatmo changed the format of the value? 0,88 like the percentage (value * 100 = humidity)??

**Comment by michaeljoos72** [comment] 2016-11-04 18:35
Can also confirm this:

2016-11-04 19:31:23.296 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Exception while formatting value '0.88000000' of item Netatmo_Aussen_Luftfeuchtigkeit with format '%d %%': java.util.IllegalFormatConversionException: d != java.math.BigDecimal
2016-11-04 19:31:23.381 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Exception while formatting value '0.88000000' of item Netatmo_Aussen_Luftfeuchtigkeit with format '%d %%': java.util.IllegalFormatConversionException: d != java.math.BigDecimal

**Comment by LukaNoah** [comment] 2016-11-05 19:09
my workaround 

bind then item of netatmo to antother item and use a rule

rule NAT_GART_Humidity

when
	Item iPROX_GART_Humidity received update

then
	if (iPROX_GART_Humidity.state < 1){
		iNAT_GART_Humidity.postUpdate((iPROX_GART_Humidity.state as DecimalType).floatValue * 100)
		logInfo("PROX","GART " + iPROX_GART_Humidity.state + " / " + iNAT_GART_Humidity.state)
	}
	else {
		iNAT_GART_Humidity.postUpdate(iPROX_GART_Humidity.state)
		logInfo("PROX","GART Hum > 1 : " + iPROX_GART_Humidity.state)
	}

end

**Comment by lolodomo** [comment] 2016-11-06 10:31
@clinique : running your PR #1099  I don't notice this issue, my humidity values are coorect, 49% and 87%.

**Comment by lolodomo** [comment] 2016-11-12 21:55
@clinique: that is totally strange. With exactly the same Netatmo binding (same jar), humidity values were OK this morning when I was running snapshot 554. Now I moved to snapshot 583 and the problem appeared for me too !!!
```
22:47:07.051 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Exception while formatting value '0.43000000' of item HumiditeSalon with format '%d %%': java.util.IllegalFormatConversionException: d != java.math.BigDecimal
22:47:07.068 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Exception while formatting value '0.93000000' of item HumiditeExt with format '%d %%': java.util.IllegalFormatConversionException: d != java.math.BigDecimal
```

**Comment by lolodomo** [comment] 2016-11-13 10:18
Here are examples of the states that show new range value between 0 and 1:
```
2016-11-13 08:55:35.389 [ItemStateChangedEvent     ] - HumiditeSalon changed from 0.47000000 to 0.46000000
2016-11-13 11:05:35.421 [ItemStateChangedEvent     ] - HumiditeExt changed from 0.95000000 to 0.94000000
```
@clinique: any idea ?

**Comment by clinique** [comment] 2016-11-17 13:05
Hey ! I do have it now, me too !

**Comment by lolodomo** [comment] 2016-11-17 13:17
Ouf :)
Why does it happen for everybody not at the same time ?!
It occurs to me when I switched from snapshot 554 to snapshot 583 but still using the same binding jar (your updated version).
@clinique: I have still my old snapshot ready tp be started. If it can help, I can start it again to see if values are then OK again. It will just confirm that the problem is relative to a change in openHAB core and not a change in the netatmo API. Let me know if you need my help.

**Comment by clinique** [comment] 2016-11-17 13:37
@lolodomo  : because I don't think it comes from the binding, neither netatmo API but ESH.
I found that in my log : 
2016-11-17 14:29:11.663 [DEBUG] [.smarthome.core.items.ItemUtil:84   ] - Converting PercentType '62' to DecimalType '0.62000000' for item 'netatmo_in_humidity'

Now, must see what changed to introduce this behaviour.

**Comment by watou** [comment] 2016-11-17 13:45
> Now, must see what changed to introduce this behaviour.

Two candidates:

* https://github.com/eclipse/smarthome/pull/2334
* https://github.com/eclipse/smarthome/pull/2393

**Comment by lolodomo** [comment] 2016-11-17 16:07
@clinique: that is probably because you are using a PercentType rather than a DecimalType ?

**Comment by clinique** [comment] 2016-11-17 16:08
@lolodomo : yes !
I just pushed an update of the PR that correct this issue

**Comment by lolodomo** [comment] 2016-11-17 16:11
Ok thank you, I will test your last version later today.

**Comment by clinique** [comment] 2016-11-17 16:21
@lolodomo : I still have got an issue without clear solution now. This applies to the thermostat : 
When you update a value from a sitemap (let say changing the mode from "program" to "away", the modification has impacts on many channels (=> setpoint changes) and this is not immedially reflected until the device gets updated upon some minutes. I tried forcing a refresh of the device, but still get the old values. Maybe you'll have an idea (located in NATherm1Handler.handleCommand)

**Comment by LukaNoah** [comment] 2016-11-18 07:06
Hi,
with the latest OH2 snapshoot the binding doesn't work. The modules are all "uninitialized" (handler error). The API is "online". 

Where can I get the latest snapshoot of this binding? How can I include this to OH2?

**Comment by lolodomo** [comment] 2016-11-18 08:23
Unfortunately the PR fixing all problems for this binding in current snapshot is not yet merged. We are waiting for the merge.
Currently it is required to compile clinique's PR yourself to produce the expected jar.
We will provide a download link to a working version of the binding in case the PR is not merged soon.

**Comment by kaikreuzer** [comment] 2016-11-18 10:13
> We are waiting for the merge.

@lolodomo Are you referring to https://github.com/openhab/openhab2-addons/pull/1099?
This still seems to be under active discussion/development, so I didn't yet consider it as a candidate for merging. Is this a false impression?

**Comment by lolodomo** [comment] 2016-11-18 10:32
@kaikreuzer : yes I am talking about the PR #1099. I let @clinique tell you the exact status but for me this PR is now no more in active discussion/development, there was only recent changes required by recent changes in ESH (thing life cycle, conversion of types, ...).

**Comment by LukaNoah** [comment] 2016-11-19 12:07
Many thanks for your work.
Now it works perfectly.

**Comment by lolodomo** [comment] 2016-11-19 12:11
@LukaNoah : please close the issue.

**Comment by LukaNoah** [comment] 2016-11-19 12:16
How? I can't find nothing to do this.

**Comment by lolodomo** [comment] 2016-11-19 12:19
As initiator of the issue, you should have a button "Comment" and a button "Close and comment" (something like that).

**Comment by michaeljoos72** [comment] 2016-11-19 12:32
Humidity works now! Thanks for the fix.
What does not work anymore for me is air quality for additional modules. Main Module looks good.

**Comment by LukaNoah** [comment] 2016-11-19 13:07
Humidity

**Closed** 2016-11-19 13:08 UTC
