### ISSUE TITLE
[Network binding] servicePing is true on ConnectException 

### ISSUE THREAD

**Issue by ZhukovAN** [openhab/openhab2-addons#3554] opened 2018-05-09 06:27 UTC
## Expected Behavior
NetworkUtils.servicePing(host, port, timeout) on non-existing port returns true. Author says "Connection refused, there is a device on the other end though" and that's true, but device isn't listening on the required port, so servicePing should return false

## Current Behavior
Network binding discovery outputs a lot of tcp:80/554/1025 listening devices where IP exists, but there's no TCP service listening at the dedicated portthere's no

## Possible Solution
Replace "return true;" with "return false;" in case of ConnectException in NetworkUtils.servicePing

## Steps to Reproduce (for Bugs)
Install Network Binding addon, go to Inbox, choose Network Binding and see how non-existing 80/554/etc are appearing

## Your Environment
OpenHab addon pack 2.2.0
[events.log](https://github.com/openhab/openhab2-addons/files/1986616/events.log)
[ip-and-services.txt](https://github.com/openhab/openhab2-addons/files/1986617/ip-and-services.txt)

**Comment by martinvw** [comment] 2018-05-25 09:18
Can you agree that this is a duplicate of #3499, in that case it is fixed with https://github.com/openhab/openhab2-addons/pull/3501

**Closed by martinvw** 2018-05-25 09:18 UTC
