### ISSUE TITLE
setpoint in basicui broken

### ISSUE THREAD

**Issue by SuperOok** [openhab/openhab2-addons#548] opened 2015-12-13 22:00 UTC
I use 'setpoint' in my sitemap like this

```
Text label="Sollwerte" icon="temperature" {
			Frame label="Soll-Temperaturen" {
				Setpoint item=Sollwert_Wohnen minValue=15 maxValue=30 step=1
				Setpoint item=Sollwert_Diele minValue=15 maxValue=30 step=1
				Setpoint item=Sollwert_HWR minValue=15 maxValue=30 step=1
				Setpoint item=Sollwert_WC minValue=15 maxValue=30 step=1
				Setpoint item=Sollwert_Gast minValue=15 maxValue=30 step=1
				Setpoint item=Sollwert_Ankleide minValue=15 maxValue=30 step=1
				Setpoint item=Sollwert_Schlafen minValue=15 maxValue=30 step=1
				Setpoint item=Sollwert_Arbeiten minValue=15 maxValue=30 step=1
				Setpoint item=Sollwert_Zimmer1 minValue=15 maxValue=30 step=1
				Setpoint item=Sollwert_Zimmer2 minValue=15 maxValue=30 step=1
				Setpoint item=Sollwert_Bad minValue=15 maxValue=30 step=1
			}
		}
```

Label, current value and change buttons show up nicely in the classicui, but not in the basicui:

![img_1057](https://cloud.githubusercontent.com/assets/10581272/11769677/3bc8c3b2-a1ed-11e5-9456-ebdebff9bcf9.PNG)
![img_1056](https://cloud.githubusercontent.com/assets/10581272/11769679/41f51d76-a1ed-11e5-876e-382e4a3bee5a.PNG)

**Comment by kaikreuzer** [comment] 2015-12-14 12:49
This looks weird. Can you reproduce this with the demo sitemap, which has such a widget as well (https://github.com/openhab/openhab2/blob/master/distribution/openhabhome/conf/sitemaps/demo.sitemap#L41)? This renders all ok for me:
<img width="1080" alt="bildschirmfoto 2015-12-14 um 13 48 39" src="https://cloud.githubusercontent.com/assets/3244965/11781343/74815846-a269-11e5-8a86-722a2add80b4.png">

**Comment by SuperOok** [comment] 2015-12-14 18:55
Well, in the basicui I don't have any Demo Frame, while it is ok in the classicui

![demo_frame](https://cloud.githubusercontent.com/assets/10581272/11790419/feaf2b24-a29b-11e5-9bcd-89f00a848492.PNG)

I checked the demo.sitemap and it's ok; just the original you referenced.
I also cannot address the frame directly. Opening http://url/basicui/app?w=0202 gives 

```
HTTP ERROR 500

Problem accessing /basicui/app. Reason:

    Server Error

Caused by:

org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=2, size=1
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)
	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getWidget(ItemUIRegistryImpl.java:475)
	at org.eclipse.smarthome.ui.basic.internal.servlet.WebAppServlet.service(WebAppServlet.java:144)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:744)
```

I'm running, again on my Raspi2. Looks like I have not much luck in running openhab2...
Nothing special in the openhab.log. Any further logs I could enable?

**Comment by kaikreuzer** [comment] 2015-12-14 18:58
Sorry, I should have posted you the url to the demo sitemap for the Basic UI - try http://localhost:8080/basicui/app?sitemap=demo

**Comment by SuperOok** [comment] 2015-12-14 19:08
Ah, ok, that looks fine, I just tried Build 441

![demo_frame2](https://cloud.githubusercontent.com/assets/10581272/11790876/64287b52-a29e-11e5-9533-b3c1268588f3.PNG)

**Comment by kaikreuzer** [comment] 2015-12-14 19:08
So what is the difference to your sitemap then? Is that still broken?

**Comment by SuperOok** [comment] 2015-12-14 19:12
I retried the build from yesterday with the demo. It looks ok but I get this exception in the log
```
2015-12-14 20:10:03.672 [ERROR] [.m.r.r.i.engine.ExecuteRuleJob] - Error during the execution of rule Set random room temperatures
java.lang.RuntimeException: The name 'Temperature' cannot be resolved to an item or type.
        at org.eclipse.smarthome.model.script.interpreter.ScriptInterpreter.invokeFeature(ScriptInterpreter.java:110) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:900) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:863) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:222) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:202) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:758) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:218) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:202) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:758) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:218) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:202) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:445) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:226) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:202) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluate(XbaseInterpreter.java:188) ~[na:na]
        at org.eclipse.smarthome.model.script.runtime.internal.engine.ScriptImpl.execute(ScriptImpl.java:77) ~[na:na]
        at org.eclipse.smarthome.model.rule.runtime.internal.engine.ExecuteRuleJob.execute(ExecuteRuleJob.java:60) ~[na:na]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.1.jar:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.1.jar:na]
```
I'll now try my own sitemap

**Comment by SuperOok** [comment] 2015-12-14 19:38
I was almost thinking that I get crazy because I could not reproduce it. But now I know the problem: I should not repeat a test with different environment: On a desktop browser (firefox on windows 8.1) the setpoint buttons look ok. But on my iPhone 6 with Safari Browser, also the demo of Build 441 has broken button Icons:

![img_1058](https://cloud.githubusercontent.com/assets/10581272/11791499/b21973ea-a2a1-11e5-814a-3df6fa2e255f.PNG)

So it's an issue with rendering the icons on Safari in iOS.

The html source looks like this 
```
<button class="mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect mdl-form__setpoint--up">
			<!-- keyboard_arrow_up -->
			<i class="material-icons">&#xE316;</i>
		</button>
		<button class="mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect mdl-form__setpoint--down">
			<!-- keyboard_arrow_down -->
			<i class="material-icons">&#xE313;</i>
		</button>
```
So there is a problem with the material icon on iOS

**Comment by SuperOok** [comment] 2015-12-14 19:47
So the Icons seem to be pretty browser specific. It's ok on my firefox and chrome on Windows 8.1, has single faulty Icons on iOS and on IE11 the styling is totally messed up
![demo_frame_ie11](https://cloud.githubusercontent.com/assets/10581272/11791917/cf187ebc-a2a3-11e5-97a5-2e54af7ebc9f.PNG)

**Comment by resetnow** [comment] 2015-12-15 07:45
Icons are browser specific but they don't work because they didn't pass IP clearance (CQ 10013) yet. Therefore they weren't merged. Maybe as a temporary solution we should use files hosted on Google CDN.

As for labels, yes it's a bug and I'll fix it this weekend.

**Comment by resetnow** [comment] 2015-12-15 07:47
@SuperOok that IE11 layout looks strange, do you have compatibility mode turned on by chance? I'll check it too, but last time it worked in IE10 and IE11 with some minor bugs/limitations.

**Comment by kaikreuzer** [comment] 2015-12-15 07:48
> Icons are browser specific but they don't work because they didn't pass IP clearance (CQ 10013) yet. Therefore they weren't merged.

It is right that they were not merged in ESH, but that's why I created a fragment in OH2, which contains them, see https://github.com/openhab/openhab2/tree/master/addons/ui/org.openhab.ui.basicui/patch/web/fonts.

So all icons should be available.

**Comment by resetnow** [comment] 2015-12-15 09:13
Oh, I missed that. It just looks like material icons font is not loaded and iOS threats these symbols as emojis. @SuperOok could you please check availability of font files?

**Comment by kaikreuzer** [comment] 2015-12-15 11:06
@resetnow I have checked, the files are correctly served by the HTTP server. I can e.g. access
http://localhost:8080/basicui/material-icons.css
http://localhost:8080/basicui/fonts/MaterialIcons-Regular.eot
http://localhost:8080/basicui/fonts/MaterialIcons-Regular.ttf
http://localhost:8080/basicui/fonts/MaterialIcons-Regular.ttf
http://localhost:8080/basicui/fonts/MaterialIcons-Regular.woff
http://localhost:8080/basicui/fonts/MaterialIcons-Regular.woff2

What files are required by Safari?

**Comment by SuperOok** [comment] 2015-12-26 19:05
For IE11 the problem is the compatibility mode. It gets activated by default for "intranet sites", which might be often true for openhab servers. I configured by IE11 in the security settings and now it works fine as expected.
To give a better out-of-the-box-experience, you could add the meta-tag for forcing to not use IE7 compatibility mode: 
http://stackoverflow.com/questions/25557299/internet-explorer-11-disable-display-intranet-sites-in-compatibility-view-via

**Comment by kaikreuzer** [comment] 2015-12-26 21:09
@resetnow Could you create a PR with that meta-tag?
Did you already check for the missing icons/fonts?

**Comment by resetnow** [comment] 2015-12-26 21:15
@kaikreuzer I wish I could, I'm still struggling with wetting the whole environment up, sorry. Cleaning maven cache seems to have helped with compilation, but now I can't view any sitemap from Classic/BasicUI with the default configuration.

**Comment by kaikreuzer** [comment] 2015-12-26 21:17
Hm, I thought you have the openHAB 2 IDE setup successfully? What has changed about that?

**Comment by resetnow** [comment] 2015-12-26 21:39
I haven't updated my forks in a while — maybe that's the reason. Also, I'm trying to use ESH only, will try with OH2, thank you,

**Comment by SuperOok** [comment] 2015-12-26 23:21
![openhab-icons](https://cloud.githubusercontent.com/assets/10581272/12008258/885827f8-ac2f-11e5-9f9a-d9aa3c6a8617.png)

So here's the overview for build 450: Besides https://github.com/eclipse/smarthome/issues/738 the Firefox and Chrome show correct icons. iOS shows wrong icons and IE11 shows no icons for this control (and back button). IE11 icons for most other controls are there.

**Comment by resetnow** [comment] 2015-12-27 10:32
@SuperOok thanks for testing.

As it turns out, some font files taken from PaperUI use different character codes for icons (probably different font version). It should work now (PR: eclipse/smarthome#785).

![2015-12-27 13-24-30 screenshot](https://cloud.githubusercontent.com/assets/2057191/12009892/1f947c3e-ac9e-11e5-90b6-328305a5f6c0.jpg)

**Comment by resetnow** [comment] 2015-12-27 12:08
@kaikreuzer quick question: should REST API work out-of-the-box when using openHAB_with_ESH configuration? I'm getting `HTTP/1.1 503 Jersey is not ready yet!` for every REST request. `com.eclipsesource.jaxrs.jersey-all` and `com.eclipsesource.jaxrs.jersey-min` are enable in the run configuration.

**Comment by kaikreuzer** [comment] 2015-12-27 13:26
Yes, it should work. Try the launch config from the repo (revert all your local changes).  jersey-all is not part there, only jersey-min. Also check the other jaxrs bundles:

<img width="574" alt="bildschirmfoto 2015-12-27 um 14 24 59" src="https://cloud.githubusercontent.com/assets/3244965/12010407/c6396444-aca5-11e5-9246-1d9de9046a8e.png">

**Comment by resetnow** [comment] 2015-12-27 22:05
That's strange, I have these bundles enabled.

For the record, the default configuration does not work at all for me, showing the following window:

![screenshot from 2015-12-28 00-59-01](https://cloud.githubusercontent.com/assets/2057191/12012282/a8a2dfe2-acfe-11e5-806b-0224637f372c.png)

After I press «Add required plug-ins» button OH2 starts and web interfaces work, but the REST API doesn't.

OH2 repo status:
```
vlad@vlad-aspire-v3:/opt/oh2$ git status targetplatform/openHAB_with_ESH.launch
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
vlad@vlad-aspire-v3:/opt/oh2$ git log -n1
commit fe709a7341947ed131d75ea8bc4f085db7ea6dbd
Merge: bd44deb 2c8d12d
Author: Kai Kreuzer <kai@openhab.org>
Date:   Wed Dec 23 23:12:14 2015 +0100

    Merge pull request #574 from DanNixon/mqtt_compat
    
    Document v1.x MQTT binding compatability
```

**Comment by kaikreuzer** [comment] 2015-12-27 22:42
> After I press «Add required plug-ins» button

FTR: Never ever press this button, it is EVIL!

I'd suggest that you go with the normal "non-esh" launch configuration and simply add the basicui bundle from your workspace (and deselect the one from the targetplatform). This should be all you need.

**Comment by paddsen** [comment] 2015-12-30 10:41
The fixed version does not work for me at the moment. The org.eclipse.smarthome.ui.basic....jar contains the correct snippets, but I think the wrong version is referenced by the artifacts.xml. After fixing this, my version works perfectly in IE11 and Edge and my simple WebView UWP app (using basicui).

**Comment by kaikreuzer** [comment] 2015-12-30 21:31
> but I think the wrong version is referenced by the artifacts.xml

Which artifacts.xml do you mean?

**Comment by kaikreuzer** [comment] 2016-01-14 20:57
Assuming this is fixed.

**Closed by kaikreuzer** 2016-01-14 20:57 UTC

**Comment by SuperOok** [comment] 2016-01-18 20:19
yes, looks very well now! 👍
