### ISSUE TITLE
WeMo Devices Changing Ports

### ISSUE THREAD

**Issue by jaywiseman1971** [openhab/openhab2-addons#5487] opened 2019-04-19 16:20 UTC
<a alt="bounty" href="https://www.bountysource.com/issues/73078259"><img src="https://api.bountysource.com/badge/issue?issue_id=73078259"></a>

I've been running 15 WeMo devices for 10 months now with OH2.3, 2.4 and 2.5m1 and the same situation continues to happen with port changing.

WeMo plugs seem to have the biggest issue with port changes over a time period which causes OH not to update thing with the new port number that the WeMo device changed to which intern means the rule doesn't work any longer.

The gentlemen (https://community.openhab.org/t/openhab-2-3-not-working-with-wemo/47755/22) that wrote the WeMo binding hasn't had time to resolve this issue so I'm putting a bounty on it to get it resolved ASAP.

Here's a blurb from another post with Home Assistant having the same issue with WeMo's.

"The best way to approach this is that when we get a connection refused error, we search the network again with SSDP, but this time use the device specific udn switch._config.get_UDN() (example value: uuid:Insight-1_0-221346K1200409). Once we found the new location, we update the object to point at the new host/port and all should be well."

Best, Jay

**Comment by wborn** [comment] 2019-04-19 16:29
Thanks for adding the bounty!

**Comment by kaikreuzer** [comment] 2019-05-02 15:37
@jaywiseman1971 Can you provide a description here on the issue on how to reproduce the issue and what is found in the (debug) logs when it happens? How often do the devices change their port, how regularly does that happen and what devices apart from plugs are affected?

**Comment by draythomp** [comment] 2019-05-04 16:19
I've been fighting this problem since the first light switches came on the market. I do not use OH, I run entirely my own home grown software.

The way I solved it is to poll each device to make sure it is still responding and when one drops out, find it again and get the new port number. I keep a simple list of the devices and just keep it updated in software with whatever the port number happens to be. 

To answer the question above, I haven't seen any particular rhythm to them changing ports. I'm actually thinking that some random bug causes the device to reset and it comes back with a different port. No proof of that though. All I see the the conversations with the devices is that they just go away and can be found on a different port.

I don't know if it happens on other devices. I have the wall switches and stopped there because of several other problems with them and unreliable internet in my area.

**Comment by jaywiseman1971** [comment] 2019-05-04 17:13
Hi Kai,

I did turn on the debug logs and got a ton entries from all the 15 devices (3 different types); when it happens OH thinks it turns it ON or OFF because the item gets updated to the correct action.  This alone means the binding is not reporting if the action actually happened or not back to OH correctly.

What I did to prove the ports are changing is a ping using the paping tool on the port numbers when it happens.

paping 192.168.0.153 -p **49153** -c 4   <-- is the original boot port of WeMo's
paping 192.168.0.153 -p **49154** -c 4  <-- it will start to climbing ports (no triggered reason why, it could be hours or days before it happens on certain devices.)
paping 192.168.0.153 -p **49155** -c 4  <-- climbed again after some times goes by

@draythomp (above reply) is stating it's happening to him on his wall switches.  My wall switches are fine but my plugs are not.  I have around 12 plugs and 5 of them move ports over time.  This is NOT a hard/fast rule on every WeMo; it's just a few of them.

I have insured all the WeMo devices are at the latest firmware and that has not helped.

The original OH owner of the binding has been using his WeMo Insight switch and it has NOT happened to him on that device.  I have 2 Insight switches also and there has been no issues on those units for us two but that doesn't mean there isn't some other batch out there that doesn't have the same issues.

I'm willing to buy a WeMo plug for anybody in the US that wants to address this situation.  I've also written the Home Assistant founders (Paul S.) since they have addressed it already in 2015 and I've offer them to help OH's WeMo binding.  

Best, Jay

**Comment by jaywiseman1971** [comment] 2019-05-21 19:33
[quote="jwiseman, post:1, topic:74453"]
move up on port numbers over a time
[/quote]

Here's the port numbers they move across.

https://www.simplecontrol.com/check-compatibility/

**Belkin** 
Wemo Mini Smart Plug , WeMo Switch, WeMo Insight Switch	
AutoDiscovery (Ports 49151 - 49153)

Best, Jay

**Comment by wborn** [comment] 2019-05-25 07:09
Maybe @hmerk can help with fixing this?

**Comment by hmerk** [comment] 2019-06-24 20:48
Please see my community post
https://community.openhab.org/t/wemo-reliability/37244/33

**Comment by hmerk** [comment] 2019-08-07 20:33
I removed the bug label, cause it is not a bug in the Binding, it is a device issue where we need a workaround. First try was not successfull😒

**Comment by hmerk** [comment] 2019-09-09 08:01
Update: New testing version published in the community.

**Comment by hmerk** [comment] 2019-10-20 11:44
PR #6253 created, test with @jaywiseman1971 had been successfull so far.

**Comment by hmerk** [comment] 2019-10-20 14:14
Merged into master

**Closed** 2019-10-20 14:13 UTC
Labels: bounty
