### ISSUE TITLE
Log is useless

### ISSUE THREAD

**Issue by kvoit** [openhab/openhab2-addons#1951] opened 2017-02-24 19:54 UTC
After this [thread in the forum](https://community.openhab.org/t/any-way-on-which-writing-rules-is-not-a-huge-pita/21996) has been sitting there unanswered for 3 weeks, I'll dare a bug report. Note that by now I found and fixed the issues in that code, but it was certainly not thanks to any helpful hints from the server software.

To name the issue here again:
In my experience, the log of openHAB is absolute useless. The pinnacle of uselessness was the message

> 08:30:53.948 [ERROR] [.script.engine.ScriptExecutionThread] - Rule 'LE_FirstFloor_Bedroom_AlertMinute_Rule': org.eclipse.smarthome.core.library.types.DecimalType

but useless or non-existing log messages about issues are the rule as far as I can tell. With default settings, I wasn't even notified that i forgot an "item=" in a sitemap script. The sitemap just silently wasn't displayed correctly.

It is nice that you guys want to make everything configurable via web interface and that shiny Eclipse thing. It is important for beginners and casual users to have such a possibility. However, it is a very well established method of system administration to write to text files and check logs for issues. I'll go as far as saying it is the most, possibly the only viable way to use the full potential of such a mighty platform as openHAB. I really like those possibilities, but each time I set up some new stuff, I do it with the really bad feeling that I might break stuff because I introduce some small mistake that is terribly hard to find.

So please, add usable error messages to the log. At least give a line where something seems to be wrong. Even C compilers mostly manage that, and those errors are already pretty useless, pretty often.

Excuse me if this rather belongs to the Eclipse SmartHome site, I can't just due to my lack of knowledge of the architecture.

**Comment by kaikreuzer** [comment] 2017-02-26 04:12
Thanks for your report.
Please note that there is no "one log" - in every single line of code it has to be decided, what can/should/is logged, so you have to look at each individual case and suggest what should be improved.
Wrt to broken config files, I'd consider this to be a duplicate of https://github.com/eclipse/smarthome/issues/2870.

**Closed by kaikreuzer** 2017-02-26 04:12 UTC

**Comment by kvoit** [comment] 2017-02-26 10:58
Well, there is something like "one log". The log I get when I open the console and type log:tail. And my repeated experience is that this log is not populated with a lot of useful info - i.e. it is not a helpful point to come to find issues in the config.
The referenced issue is certainly part of the problem, but I rather wonder if the log is taken seriously by the devs at all - and if not, I wonder what is suggested for development of more complex rules. 
It feels like people rely too much on the smarthomeDesigner, maybe.

**Comment by kvoit** [comment] 2017-02-26 11:06
Next one just now:

```
12:03:27.602 [ERROR] [.core.internal.folder.FolderObserver] - Error handling update of file '/etc/openhab2/persistence/mysql.persist': null.
java.lang.NullPointerException
        at org.eclipse.smarthome.core.scheduler.ExpressionThreadPoolManager$ExpressionThreadPoolExecutor.removeFutures(ExpressionThreadPoolManager.java:321)[98:org.eclipse.smarthome.core:0.9.0.b4]
        at org.eclipse.smarthome.core.scheduler.ExpressionThreadPoolManager$ExpressionThreadPoolExecutor.remove(ExpressionThreadPoolManager.java:291)[98:org.eclipse.smarthome.core:0.9.0.b4]
        at org.eclipse.smarthome.core.scheduler.ExpressionThreadPoolManager$ExpressionThreadPoolExecutor.remove(ExpressionThreadPoolManager.java:308)[98:org.eclipse.smarthome.core:0.9.0.b4]
        at org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl.removeTimers(PersistenceManagerImpl.java:321)[103:org.eclipse.smarthome.core.persistence:0.9.0.b4]
        at org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl.stopEventHandling(PersistenceManagerImpl.java:377)[103:org.eclipse.smarthome.core.persistence:0.9.0.b4]
        at org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl.removeConfig(PersistenceManagerImpl.java:348)[103:org.eclipse.smarthome.core.persistence:0.9.0.b4]
        at org.eclipse.smarthome.model.persistence.internal.PersistenceModelManager.modelChanged(PersistenceModelManager.java:85)[125:org.eclipse.smarthome.model.persistence:0.9.0.b4]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:207)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:120)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:272)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.access$1(FolderObserver.java:265)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver$WatchQueueReader.processWatchEvent(FolderObserver.java:146)[122:org.eclipse.smarthome.model.core:0.9.0.b4]
        at org.eclipse.smarthome.core.service.AbstractWatchQueueReader.run(AbstractWatchQueueReader.java:122)[98:org.eclipse.smarthome.core:0.9.0.b4]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
```

I mean ... c'mon ...

**Comment by MHerbst** [comment] 2017-02-26 11:21
If you want to see more log output you can simply change the log level. For most components you will get very detailed log output if you change the log level to TRACE or even DEBUG.

**Comment by kvoit** [comment] 2017-02-26 11:47
I tried that once an estimated million lines of unimportant stuff where thrown at me. It's a parse error in a config file. It belongs in almost all log levels.

Just encountered another two:
- A group did not exist but was used for an item. Not a single fuck in the config file.
- Trying to display temperature and humidity in one chart according to https://github.com/openhab/openhab1-addons/wiki/Charts. Charts for single items work, group chart is empty. Nothing in the log file.
