### ISSUE TITLE
[bosesoundtouch] null pointer exception 

### ISSUE THREAD

**Issue by Markinus** [openhab/openhab2-addons#3643] opened 2018-06-10 09:02 UTC
## Expected Behavior

The channel "now playing" is linked and should show the corrent info but nothing happend.

## Current Behavior

In the logfile is a null pointer exception. The device is playing a radio channel from Alexa, maybe that's the problem).

## Steps to Reproduce (for Bugs)

1. Install the bose skill on alexa
2. Say play something on the in device somewhere
3. Start Openhab2 -> null pointer exception.

## Context

Logfile:
`
2018-06-10 10:50:56.877 [WARN ] [undtouch.internal.XMLResponseHandler] - null: Wrong device-ID in entity 'info': Got: '10CEA98A16A9', expected: 'b827XXXX039b'
2018-06-10 10:50:56.948 [WARN ] [dtouch.handler.BoseSoundTouchHandler] - null: Could not parse XML from string '<?xml version="1.0" encoding="UTF-8" ?><msg><header deviceID="b827XXXX039b" url="now_playing" method="GET"><request requestID="0" msgType="RESPONSE"><info type="new" /></request></header><body><nowPlaying deviceID="10CEA98A16A9" source="ALEXA" sourceAccount=""><ContentItem source="ALEXA" type="tracklisturl" location="DO_NOT_RESUME" sourceAccount="" isPresetable="false"><itemName /></ContentItem><track>Alexa</track><artist /><album /><stationName /><art artImageStatus="SHOW_DEFAULT_IMAGE" /><time total="0">1965</time><skipEnabled /><playStatus>PLAY_STATE</playStatus><skipPreviousSupported value="false" /><seekSupported value="true" /><streamType>RADIO_TRACKS</streamType></nowPlaying></body></msg>'.
java.lang.NullPointerException: null
        at org.eclipse.smarthome.binding.bosesoundtouch.internal.ContentItem.isValid(ContentItem.java:74) [219:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]
        at org.eclipse.smarthome.binding.bosesoundtouch.internal.CommandExecutor.setCurrentContentItem(CommandExecutor.java:114) [219:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]
        at org.eclipse.smarthome.binding.bosesoundtouch.internal.XMLResponseHandler.endElement(XMLResponseHandler.java:367) [219:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609) [?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782) [?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967) [?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) [?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) [?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) [?:?]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) [?:?]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) [?:?]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) [?:?]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) [?:?]
        at org.eclipse.smarthome.binding.bosesoundtouch.internal.XMLResponseProcessor.handleMessage(XMLResponseProcessor.java:45) [219:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]
        at org.eclipse.smarthome.binding.bosesoundtouch.handler.BoseSoundTouchHandler.onWebSocketText(BoseSoundTouchHandler.java:350) [219:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189) [92:org.eclipse.jetty.websocket.common:9.3.21.v20170918]
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69) [92:org.eclipse.jetty.websocket.common:9.3.21.v20170918]
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66) [92:org.eclipse.jetty.websocket.common:9.3.21.v20170918]
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158) [92:org.eclipse.jetty.websocket.common:9.3.21.v20170918]
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162) [92:org.eclipse.jetty.websocket.common:9.3.21.v20170918]
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376) [92:org.eclipse.jetty.websocket.common:9.3.21.v20170918]
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220) [92:org.eclipse.jetty.websocket.common:9.3.21.v20170918]
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220) [92:org.eclipse.jetty.websocket.common:9.3.21.v20170918]
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256) [92:org.eclipse.jetty.websocket.common:9.3.21.v20170918]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679) [92:org.eclipse.jetty.websocket.common:9.3.21.v20170918]
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511) [92:org.eclipse.jetty.websocket.common:9.3.21.v20170918]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [76:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [76:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [76:org.eclipse.jetty.io:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [87:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [87:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [87:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [87:org.eclipse.jetty.util:9.3.21.v20170918]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [87:org.eclipse.jetty.util:9.3.21.v20170918]
        at java.lang.Thread.run(Thread.java:748) [?:?]
`
## Your Environment

Openhab 2.3 on Rasp. Pi. 2, Rasbian, Alexa, Bose Soundtouch 10

**Comment by kaikreuzer** [comment] 2018-06-10 09:55
Note that this binding is maintained at https://github.com/eclipse/smarthome.

This might be a duplicate of https://github.com/eclipse/smarthome/issues/5684, so you might want to have a look at this issue first and comment on it.

**Closed by kaikreuzer** 2018-06-10 09:55 UTC
