### ISSUE TITLE
[Homematic] GATEWAY_EXTRAS not shown after configuring the binding.

### ISSUE THREAD

**Issue by DoerrSt** [openhab/openhab2-addons#2373] opened 2017-06-14 18:43 UTC
After configuring the Homematic binding a new thing "GATEWAY_EXTRAS" should be shown. But it isn't in my case. 

Looks like the adding things from the gateway is interrupted by the following error message:

2017-06-13 12:20:00.322 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'homematic:HM-LC-Sw1PBU-FM:xxxxxxxx:CUXxxxxxxx' to inbox.
2017-06-13 12:20:00.369 [ERROR] [very.HomematicDeviceDiscoveryService] - java.lang.String cannot be cast to java.util.Map
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
at org.openhab.binding.homematic.internal.communicator.parser.GetParamsetDescriptionParser.parse(GetParamsetDescriptionParser.java:41)[253:org.openhab.binding.homematic:2.1.0.201706022154]
at org.openhab.binding.homematic.internal.communicator.client.RpcClient.addChannelDatapoints(RpcClient.java:150)[253:org.openhab.binding.homematic:2.1.0.201706022154]
at org.openhab.binding.homematic.internal.communicator.CcuGateway.addChannelDatapoints(CcuGateway.java:168)[253:org.openhab.binding.homematic:2.1.0.201706022154]
at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadAllDeviceMetadata(AbstractHomematicGateway.java:407)[253:org.openhab.binding.homematic:2.1.0.201706022154]
at org.openhab.binding.homematic.discovery.HomematicDeviceDiscoveryService$1.run(HomematicDeviceDiscoveryService.java:110)[253:org.openhab.binding.homematic:2.1.0.201706022154]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
2017-06-13 12:20:39.953 [WARN ] [ommunicator.parser.GetParamsetParser] - Can't set value for datapoint 'LABxxxxxxx:1#NEXT_TRANSMISSION'

I use a CCU2 (Version 2.27.8) and the device which is causing the trouble is a HM-Sec-MDIR-2-LABxxxxxxx motion detector. The device itself shows the following properties:

```
<device config_pending="false" sticky_unreach="false" unreach="false" ise_id="3958" name="HM-Sec-MDIR-2 LABxxxxxxx">
<channel ise_id="3959" name="HM-Sec-MDIR-2 LABxxxxxxx:0" operate="" visible="">
<datapoint ise_id="3980" name="BidCos-RF.LABxxxxxxx:0.UNREACH" operations="5" timestamp="1497465644" valueunit="" valuetype="2" value="false" type="UNREACH"/>
<datapoint ise_id="3976" name="BidCos-RF.LABxxxxxxx:0.STICKY_UNREACH" operations="7" timestamp="1497465644" valueunit="" valuetype="2" value="false" type="STICKY_UNREACH"/>
<datapoint ise_id="3961" name="BidCos-RF.LABxxxxxxx:0.CONFIG_PENDING" operations="5" timestamp="1497465644" valueunit="" valuetype="2" value="false" type="CONFIG_PENDING"/>
<datapoint ise_id="3970" name="BidCos-RF.LABxxxxxxx:0.LOWBAT" operations="5" timestamp="1497465644" valueunit="" valuetype="2" value="false" type="LOWBAT"/>
<datapoint ise_id="3974" name="BidCos-RF.LABxxxxxxx:0.RSSI_DEVICE" operations="5" timestamp="1497465644" valueunit="" valuetype="8" value="1" type="RSSI_DEVICE"/>
<datapoint ise_id="3975" name="BidCos-RF.LABxxxxxxx:0.RSSI_PEER" operations="5" timestamp="1497465644" valueunit="" valuetype="8" value="212" type="RSSI_PEER"/>
<datapoint ise_id="3965" name="BidCos-RF.LABxxxxxxx:0.DEVICE_IN_BOOTLOADER" operations="5" timestamp="1497465644" valueunit="" valuetype="2" value="false" type="DEVICE_IN_BOOTLOADER"/>
<datapoint ise_id="3984" name="BidCos-RF.LABxxxxxxx:0.UPDATE_PENDING" operations="5" timestamp="1497465645" valueunit="" valuetype="2" value="false" type="UPDATE_PENDING"/>
</channel>
<channel ise_id="3988" name="HM-Sec-MDIR-2 LABxxxxxxx:1" operate="true" visible="true">
<datapoint ise_id="3989" name="BidCos-RF.LABxxxxxxx:1.BRIGHTNESS" operations="5" timestamp="1497465441" valueunit="" valuetype="16" value="254" type="BRIGHTNESS"/>
<datapoint ise_id="4013" name="BidCos-RF.LABxxxxxxx:1.MOTION" operations="5" timestamp="1497464932" valueunit="" valuetype="2" value="false" type="MOTION"/>
<datapoint ise_id="3990" name="BidCos-RF.LABxxxxxxx:1.ERROR" operations="5" timestamp="1497465441" valueunit="" valuetype="16" value="0" type="ERROR"/>
</channel>
</device>
```

I configured the whole thing via PaperUI. So no ´sitemap or item configuration has been created manually.

**Comment by MHerbst** [comment] 2017-06-15 09:40
On a first look I can't see anything special in the device properties. It seems that the CCU sends some unexpected values back to the addon. @DoerrSt  Can you enable the debug log for the Homematic binding, restart openHAB and then post the log?

**Comment by DoerrSt** [comment] 2017-06-15 16:58
@MHerbst 

I activated the debug output for this binding. and removed the existing one. After that I added the device again to ensure the Messages are not mixed up. 

It starts with the following Output:
2017-06-15 18:50:58.162 [DEBUG] [matic.handler.HomematicBridgeHandler] - HomematicConfig[gatewayAddress=192.168.178.34,callbackHost=192.168.178.32,xmlCallbackPort=9125,binCallbackPort=9126,gatewayType=ccu,rfPort=2001,wiredPort=2000,hmIpPort=2010,cuxdPort=8701,groupPort=9292,aliveInterval=300,reconnectInterval=0,timeout=15,socketMaxAlive=900]
2017-06-15 18:50:58.163 [DEBUG] [org.openhab.binding.homematic       ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=443, service.bundleid=253, service.scope=singleton} - org.openhab.binding.homematic
2017-06-15 18:50:58.430 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'WIRED' on gateway '3fb2176a' not available, disabling support
2017-06-15 18:50:58.519 [DEBUG] [ommunicator.AbstractHomematicGateway] - Initializing gateway with id '3fb2176a'
2017-06-15 18:50:58.524 [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=2.27.8,address=LEQ0586037,wired=false,hmip=true,cuxd=true,group=true]
2017-06-15 18:50:58.524 [DEBUG] [ommunicator.AbstractHomematicGateway] - Used Homematic transfer modes: RF:BIN_RPC, HMIP:XML_RPC, CUXD:BIN_RPC, GROUP:XML_RPC
2017-06-15 18:50:58.623 [DEBUG] [nal.communicator.server.BinRpcServer] - Initializing BIN-RPC server at port 9126
2017-06-15 18:50:58.628 [DEBUG] [nal.communicator.server.XmlRpcServer] - Initializing XML-RPC server at port 9125
2017-06-15 18:50:59.084 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Boolean) value 'true' for 'LEQxxxxxxx:0#UNREACH' from gateway with id '3fb2176a'


Here the Messages from the log around the exception:

2017-06-15 18:51:20.900 [DEBUG] [ommunicator.AbstractHomematicGateway] - Loaded device 'CUX2801001' (HM-LC-Sw1PBU-FM) with 533 datapoints
2017-06-15 18:51:20.900 [DEBUG] [atic.type.HomematicTypeGeneratorImpl] - Generating ThingType for device 'HM-LC-Sw1PBU-FM' with 533 datapoints
2017-06-15 18:51:20.917 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'homematic:HM-LC-Sw1PBU-FM:3fb2176a:CUX2801001' to inbox.
2017-06-15 18:51:20.946 [ERROR] [very.HomematicDeviceDiscoveryService] - java.lang.String cannot be cast to java.util.Map
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
        at org.openhab.binding.homematic.internal.communicator.parser.GetParamsetDescriptionParser.parse(GetParamsetDescriptionParser.java:41)[253:org.openhab.binding.homematic:2.1.0.201706022154]
        at org.openhab.binding.homematic.internal.communicator.client.RpcClient.addChannelDatapoints(RpcClient.java:150)[253:org.openhab.binding.homematic:2.1.0.201706022154]
        at org.openhab.binding.homematic.internal.communicator.CcuGateway.addChannelDatapoints(CcuGateway.java:168)[253:org.openhab.binding.homematic:2.1.0.201706022154]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadAllDeviceMetadata(AbstractHomematicGateway.java:407)[253:org.openhab.binding.homematic:2.1.0.201706022154]
        at org.openhab.binding.homematic.discovery.HomematicDeviceDiscoveryService$1.run(HomematicDeviceDiscoveryService.java:110)[253:org.openhab.binding.homematic:2.1.0.201706022154]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
2017-06-15 18:51:20.948 [DEBUG] [very.HomematicDeviceDiscoveryService] - Homematic device discovery scan finished
2

It continues with those messages:;
2017-06-15 18:51:21.200 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Integer) value '0' for 'LABxxxxxxx:0#RSSI_DEVICE' from gateway with id '3fb2176a'

**Comment by MHerbst** [comment] 2017-06-15 17:30
I have compared your output with my installation. The big difference is CUXD. 
Can you disable it for a test? I think it should be sufficient to configure a wrong port in the bridge configuration within openHAB. 

To get even more information you could set the log level to TRACE. With this level, we get the message content received from the CCU. But with this log level, you better attach the log file content as a file :-)

**Comment by DoerrSt** [comment] 2017-06-16 09:17
I removed the CuX-Device from Homematic and enabled TRACE level in the logs. Unfortunately the GATEWAY_EXTRAS is still not shown. I've found the following in the logs:

2017-06-16 11:01:19.015 [TRACE] [ommunicator.AbstractHomematicGateway] -     Loading datapoints into channel HmChannel[number=0,type=VIP-MAINTENANCE,initialized=false]
2017-06-16 11:01:19.016 [TRACE] [nal.communicator.client.XmlRpcClient] - Client XmlRpcRequest (port 9292):
<?xml version="1.0" encoding="ISO-8859-1"?>
<methodCall><methodName>getParamsetDescription</methodName>
<params><param><value>OL-broadcast:0</value></param><param><value>MASTER</value></param></params></methodCall>
2017-06-16 11:01:19.029 [TRACE] [nal.communicator.client.XmlRpcClient] - Client XmlRpcResponse (port 9292):
<?xml version="1.0" encoding="ISO-8859-1"?><methodResponse><params><param><value><struct></struct></value></param></params></methodResponse>
2017-06-16 11:01:19.030 [TRACE] [nal.communicator.client.XmlRpcClient] - Client XmlRpcRequest (port 9292):
<?xml version="1.0" encoding="ISO-8859-1"?>
<methodCall><methodName>getParamsetDescription</methodName>
<params><param><value>OL-broadcast:0</value></param><param><value>VALUES</value></param></params></methodCall>
2017-06-16 11:01:19.047 [TRACE] [nal.communicator.client.XmlRpcClient] - Client XmlRpcResponse (port 9292):
<?xml version="1.0" encoding="ISO-8859-1"?><methodResponse><params><param><value></value></param></params></methodResponse>
2017-06-16 11:01:19.050 [ERROR] [very.HomematicDeviceDiscoveryService] - java.lang.String cannot be cast to java.util.Map
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
    at org.openhab.binding.homematic.internal.communicator.parser.GetParamsetDescriptionParser.parse(GetParamsetDescriptionParser.java:41)[183:org.openhab.binding.homematic:2.1.0.201706122104]
    at org.openhab.binding.homematic.internal.communicator.client.RpcClient.addChannelDatapoints(RpcClient.java:150)[183:org.openhab.binding.homematic:2.1.0.201706122104]
    at org.openhab.binding.homematic.internal.communicator.CcuGateway.addChannelDatapoints(CcuGateway.java:168)[183:org.openhab.binding.homematic:2.1.0.201706122104]
    at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.loadAllDeviceMetadata(AbstractHomematicGateway.java:407)[183:org.openhab.binding.homematic:2.1.0.201706122104]
    at org.openhab.binding.homematic.discovery.HomematicDeviceDiscoveryService$1.run(HomematicDeviceDiscoveryService.java:110)[183:org.openhab.binding.homematic:2.1.0.201706122104]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_121]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
2017-06-16 11:01:19.053 [DEBUG] [very.HomematicDeviceDiscoveryService] - Homematic device discovery scan finished
2017-06-16 11:01:19.055 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcRequest:
rssiInfo()

If the full file is required I can provide it too but this is the only recorded error / exception.

**Comment by MHerbst** [comment] 2017-06-16 16:48
One possible cause of failure less. I hope the TRACE log could help as it should show more information about the received data. If it does not help I can modify the binding and create additional logging output and ignore such unexpected data types.

**Comment by DoerrSt** [comment] 2017-06-16 19:21
Here the complete logfile with TRACE loglevel

[trace.txt](https://github.com/openhab/openhab2-addons/files/1081744/trace.txt)

**Comment by MHerbst** [comment] 2017-06-16 21:39
Thanks for trace. It was really helpful. The problem is not caused by the device: HM-Sec-MDIR-2-LAB. 
It is caused by this one `Loading metadata for device 'OL-broadcast' of type 'VIR-LG-GROUP`. This is probably a group of devices. Can you give me some more information about the devices contained in this group?

The exception happens because the response from the CCU for this device is a bit different and a `<struct>` tag is missing. I can change the code in a way that this missing tag no longer leads to an exception.

**Comment by DoerrSt** [comment] 2017-06-17 06:12
This is the "new" function which Supports the Osram Lightify Gateway. Here the device details:

```
<device ise_id="5777" name="VIR-LG-GROUP OL-broadcast">
<channel ise_id="5778" name="VIR-LG-GROUP OL-broadcast:0" operate="true" visible="true"/>
<channel ise_id="5779" name="VIR-LG-GROUP OL-broadcast:1" operate="true" visible="true">
<datapoint ise_id="5780" name="VirtualDevices.OL-broadcast:1.LEVEL" operations="3" timestamp="1497634683" valueunit="100%" valuetype="4" value="0.000000" type="LEVEL"/>
<datapoint ise_id="5781" name="VirtualDevices.OL-broadcast:1.RGBW" operations="3" timestamp="1497634683" valueunit="" valuetype="20" value="rgb(255,255,255,255)" type="RGBW"/>
<datapoint ise_id="5782" name="VirtualDevices.OL-broadcast:1.WHITE" operations="3" timestamp="1497634683" valueunit="100%" valuetype="4" value="2000.000000" type="WHITE"/>
</channel>
</device>
<device ise_id="5771" name="VIR-LG-RGBW-DIM OL-a60rgbw_01">
<channel ise_id="5772" name="VIR-LG-RGBW-DIM OL-a60rgbw_01:0" operate="true" visible="true"/>
<channel ise_id="5773" name="VIR-LG-RGBW-DIM OL-a60rgbw_01:1" operate="true" visible="true">
<datapoint ise_id="5774" name="VirtualDevices.OL-a60rgbw_01:1.LEVEL" operations="3" timestamp="1497634683" valueunit="100%" valuetype="4" value="0.000000" type="LEVEL"/>
<datapoint ise_id="5775" name="VirtualDevices.OL-a60rgbw_01:1.RGBW" operations="3" timestamp="1497634683" valueunit="" valuetype="20" value="rgb(0,0,0,255)" type="RGBW"/>
<datapoint ise_id="5776" name="VirtualDevices.OL-a60rgbw_01:1.WHITE" operations="3" timestamp="1497634683" valueunit="100%" valuetype="4" value="2000.000000" type="WHITE"/>
</channel>
</device>
<device ise_id="5783" name="VIR-OL-GTW OL-OL-BRG-0001">
<channel ise_id="5784" name="VIR-OL-GTW OL-OL-BRG-0001:0" operate="true" visible="true"/>
<channel ise_id="5785" name="VIR-OL-GTW OL-OL-BRG-0001:1" operate="true" visible="true">
<datapoint ise_id="5786" name="VirtualDevices.OL-OL-BRG-0001:1.LEVEL" operations="3" timestamp="1497634683" valueunit="100%" valuetype="4" value="0.000000" type="LEVEL"/>
</channel>
</device>
```

**Comment by MHerbst** [comment] 2017-06-17 16:03
I had a close look into the trace and it seems that the Osram Lightify Gateway needs some special "treatment". I will fix the exception but I don't think that it will be sufficient to make the gateway fully work. Therefore I will then create a new issue for support of this gateway.

**Comment by DoerrSt** [comment] 2017-06-17 18:11
As there exists an Lightify Binding there is perhaps no urgent need to support the Osram Lightify Gateway, but nonetheless it would be good.

**Comment by MHerbst** [comment] 2017-06-18 08:02
@doerrst I have simply overseen that there already is a binding. In this case I would propose to simply ignore in the Osram Lightify Gateway in the Homematic binding and do everything in the Lightify binding.

**Comment by DoerrSt** [comment] 2017-06-18 09:10
@MHerbst,. Yes, ignoring the device makes sense. Just all "real" homematic devices should be available as well as the gateway-extras.

**Comment by DoerrSt** [comment] 2017-06-19 10:02
The Gateway-Extras is now shown as a device (with the patch installed). Also the virtual Osram devices are visible and do look functional (e.g. Level, White, Rgbw) are shown. I'll test later if they really work or not. In case they don't I would recommend to not import them at all to prevent any confusion.

**Comment by MHerbst** [comment] 2017-06-19 11:58
> The Gateway-Extras is now shown as a device (with the patch installed).
👍 Thanks for the feedback.

> Also the virtual Osram devices are visible and do look functional (e.g. Level, White, Rgbw). I'll test later if they really work or not. In case they don't I would recommend to not import them at all to prevent any confusion.

I am not sure whether it would be better do ignore them in any case. Regarding the Osram device please create a new issue, because this is another topic.

**Comment by DoerrSt** [comment] 2017-06-19 20:17
I am testing some things currently and if I got the documentation right the switch "Reload All from Gateway" should update all devices and variables. Is this correct? 

If yes there may be an issue that the new variable values aren't written to the database. I see updates of the things in the logs but not for the variables added by the gateway_extras-device.

**Comment by MHerbst** [comment] 2017-06-19 20:39
Sounds similar to #2333. Changing variable content in openHab should work, but currently it is not possible to refresh variable contents in openHab if they were changed in the CCU.

**Comment by DoerrSt** [comment] 2017-06-19 21:04
Sounds similiar that's true. As your patch worked to resolved the topic here shall I close this issue?

**Comment by MHerbst** [comment] 2017-06-19 21:17
Please wait until the patch is merged. Should be closed automatically by the merge process.

**Closed** 2017-06-20 08:22 UTC
