### ISSUE TITLE
Netatmo Binding getNAThingProperty nullPointerException

### ISSUE THREAD

**Issue by mcarlosro** [openhab/openhab2-addons#1557] opened 2016-12-10 06:44 UTC
Hi,

I have the latest built from 20161209 and I got the following null stacktrace

`2016-12-10 07:36:24.753 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
java.lang.NullPointerException
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.getNAThingProperty(NATherm1Handler.java:64)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:120)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:166)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.handleCommand(NATherm1Handler.java:106)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:135)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.channelLinked(NATherm1Handler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2016-12-10 07:36:24.784 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
java.lang.NullPointerException
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.getNAThingProperty(NATherm1Handler.java:64)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:120)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:166)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.handleCommand(NATherm1Handler.java:106)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:135)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.channelLinked(NATherm1Handler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2016-12-10 07:36:24.799 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
java.lang.NullPointerException
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.getNAThingProperty(NATherm1Handler.java:64)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:120)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:166)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.handleCommand(NATherm1Handler.java:106)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:135)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.channelLinked(NATherm1Handler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2016-12-10 07:36:24.819 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
java.lang.NullPointerException
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.getNAThingProperty(NATherm1Handler.java:64)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:120)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:166)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.handleCommand(NATherm1Handler.java:106)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:135)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.channelLinked(NATherm1Handler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2016-12-10 07:36:24.832 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
java.lang.NullPointerException
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.getNAThingProperty(NATherm1Handler.java:64)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:120)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:166)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.handleCommand(NATherm1Handler.java:106)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:135)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.channelLinked(NATherm1Handler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2016-12-10 07:36:24.839 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
java.lang.NullPointerException
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.getNAThingProperty(NATherm1Handler.java:64)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:120)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:166)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.handleCommand(NATherm1Handler.java:106)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:135)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.channelLinked(NATherm1Handler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2016-12-10 07:36:24.848 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
java.lang.NullPointerException
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.getNAThingProperty(NATherm1Handler.java:64)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:120)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:166)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.handleCommand(NATherm1Handler.java:106)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:135)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.channelLinked(NATherm1Handler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2016-12-10 07:36:24.855 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
java.lang.NullPointerException
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.getNAThingProperty(NATherm1Handler.java:64)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:120)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:166)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.handleCommand(NATherm1Handler.java:106)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:135)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.channelLinked(NATherm1Handler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
2016-12-10 07:36:24.862 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occured while informing handler:null
java.lang.NullPointerException
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.getNAThingProperty(NATherm1Handler.java:64)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:120)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.handleCommand(AbstractNetatmoThingHandler.java:166)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.handleCommand(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.handleCommand(NATherm1Handler.java:106)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:207)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.openhab.binding.netatmo.handler.AbstractNetatmoThingHandler.channelLinked(AbstractNetatmoThingHandler.java:135)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.NetatmoModuleHandler.channelLinked(NetatmoModuleHandler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.openhab.binding.netatmo.handler.thermostat.NATherm1Handler.channelLinked(NATherm1Handler.java:1)[194:org.openhab.binding.netatmo:2.0.0.201612091712]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612091054]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[96:org.eclipse.smarthome.core:0.9.0.201612091054]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]`

I look the other issues opened and look the same, but it is also said it is fixed, while it is not.

**Comment by lolodomo** [comment] 2016-12-10 13:12
Can be closed, it is a duplicate of opened issue #1517 .
A fix has been proposed and is working. But not yet validated.

**Closed** 2016-12-12 04:56 UTC

**Comment by svenvanlierde** [comment] 2016-12-15 13:16
Where can i download the fix?
Thanks

**Comment by lolodomo** [comment] 2016-12-15 19:49
See PR #1553
