### ISSUE TITLE
Parameters Available for Device 326

### ISSUE THREAD

**Issue by carryonrewardless** [openhab/openhab2-addons#1016] opened 2016-06-11 12:06 UTC
Page 13 of User Manual attached to Device Summary and here has some parameter details that may be useful
[DHS_Zwave_Motion_Sensor_v1.pdf](https://github.com/openhab/openhab2-addons/files/310226/DHS_Zwave_Motion_Sensor_v1.pdf)

**Comment by cdjackson** [comment] 2016-06-14 08:01
Please can you update the online database (www.cd-jackson.com).

**Comment by carryonrewardless** [comment] 2016-06-14 09:51
Fresh version of node7.xml added.

**Comment by cdjackson** [comment] 2016-06-14 10:01
Maybe I don't understand what this issue is about, but the title mentions parameters. So, if you want to update the parameters (ie configuration parametrs) then you will need to add them manually since they are not read from the device.

So, can you explain what you actually want here?

Thanks.

**Comment by carryonrewardless** [comment] 2016-06-14 12:05
Are there any guidelines for manually adding the parameters?  I am not clear on how the text translates into xml syntax. 
E.g.

**Comment by cdjackson** [comment] 2016-06-14 12:10
There are guidelines  on the website. You shouldn't need to worry about the xml - this is handled as part of the export. You should be able to take the data from the manual and add it to the database - eg the parameter number, name, size, default value, options etc - this is normally all supplied in the manufacturers document.

**Comment by carryonrewardless** [comment] 2016-06-14 12:40
Ok I have published it. Hopefully it is ok.

**Comment by cdjackson** [comment] 2016-06-14 12:47
Thanks - I'll take a look tonight.

**Comment by carryonrewardless** [comment] 2016-06-17 00:20
@cdjackson Thanks. This is looking good. Getting regular temperature, lux and battery level messages now. 
Couple of issue remain with a lot of this message:
2016-06-17 10:05:23.497 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 2678 to 2679
2016-06-17 10:05:23.527 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 2679 to 2680
2016-06-17 10:05:23.584 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 2680 to 2681
2016-06-17 10:05:23.617 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 2681 to 2682
2016-06-17 10:05:23.645 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 2682 to 2683
2016-06-17 10:05:23.669 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 2683 to 2684

in the logs. Can you see what is causing this?
Also before the latest chnage I was seeing a bit of this:
2016-06-16 23:02:33.608 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'Sensor_LivingRoom_PIR' has been added.
2016-06-16 23:02:33.742 [INFO ] [smarthome.event.ItemRemovedEvent    ] - Item 'Sensor_LivingRoom_PIR' has been removed.
2016-06-16 23:25:33.603 [INFO ] [smarthome.event.ItemRemovedEvent    ] - Item 'Sensor_LivingRoom_PIR' has been removed.
2016-06-16 23:27:19.816 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'Sensor_LivingRoom_PIR' has been added.
2016-06-16 23:27:21.216 [INFO ] [smarthome.event.ItemRemovedEvent    ] - Item 'Sensor_LivingRoom_PIR' has been removed.

but with the latest change this channel does not seem to be added. Its great that the device is now looking useable.

**Comment by carryonrewardless** [comment] 2016-06-18 00:42
An update on this. The current version seems to randomly and alternately add and then immediately remove this item also. The net result is of course that the motion detection channel of this device is non-functional with motion never actually causing the device to wake-up and report a change of state. The only parameter I have to adjust is the sensitivity which obviously is not the issue here.

**Comment by carryonrewardless** [comment] 2016-06-18 00:46
A separate issue with this device is to do with the temperature offset parameter 6. Is there an interface in either PaperUI or Habmin to alter this? I have not been able to find it so far so maybe it is a feature to be loaded at a future time?

**Comment by cdjackson** [comment] 2016-06-18 08:54
Items get removed and readded when the thing is added and removed within the software I think - I'm not 100% sure, but this probably isn't anything to do with the zwave binding.  It's hard to tell though without a log.

What is wrong with parameter 6 - I'm not sure I understand what the issue is?

**Comment by carryonrewardless** [comment] 2016-06-19 08:04
> 
What is wrong with parameter 6 - I'm not sure I understand what the issue is?
> 
Nothing wrong with it but parameter 6 is an offset for the temperature data from the device. So if I want to add a 2 degree offset I presume I don't need to go back to the database to do that. I thought there might be a facility in PaperUI or in Habmin to adjust this. Or maybe I am not understanding this correctly?

**Comment by cdjackson** [comment] 2016-06-19 08:17
Can't you just change the value of parameter 6 to adjust the calibration using HABmin or PaperUI configuration panels?  I don’t think I understand the problem - sorry.

**Comment by carryonrewardless** [comment] 2016-06-19 08:29
Ok with the PIR I might start again with my problem description. 
The PIR channel appears not to be working whereas the other channels of this device - two temperature channels, Lux luminance channel and the battery level are all reporting ok.

The log below has just been grabbed (| grep PIR) with debug on for zwave but shows no activity for the PIR channel in 2 days of people walking past it regularly:
2016-06-19 18:15:02.658 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11443 to 11444
2016-06-19 18:15:02.854 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11444 to 11445
2016-06-19 18:15:03.114 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11445 to 11446
2016-06-19 18:15:06.158 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11446 to 11447
2016-06-19 18:15:06.174 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11447 to 11448
2016-06-19 18:15:06.445 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11448 to 11449
2016-06-19 18:15:11.200 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11449 to 11450
2016-06-19 18:15:11.632 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11450 to 11451
2016-06-19 18:15:11.697 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11451 to 11452
2016-06-19 18:15:50.232 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11452 to 11453
2016-06-19 18:15:50.298 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'zwave:device:48766d53:node7' has been updated.
2016-06-19 18:15:50.322 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11453 to 11454
2016-06-19 18:15:50.379 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11454 to 11455
2016-06-19 18:17:48.416 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11455 to 11456
2016-06-19 18:17:48.486 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'zwave:device:48766d53:node7' has been updated.
2016-06-19 18:17:49.517 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11456 to 11457
2016-06-19 18:17:56.183 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11457 to 11458

This log ( | grep zwave) shows lots of reports that I don't understand and which don't "add value" (i.e. changed from 11457 to 11458) :
2016-06-19 18:15:02.658 [INFO ] )[marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11443 to 11444
2016-06-19 18:15:02.854 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11444 to 11445
2016-06-19 18:15:03.114 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11445 to 11446
2016-06-19 18:15:06.158 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11446 to 11447
2016-06-19 18:15:06.174 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11447 to 11448
2016-06-19 18:15:06.445 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11448 to 11449
2016-06-19 18:15:11.200 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11449 to 11450
2016-06-19 18:15:11.632 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11450 to 11451
2016-06-19 18:15:11.697 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11451 to 11452
2016-06-19 18:15:50.232 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11452 to 11453
2016-06-19 18:15:50.298 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'zwave:device:48766d53:node7' has been updated.
2016-06-19 18:15:50.322 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11453 to 11454
2016-06-19 18:15:50.379 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11454 to 11455
2016-06-19 18:17:48.416 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11455 to 11456
2016-06-19 18:17:48.486 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'zwave:device:48766d53:node7' has been updated.
2016-06-19 18:17:49.517 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11456 to 11457
2016-06-19 18:17:56.183 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11457 to 11458

What does "zwave_device_48766d53_node7 changed from 11457 to 11458" mean and does it relate to the problem of the device apparently not responding on the PIR channel.
Even pressing its tamper switch generates no log activity.

**Comment by cdjackson** [comment] 2016-06-19 08:32
I have no idea why this is - what is zwave_device_48766d53_node7? I guess you must have defined this - you need to find what it’s linked to.

**Comment by cdjackson** [comment] 2016-06-19 08:34
It would also be better to look at a debug log - these sort of INFO level logs are nigh on useless for trying to work out what’s happening.

**Comment by carryonrewardless** [comment] 2016-06-19 08:53
Seems I had not set DEBUG logging correctly.
Attached 
[logfile20160619.txt](https://github.com/openhab/openhab2-addons/files/322181/logfile20160619.txt)
 is the log ( | grep  node7) after deleting the Thing and then re-discovering. Do you need a broader selection from the log?

**Comment by cdjackson** [comment] 2016-06-19 09:00
Unfortunately the log doesn’t contain anything from the zwave binding. You need to enable debug for this binding using the console (unless your grep has filtered it all out).

**Comment by carryonrewardless** [comment] 2016-06-19 09:12
Ok this one does:
[logfile20160619.txt](https://github.com/openhab/openhab2-addons/files/322196/logfile20160619.txt)

**Comment by carryonrewardless** [comment] 2016-06-19 09:19
cat /openhab.log | grep PIR  is very brief:
2016-06-19 19:16:41.466 [DEBUG] [io.socket.parser.Parser             ] - encoded io.socket.parser.Packet@97dd3f as 2["itemupdate",{"itemName":"Sensor_LivingRoom_PIR","itemStatus":"OFF"}]

**Comment by cdjackson** [comment] 2016-06-19 09:20
Ok - unfortunately it still doesn’t help as I have no idea what this item is and it doesn’t seem to be associated with anything that’s happening in ZWave if this now includes all the ZWave binding logs. You need to look at what this item is - it must be something you’ve configured?

**Comment by carryonrewardless** [comment] 2016-06-19 10:23
Well zwave_device_48766d53_node7 is the Multi-sensor zwave device with two channels for temperature, one for luminance, one for motion and the battery level.
In the Items file we have
Number Temperature_GF_Entry    "Temperature [%.1f °C]" <temperature>   (Temperature, GF_Living, HouseTemps) {channel="zwave:device:48766d53:node7:sensor_temperature"}
Number Temperature_GF_Entr2    "Temperatur2 [%.1f °C]" <temperature>   (Temperature, GF_Living, HouseTemps) {channel="zwave:device:48766d53:node7:sensor_temperature1"}
Number Sensor_LivingRoom_Lux   "Living Room Lux [%.0f Lux]" 	<lux>	(GF_Living)			{channel="zwave:device:48766d53:node7:sensor_luminance2"}
Contact Sensor_LivingRoom_PIR  "Living Room PIR"		<pir>	(GF_Living)			{channel="zwave:device:48766d53:node7:sensor_binary"}
Number Sensor_LivingRoom_Batt   "Living Room Battery [%d %%]"       (GF_Living)                    	 {channel="zwave:device:48766d53:node7:battery-level"}
Maybe the PIR needs to be on the alarm channel not the sensor_binary.

**Comment by carryonrewardless** [comment] 2016-06-19 10:41
Screenshot:
![screenshot from 2016-06-19 20 40 44](https://cloud.githubusercontent.com/assets/7085477/16176857/3312b02e-365e-11e6-8838-d1427aa41396.png)

**Comment by cdjackson** [comment] 2016-06-19 10:43
> On 19 Jun 2016, at 11:23, carryonrewardless <notifications@github.com> wrote:
> 
> Well zwave_device_48766d53_node7 is the Multi-sensor zwave device with two channels for temperature, one for luminance, one for motion and the battery level.

I don’t think so - this is defined as an item - not a thing. If it were a thing URI, it would look different as the underscores would be replaced with colons (zwave:device:48766d53:node7).  You’re getting ITEM state change events -:

[marthome.event.ItemStateChangedEvent] - zwave_device_48766d53_node7 changed from 11444 to 11445

So, I think you have defined this as an item, and it’s linked to some channel, but I can’t tell what.

**Comment by cdjackson** [comment] 2016-06-19 10:43
> On 19 Jun 2016, at 11:41, carryonrewardless <notifications@github.com> wrote:
> 
> Screenshot:

Sorry - I'm not sure what this is trying to show?

**Comment by carryonrewardless** [comment] 2016-06-19 11:11
The screenshot shows that the Thing is the zwave device Zwave Node 7:MultiSensor Wintop and the channels for it.
"If it were a thing URI, it would look different as the underscores would be replaced with colons (zwave:device:48766d53:node7)"
Thanks for this clarification. I was not aware of that subtlety. I listed my Items file lines above. I am not clear on how to redefine these to get the PIT working.  The other channels for this device seem to be working ok and I was ( in my limited knowledge of the system) using something similar to trya nf get the PIR channel working. Not sure where to go from here. How does linking items in a channel in Habmin work c.f. defining items as I have done manually (a la OH1) in the Items file? 
Thanks for your patience.

**Comment by cdjackson** [comment] 2016-06-19 11:20
In HABmin, you can link items to channels by selecting the thing, then on the right side of the window there will be a list of channels. You should be able to see there what is linked. However, if you’ve got some random link to some channel, then it might not be so simple to find. You could go to Configuration | Items and see what is listed there in case you’ve created an item in the UI (i.e. just because you listed your items that you created manually, doesn’t mean that these are the only items in the system).

I just had a read through the manual. It states that the device sends the BASIC class when it detects an alarms, and the SENSOR__BINARY can be used to check the alarm. So, in this case we need to assume that BASIC and SENSOR_BINARY are the same. I’ve just updated the database to do this.

**Comment by carryonrewardless** [comment] 2016-06-19 11:35
> I’ve just updated the database to do this.
> 
I will check once the new update comes through before I change anything.

**Comment by carryonrewardless** [comment] 2016-06-19 13:11
It is now looking to me like all of the channels on this node7 device are only updating when I do something to the system like a change in the Items file. So obviously I have the configuration fundamentally not right.

**Comment by rtvb** [comment] 2016-06-19 17:37
Note to self: this device is similar to 374:

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/374

(rebranded)

**Comment by cdjackson** [comment] 2016-07-31 11:05
I'm not completely sure where this is at. I think we resolved the original issue so let's close this and if there are still outstanding issues then please open a new request [in the new Z-Wave repository](https://github.com/openhab/org.openhab.binding.zwave/issues).

**Closed by cdjackson** 2016-07-31 11:05 UTC
Labels: z-wave
