### ISSUE TITLE
[MiHome] NPE, cannot discover things

### ISSUE THREAD

**Issue by iSevenDays** [openhab/openhab2-addons#3367] opened 2018-03-19 21:01 UTC
```
/Users/seven/openhab/runtime/bin/inc: line 77: ulimit: open files: cannot modify limit: Invalid argument
karaf: Could not set maximum file descriptor limit: 524288

                          __  _____    ____
  ____  ____  ___  ____  / / / /   |  / __ )
 / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  |
/ /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ /
\____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/
    /_/                        2.2.0
                               Release Build

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.

openhab> Exception in thread "Thread-131" java.lang.NullPointerException
	at org.openhab.binding.mihome.internal.discovery.XiaomiItemDiscoveryService.onItemUpdate(XiaomiItemDiscoveryService.java:87)
	at org.openhab.binding.mihome.handler.XiaomiBridgeHandler.notifyListeners(XiaomiBridgeHandler.java:206)
	at org.openhab.binding.mihome.handler.XiaomiBridgeHandler.onDataReceived(XiaomiBridgeHandler.java:154)
	at org.openhab.binding.mihome.internal.socket.XiaomiSocket$ReceiverThread.notifyAll(XiaomiSocket.java:234)
	at org.openhab.binding.mihome.internal.socket.XiaomiSocket$ReceiverThread.receiveData(XiaomiSocket.java:210)
	at org.openhab.binding.mihome.internal.socket.XiaomiSocket$ReceiverThread.run(XiaomiSocket.java:189)
Exception in thread "Thread-135" java.lang.NullPointerException
	at org.openhab.binding.mihome.internal.discovery.XiaomiItemDiscoveryService.onItemUpdate(XiaomiItemDiscoveryService.java:87)
	at org.openhab.binding.mihome.handler.XiaomiBridgeHandler.notifyListeners(XiaomiBridgeHandler.java:206)
	at org.openhab.binding.mihome.handler.XiaomiBridgeHandler.onDataReceived(XiaomiBridgeHandler.java:154)
	at org.openhab.binding.mihome.internal.socket.XiaomiSocket$ReceiverThread.notifyAll(XiaomiSocket.java:234)
	at org.openhab.binding.mihome.internal.socket.XiaomiSocket$ReceiverThread.receiveData(XiaomiSocket.java:210)
	at org.openhab.binding.mihome.internal.socket.XiaomiSocket$ReceiverThread.run(XiaomiSocket.java:189)
```

## Expected Behavior
Things are discovered correctly. I have a temperature sensor and a door sensor.

## Current Behavior
I have successfully added a gateway, and I have enabled local developer access and entered the password of the gateway to openhab.

## Steps to Reproduce (for Bugs)

1.
2.

## Context
I have installed "binding-mihome - 2.2.0".

## Your Environment
Mac OS 10.13.3

I have tried running "Scan for Things", but nothing is discovered.

(py36) AS-Mac-Pro:openhab seven$ java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

**Comment by iSevenDays** [comment] 2018-03-20 13:10
Next day, after restarting, I was able to discover new things.

**Comment by C4ET4uK** [comment] 2018-03-20 21:54
Looks like it was some error in message. Missing "model" node.
Can you reproduce the error anymore?

**Comment by iSevenDays** [comment] 2018-03-21 18:17
@C4ET4uK  I was able to reproduce another bug - all my things were UNINITIALIZED except mi home binding gateway thing that was staying INITIALIZING for like forever. Even restart didn't help me. After I rebooted my mac, things were discovered again and after some time I saw that network biding showed that my iPhone was connected(online).
But when I went to control panel - it showed that my iPhone is not online.

Unfortunately, this forced me to switch to another home automation system that is reliable up to this time.

**Comment by wborn** [comment] 2018-03-24 12:46
> (py36) AS-Mac-Pro:openhab seven$ java --version
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

As far as I know Java 9 is still unsupported by openHAB. So you might find openHAB more reliable when using Java 8 instead @iSevenDays.

See also issues like https://github.com/eclipse/smarthome/issues/4369.

**Comment by dimalo** [comment] 2018-03-30 11:13
Hi @iSevenDays 
Thanks for your report!
As @wborn mentioned please try to install Java 8 and reproduce the issue. Thank sou!

**Comment by dimalo** [comment] 2018-04-15 21:06
@iSevenDays 
any progress on this?
@wborn otherwise I'd suggest to close this and let the issuer reopen if needed.

**Closed** 2018-04-16 06:16 UTC
