### ISSUE TITLE
[Astro] Next total eclipse of moon has date 2018-00-31

### ISSUE THREAD

**Issue by aness-github** [openhab/openhab2-addons#1995] opened 2017-03-05 13:21 UTC
Using Astro Binding for OpenHAB2 the date of Local Moon Total Eclipse is set to 2018-00-31.

Correct date seems to be 2018-01-31, https://www.timeanddate.com/eclipse/lunar/2018-january-31

**Comment by NorbertHD** [comment] 2017-03-06 20:16
The error is in smarthome/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js.
Javascript getMonth() returns 0-11. So 1 has to be added when displaying the numerical month value.
```diff
 .../ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js      | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js b/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
index 4ebf2ee9b..ec5a2ed71 100644
--- a/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
+++ b/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/js/services.js
@@ -368,7 +368,7 @@ angular.module('PaperUI.services', [ 'PaperUI.constants' ]).config(function($htt
                         if (param.context.toUpperCase() === 'TIME') {
                             value = (value.getHours() < 10 ? '0' : '') + value.getHours() + ':' + (value.getMinutes() < 10 ? '0' : '') + value.getMinutes();
                         } else if (param.context.toUpperCase() === 'DATE') {
-                            value = (value.getFullYear() + '-' + (value.getMonth() < 10 ? '0' : '') + (value.getMonth() + 1) + '-' + value.getDate());
+                            value = (value.getFullYear() + '-' + ((value.getMonth() + 1) < 10 ? '0' : '') + (value.getMonth() + 1) + '-' + value.getDate());
                         }
                     }
                 }
@@ -449,7 +449,7 @@ angular.module('PaperUI.services', [ 'PaperUI.constants' ]).config(function($htt
                         if (date) {
                             if (typeof sending !== "undefined" && sending) {
                                 if (parameter.context.toUpperCase() === 'DATE') {
-                                    configuration[parameter.name] = date instanceof Date ? (date.getFullYear() + '-' + (date.getMonth() < 10 ? '0' : '') + (date.getMonth() + 1) + '-' + date.getDate()) : date;
+                                    configuration[parameter.name] = date instanceof Date ? (date.getFullYear() + '-' + ((date.getMonth() + 1) < 10 ? '0' : '') + (date.getMonth() + 1) + '-' + date.getDate()) : date;
                                 } else {
                                     configuration[parameter.name] = date instanceof Date ? (date.getHours() < 10 ? '0' : '') + date.getHours() + ':' + (date.getMinutes() < 10 ? '0' : '') + date.getMinutes() : date;
                                 }
@@ -689,10 +689,10 @@ angular.module('PaperUI.services', [ 'PaperUI.constants' ]).config(function($htt
                                 str = formatNumber(hours) + ":" + formatNumber(date.getMinutes()) + ":" + formatNumber(date.getSeconds()) + " " + ampm;
                                 break;
                             case 'D':
-                                str = formatNumber(date.getMonth()) + "/" + formatNumber(date.getDate()) + "/" + formatNumber(date.getFullYear());
+                                str = formatNumber(date.getMonth() + 1) + "/" + formatNumber(date.getDate()) + "/" + formatNumber(date.getFullYear());
                                 break;
                             case 'F':
-                                str = formatNumber(date.getFullYear()) + "-" + formatNumber(date.getMonth()) + "-" + formatNumber(date.getDate());
+                                str = formatNumber(date.getFullYear()) + "-" + formatNumber(date.getMonth() + 1) + "-" + formatNumber(date.getDate());
                                 break;
                             case 'c':
                                 str = date;
```

**Comment by martinvw** [comment] 2017-11-03 15:09
@aounhaider1 any updates?

**Comment by aounhaider1** [comment] 2017-11-03 15:17
@martinvw the problem is already fixed in ESH so it should work now. The issue can be closed.

**Closed** 2017-11-03 15:29 UTC
