### ISSUE TITLE
Virtual datapoint for HM-Disp-EP-WM55 not working with Homegear

### ISSUE THREAD

**Issue by mhaack** [openhab/openhab2-addons#2339] opened 2017-06-06 09:11 UTC
The virtual datapoint for the HM-Disp-EP-WM55 display (introduced with #2024) does not working if Homegear is used.

I'm getting the following error in the log:

```2017-06-06 11:07:54.861 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.internal.ThingManager@1756af8' takes more than 5000ms.
2017-06-06 11:07:54.990 [ERROR] [ematic.handler.HomematicThingHandler] - -100 No answer from device. (sending setValue()
NEQ0711284:3
SUBMIT
0x02,0x0a,0x12,0x20,0x0a,0x12,0x20,0x0a,0x12,0x20,0x0a,0x14,0xc0,0x1c,0xd0,0x1D,0xe0,0x16,0xf0,0x03
)
java.io.IOException: -100 No answer from device. (sending setValue()
NEQ0711284:3
SUBMIT
0x02,0x0a,0x12,0x20,0x0a,0x12,0x20,0x0a,0x12,0x20,0x0a,0x14,0xc0,0x1c,0xd0,0x1D,0xe0,0x16,0xf0,0x03
)
	at org.openhab.binding.homematic.internal.communicator.parser.RpcResponseParser.parse(RpcResponseParser.java:50)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:90)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:102)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:78)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.communicator.client.RpcClient.setDatapointValue(RpcClient.java:281)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway$1.execute(AbstractHomematicGateway.java:614)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:61)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:593)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:572)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.communicator.virtual.DisplayTextVirtualDatapoint.handleCommand(DisplayTextVirtualDatapoint.java:382)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway$1.execute(AbstractHomematicGateway.java:601)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:61)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:593)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:572)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.openhab.binding.homematic.handler.HomematicThingHandler.handleCommand(HomematicThingHandler.java:177)[220:org.openhab.binding.homematic:2.1.0.201705212134]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:366)[106:org.eclipse.smarthome.core.thing:0.9.0.201705120951]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.201705120951]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.executeDirectly(SafeMethodCaller.java:218)[99:org.eclipse.smarthome.core:0.9.0.201705120951]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:189)[99:org.eclipse.smarthome.core:0.9.0.201705120951]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83)[99:org.eclipse.smarthome.core:0.9.0.201705120951]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67)[99:org.eclipse.smarthome.core:0.9.0.201705120951]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:363)[106:org.eclipse.smarthome.core.thing:0.9.0.201705120951]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:46)[99:org.eclipse.smarthome.core:0.9.0.201705120951]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[99:org.eclipse.smarthome.core:0.9.0.201705120951]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[99:org.eclipse.smarthome.core:0.9.0.201705120951]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181)[99:org.eclipse.smarthome.core:0.9.0.201705120951]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]```

The device is configured the following way:

```/* HM-Dis-EP-WM55 Switch with ePaper Display */
Switch Switch_GF_Floor_1_C1_Short       "Alarmschalter Flur EG Kanal 1 Kurz"                    <switch>      (gHouse)                                      {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:1#PRESS_SHORT"}
Switch Switch_GF_Floor_1_C1_Long        "Alarmschalter Flur EG Kanal 1 Lang"                    <switch>      (gHouse)                                      {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:1#PRESS_LONG"}
Switch Switch_GF_Floor_1_C2_Short       "Alarmschalter Flur EG Kanal 2 Kurz"                    <switch>      (gHouse)                                      {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:2#PRESS_SHORT"}
Switch Switch_GF_Floor_1_C2_Long        "Alarmschalter Flur EG Kanal 2 Lang"                    <switch>      (gHouse)                                      {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:2#PRESS_LONG"}
Number Switch_GF_Floor_1_RSSI           "Alarmschalter Flur EG RSSI [%d dBm]"                   <signal>      (gRSSI)                                       {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:0#RSSI"}
Switch Switch_GF_Floor_1_LowBat         "Alarmschalter Flur EG Batterie [%s]"                   <battery>     (gBattery)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:0#LOWBAT"}
String Switch_GF_Floor_1_Display        "Alarmschalter Flur EG Display"                         <wallswitch>  (gHouse)                                      {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:3#SUBMIT"}
Switch Switch_GF_Floor_1_Unreach        "Alarmschalter unreachable"                             <brokenlink>  (gUnreach)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:0#UNREACH"}
String Switch_GF_Floor_1_Display_L1     "Display Line 1"                                        <wallswitch>    (gHouse)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:3#DISPLAY_LINE_1"}
String Switch_GF_Floor_1_Display_L2     "Display Line 2"                                        <wallswitch>    (gHouse)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:3#DISPLAY_LINE_2"}
String Switch_GF_Floor_1_Display_L3     "Display Line 3"                                        <wallswitch>    (gHouse)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:3#DISPLAY_LINE_3"}
String Switch_GF_Floor_1_Display_I1     "Display Icon 1"                                        <wallswitch>    (gHouse)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:3#DISPLAY_ICON_1"}
String Switch_GF_Floor_1_Display_I2     "Display Icon 2"                                        <wallswitch>    (gHouse)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:3#DISPLAY_ICON_2"}
String Switch_GF_Floor_1_Display_I3     "Display Icon 3"                                        <wallswitch>    (gHouse)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:3#DISPLAY_ICON_3"}
String Switch_GF_Floor_1_Display_LED    "Display LED"                                           <wallswitch>    (gHouse)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:3#DISPLAY_LED"}
String Switch_GF_Floor_1_Display_BEEPER "Display BEEPER"                                        <wallswitch>    (gHouse)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:3#DISPLAY_BEEPER"}
Number Switch_GF_Floor_1_Display_BC     "Display BEEPER COUNT"                                  <wallswitch>    (gHouse)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:3#DISPLAY_BEEPCOUNT"}
Switch Switch_GF_Floor_1_Display_SUBMIT "Display SUBMIT"                                        <wallswitch>    (gHouse)                                    {channel="homematic:HG-HM-Dis-EP-WM55:ccu:NEQ0711284:3#DISPLAY_SUBMIT"}
```

I think the problem is the hex format of the string send to the SUBMIT channel. Sending a plain string like `020a1246656e737465722f547d7213820A124861757313840A12487d74746513840A14C51CD01DE016F203` works perfect.

**Comment by MHerbst** [comment] 2017-06-06 17:16
`I think the problem is the hex format of the string send to the SUBMIT channel. Sending a plain string like 020a1246656e737465722f547d7213820A124861757313840A12487d74746513840A14C51CD01DE016F203 works perfect.`

Thank you for this information. I have got the same device and use it together with the CCU. I will try whether the plain string also works with the CCU. In this case we would only need one implementation variant.

**Comment by MHerbst** [comment] 2017-06-14 18:40
I have tried to send a plain string to the CCU but it does not work (I only get an exception). That means we need different values for Homegear and the CCU :-(. I can implement it but need to know how to finde out the bridge type.
@gerrieg what is the best way to find out whether a CCU or Homegear is used? HmDevice seems to contain information that could give a hint but I am not sure about it.

**Comment by gerrieg** [comment] 2017-06-18 07:51
I think it's better to implement this in Homegear. Because Homegear want's to be compatible with the CCU, it should accept the same string.

@mhaack 
Can you please ask Sathya in the Homegear forum? https://forum.homegear.eu

@MHerbst
just for you info: It's in the HomematicConfig class, config.getGatewayInfo().isHomegear()

**Comment by MHerbst** [comment] 2017-06-18 07:56
@gerrieg You are right, it's probably better to do in Homegear. And thanks for the info.

@mhaack Can you close this issue?

**Closed** 2017-06-19 06:35 UTC
