### ISSUE TITLE
[chromecast] communication error - connection refused

### ISSUE THREAD

**Issue by Stefan300381** [openhab/openhab2-addons#5257] opened 2019-03-26 14:15 UTC
## Expected Behavior
google home audiogroup thing should stay online

## Current Behavior
Thing randomly switches between online and offline status.

## Possible Solution
no solution 

## Steps to Reproduce (for Bugs)
just wait and then I see something like this:
```
2019-03-26 15:02:05.887 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Got IOException while reading due to stream being closed (stop=true)
2019-03-26 15:02:05.905 [hingStatusInfoChangedEvent] - 'chromecast:audiogroup:45beba5c-5205-40b9-90ee-31c9c6d49fa6' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Connection refused (Connection refused)
2019-03-26 15:02:05.954 [me.event.ThingUpdatedEvent] - Thing 'chromecast:audiogroup:45beba5c-5205-40b9-90ee-31c9c6d49fa6' has been updated.
2019-03-26 15:02:06.405 [hingStatusInfoChangedEvent] - 'chromecast:audiogroup:45beba5c-5205-40b9-90ee-31c9c6d49fa6' changed from OFFLINE (COMMUNICATION_ERROR): Connection refused (Connection refused) to ONLINE
2019-03-26 15:02:06.434 [me.event.ThingUpdatedEvent] - Thing 'chromecast:audiogroup:45beba5c-5205-40b9-90ee-31c9c6d49fa6' has been updated.
2019-03-26 15:02:06.530 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while reading
su.litvak.chromecast.api.v2.ChromeCastException: Remote socket closed
	at su.litvak.chromecast.api.v2.Channel.read(Channel.java:425) ~[216:org.openhab.binding.chromecast:2.5.0.M1]
	at su.litvak.chromecast.api.v2.Channel.access$200(Channel.java:51) ~[216:org.openhab.binding.chromecast:2.5.0.M1]
	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:137) [216:org.openhab.binding.chromecast:2.5.0.M1]
2019-03-26 15:02:06.537 [WARN ] [su.litvak.chromecast.api.v2.Channel ] -  <--  null payload in message 
2019-03-26 15:02:06.562 [hingStatusInfoChangedEvent] - 'chromecast:audiogroup:45beba5c-5205-40b9-90ee-31c9c6d49fa6' changed from ONLINE to OFFLINE
2019-03-26 15:02:16.597 [hingStatusInfoChangedEvent] - 'chromecast:audiogroup:45beba5c-5205-40b9-90ee-31c9c6d49fa6' changed from OFFLINE to OFFLINE (COMMUNICATION_ERROR): Connection refused (Connection refused)
```

## Context
using the android google home app I've created a google home audiogroup for all the devices I have in the house. the audiogroup is affected by the random online/offline issue. sometimes even individual google home devices are affected, but most of the time it's the audiogrop. 

## Your Environment
OrangePi with OH 2.5 M1

**Comment by cweitkamp** [comment] 2019-03-26 15:14
> The ChromeCast may close connection by itself based on some timeout. (see https://github.com/openhab/openhab2-addons/issues/3770#issuecomment-414931546).

The binding does the right thing here. I toggles between OFFLINE and ONLINE as the underlying library disconnects and reconnects again.

Closing this issue for being a duplicate of #3770 and #1935.

**Closed by cweitkamp** 2019-03-26 15:14 UTC
Labels: duplicate, won't fix
