### ISSUE TITLE
[Freebox] Possible memory leak

### ISSUE THREAD

**Issue by Orfait** [openhab/openhab2-addons#3767] opened 2018-07-26 19:53 UTC
I am experiencing a probable memory leak in openhab, RAM is at almost 100% (2GB) in few hours and begins to use swap (500MB).

After some tests, I discovered that I can "fix" this memory issue by disabling the Freebox binding.

My setup is :
- Openhab 2.3.0 stable under debian 9 LXC container in Proxmox
- Zulu 8.30.0.1-linux64
- All config made with text files
- bindings are installed with addons.cfg
- Freebox Binding v2.3.0

Ask me for more info if needed.

**Comment by lolodomo** [comment] 2018-07-27 06:23
Weird. I am using this binding.
The problem could be inside the binding or in the library we rely on.
At my knowledge nothing was changed since a long time.
I have no idea where to start.

@clinique for information.

**Comment by Orfait** [comment] 2018-07-27 06:37
https://www.openhab.org/docs/installation/#prerequisites

OpenHAB should work with Zulu, Oracle JRE and OpenJDK. But for the last one, docs says we could have compatibility issues.

In the doc, Zulu is the only one which does not have any disadvantage. So, natural choice.

I will try Oracle JRE today.

**Comment by clinique** [comment] 2018-07-27 06:52
@lolodomo : no change on my side and for good reason, I quit Free a year ago. So can not help... :(

**Comment by lolodomo** [comment] 2018-07-27 07:14
So I become officially the only maintener of this binding.

**Comment by clinique** [comment] 2018-07-27 07:20
Sorry, yes. Maybe I'll start the same for Orange ...

**Comment by Orfait** [comment] 2018-07-27 11:07
First result :
30% of RAM at the beginning become more than 61% after 3 hours.

So, switch to Oracle JRE does not show progress on RAM usage.
I will let a chance for a stabilisation over time. Let's see in 4-5 hours.

**Comment by Orfait** [comment] 2018-07-27 15:52
I am now reaching 100% of RAM usage.

How should we do to fix this issue ?

**Comment by lolodomo** [comment] 2018-07-27 18:14
And without this binding, you have no increase of memory  ?

**Comment by Orfait** [comment] 2018-07-27 18:17
When I remove it, memory usage is constant.

**Comment by lolodomo** [comment] 2018-07-27 18:40
How do you measure the memory usage  ? 
Which command ? 

What things did ypu setup and with what refresh setting ?

**Comment by Orfait** [comment] 2018-07-27 19:16
As OpenHAB is running in proxmox (LXC container), I can see memory usage directly in proxmox.
I also confirmed that this memory usage is associated to OpenHAB :
- top command, sorted by memory usage, show high memory usage on java process
- memory usage falls when restarting OpenHAB

Then, I started to disable addons one by one.

things :
`Bridge freebox:server:FreeboxServer "Freebox" [ fqdn="mafreebox.freebox.fr:80", useOnlyHttp=true, appToken="xxx", refreshInterval=30 ] {
    Thing phone telephone "Téléphone fixe" [ refreshPhoneInterval=10, refreshPhoneCallsInterval=10 ]
    Thing net_device iphone1 "iPhone 1" [ macAddress="XXX" ]
    Thing net_device iphone2 "iPhone 2" [ macAddress="XXX" ]
    Thing net_device mobile1 "Téléphone 1" [ macAddress="XXX" ]
}`

items :
`String      Freebox_Fwversion                       "Firmware Version"                 (Freebox) {channel="freebox:server:FreeboxServer:fwversion"}
Number      Freebox_Uptime                          "Server uptime"                    (Freebox) {channel="freebox:server:FreeboxServer:uptime"}
Switch      Freebox_Restarted                       "Just restarted"                   (Freebox) {channel="freebox:server:FreeboxServer:restarted"}
Number      Freebox_Tempcpum                        "CPUm Temperature"                 (Freebox) {channel="freebox:server:FreeboxServer:tempcpum"}
Number      Freebox_Tempcpub                        "CPUb Temperature"                 (Freebox) {channel="freebox:server:FreeboxServer:tempcpub"}
Number      Freebox_Tempswitch                      "Switch Temperature"               (Freebox) {channel="freebox:server:FreeboxServer:tempswitch"}
Number      Freebox_Fanspeed                        "Fan Speed"                        (Freebox) {channel="freebox:server:FreeboxServer:fanspeed"}
Switch      Freebox_Reboot                          "Reboot Freebox"                   (Freebox) {channel="freebox:server:FreeboxServer:reboot"}
Number      Freebox_LcdBrightness                   "Screen Brightness"                (Freebox) {channel="freebox:server:FreeboxServer:lcd_brightness"}
Number      Freebox_LcdOrientation                  "Screen Orientation"               (Freebox) {channel="freebox:server:FreeboxServer:lcd_orientation"}
Switch      Freebox_LcdForced                       "Forced Orientation"               (Freebox) {channel="freebox:server:FreeboxServer:lcd_forced"}
Switch      Freebox_WifiStatus                      "Wifi Enabled"                     (Freebox) {channel="freebox:server:FreeboxServer:wifi_status"}
Switch      Freebox_FtpStatus                       "FTP Server Enabled"               (Freebox) {channel="freebox:server:FreeboxServer:ftp_status"}
Switch      Freebox_AirmediaStatus                  "Air Media Enabled"                (Freebox) {channel="freebox:server:FreeboxServer:airmedia_status"}
Switch      Freebox_UpnpavStatus                    "UPnP AV Enabled"                  (Freebox) {channel="freebox:server:FreeboxServer:upnpav_status"}
Switch      Freebox_SambafileshareStatus            "Window File Sharing Enabled"      (Freebox) {channel="freebox:server:FreeboxServer:sambafileshare_status"}
Switch      Freebox_SambaprintershareStatus         "Window Printer Sharing Enabled"   (Freebox) {channel="freebox:server:FreeboxServer:sambaprintershare_status"}
String      Freebox_XdslStatus                      "xDSL Status"                      (Freebox) {channel="freebox:server:FreeboxServer:xdsl_status"}
String      Freebox_LineStatus                      "Line Status"                      (Freebox) {channel="freebox:server:FreeboxServer:line_status"}
String      Freebox_Ipv4                            "IP Address"                       (Freebox) {channel="freebox:server:FreeboxServer:ipv4"}
Number      Freebox_RateUp                          "Upload Rate"                      (Freebox) {channel="freebox:server:FreeboxServer:rate_up"}
Number      Freebox_RateDown                        "Download Rate"                    (Freebox) {channel="freebox:server:FreeboxServer:rate_down"}
Number      Freebox_BytesUp                         "Uploaded"                         (Freebox) {channel="freebox:server:FreeboxServer:bytes_up"}
Number      Freebox_BytesDown                       "Downloaded"                       (Freebox) {channel="freebox:server:FreeboxServer:bytes_down"}`

`Switch      TelephoneFixe_StateOnhook               "State onhook"                     (Freebox) {channel="freebox:phone:FreeboxServer:telephone:state#onhook"}
Switch      TelephoneFixe_StateRinging              "State ringing"                    (Freebox) {channel="freebox:phone:FreeboxServer:telephone:state#ringing"}
String      TelephoneFixe_AnyCallNumber             "Any call number"                  (Freebox) {channel="freebox:phone:FreeboxServer:telephone:any#call_number"}
Number      TelephoneFixe_AnyCallDuration           "Any call duration"                (Freebox) {channel="freebox:phone:FreeboxServer:telephone:any#call_duration"}
DateTime    TelephoneFixe_AnyCallTimestamp          "Any call timestamp"               (Freebox) {channel="freebox:phone:FreeboxServer:telephone:any#call_timestamp"}
String      TelephoneFixe_AnyCallStatus             "Any call status"                  (Freebox) {channel="freebox:phone:FreeboxServer:telephone:any#call_status"}
String      TelephoneFixe_AnyCallName               "Any call name"                    (Freebox) {channel="freebox:phone:FreeboxServer:telephone:any#call_name"}
String      TelephoneFixe_AcceptedCallNumber        "Accepted call number"             (Freebox) {channel="freebox:phone:FreeboxServer:telephone:accepted#call_number"}
Number      TelephoneFixe_AcceptedCallDuration      "Accepted call duration"           (Freebox) {channel="freebox:phone:FreeboxServer:telephone:accepted#call_duration"}
DateTime    TelephoneFixe_AcceptedCallTimestamp     "Accepted call timestamp"          (Freebox) {channel="freebox:phone:FreeboxServer:telephone:accepted#call_timestamp"}
String      TelephoneFixe_AcceptedCallName          "Accepted call name"               (Freebox) {channel="freebox:phone:FreeboxServer:telephone:accepted#call_name"}
String      TelephoneFixe_MissedCallNumber          "Missed call number"               (Freebox) {channel="freebox:phone:FreeboxServer:telephone:missed#call_number"}
Number      TelephoneFixe_MissedCallDuration        "Missed call duration"             (Freebox) {channel="freebox:phone:FreeboxServer:telephone:missed#call_duration"}
DateTime    TelephoneFixe_MissedCallTimestamp       "Missed call timestamp"            (Freebox) {channel="freebox:phone:FreeboxServer:telephone:missed#call_timestamp"}
String      TelephoneFixe_MissedCallName            "Missed call name"                 (Freebox) {channel="freebox:phone:FreeboxServer:telephone:missed#call_name"}
String      TelephoneFixe_OutgoingCallNumber        "Outgoing call number"             (Freebox) {channel="freebox:phone:FreeboxServer:telephone:outgoing#call_number"}
Number      TelephoneFixe_OutgoingCallDuration      "Outgoing call duration"           (Freebox) {channel="freebox:phone:FreeboxServer:telephone:outgoing#call_duration"}
DateTime    TelephoneFixe_OutgoingCallTimestamp     "Outgoing call timestamp"          (Freebox) {channel="freebox:phone:FreeboxServer:telephone:outgoing#call_timestamp"}
String      TelephoneFixe_OutgoingCallName          "Outgoing call name"               (Freebox) {channel="freebox:phone:FreeboxServer:telephone:outgoing#call_name"}`

`Switch      IPhone1_Reachable                 "Reachable"                                  {channel="freebox:net_device:FreeboxServer:iphone1:reachable"}
Switch      IPhone2_Reachable             "Reachable"                                  {channel="freebox:net_device:FreeboxServer:iphone2:reachable"}
Switch      Telephone1              "Reachable"                                  {channel="freebox:net_device:FreeboxServer:mobile1:reachable"}
`

**Comment by lolodomo** [comment] 2018-07-28 08:19
The binding is requesting some objects from the underlying library. Few of these objects contain or are list of objects. I am not sure if I need to clear the lists after using them or if I should let Java garbage collector deal with that ?
Maybe @maggu2810 can answer to this question ?

**Comment by lolodomo** [comment] 2018-07-28 10:12
Looking at the code of the binding itself, I can find what could lead to a memory leak.

**Comment by Orfait** [comment] 2018-07-28 11:35
Nice, I can help for testing.

**Comment by Orfait** [comment] 2018-07-28 12:31
I can't build but I can deploy a jar.

**Comment by lolodomo** [comment] 2018-07-28 13:12
Please check if this is better with this version.
[org.openhab.binding.freebox-2.4.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/2237988/org.openhab.binding.freebox-2.4.0-SNAPSHOT.zip)

**Comment by Orfait** [comment] 2018-07-28 16:32
I installed it, let's see in few hours

**Comment by Orfait** [comment] 2018-07-29 05:41
I stil get the issue : after a night, memory is at 97% (1,9GB) and swap is at 474MB.
So I made a heap dump and removed the binding.

Unfortunately, the Memory Analyzer Tool does not run on my computer. SO for now, heap dump is useless.

**Comment by martinvw** [comment] 2018-07-29 06:31
@lolodomo did you ever analyse a heapdump, there is a good chance that it shows the cause. If needed I can take look in the upcoming days.

@orfait do you have the full heap dump? So the the 1 gb + one. AFAIK it is not enabled by default, but it is the that can help us find the cause.

**Comment by lolodomo** [comment] 2018-07-29 06:31
What is strange is that the binding is not manipulating massive data. I can't understand how it could consume 2 GB of memory after 2 hours, even with your refresh rate for phone set to 10 seconds.

**Comment by lolodomo** [comment] 2018-07-29 06:34
No I never produced or analyzed heapdumps.

**Comment by Orfait** [comment] 2018-07-29 06:45
@lolodomo : not 2 hours, grow from 500MB to 2GB takes about 10 hours. But yes, that's fast.

@martinvw : strange, the file produced with dev:dump-create is only 2MB. Is it normal ?

**Comment by martinvw** [comment] 2018-07-29 06:53
That sounds more like a threaddump, see also

https://stackoverflow.com/questions/407612/how-to-get-a-thread-and-heap-dump-of-a-java-process-on-windows-thats-not-runnin

**Comment by lolodomo** [comment] 2018-07-29 07:43
What is strange too is that I am using this binding in my production environment (RPI 2) since ages and openHAB is still responding well even after several days.

**Comment by lolodomo** [comment] 2018-07-29 08:45
The architecture of the binding is very simple.
A thread is scheduled every XX seconds. It requessts data from the library and use them to set the state of the channels. These data include list of objects. Nothing is done in the binding to release these objects. I was expecting the memory to be released when the thread ends (or at least after Java Garbage Collector is run).
The library executes HTTP requests to get the data and builds objects from the JSON response. List of objects are sometimes built. As these data are delivered to the client requesting them through the return of a library public method, these lists are never removed inside the library itself.

PS: in fact, we have 3 different threads that handle different data.

**Comment by lolodomo** [comment] 2018-07-29 08:47
@Orfait : as my fix did not help, it could be better to do your memory dump with the official version of the binding.

**Comment by lolodomo** [comment] 2018-07-29 08:53
I could apply a removeAll to all lists of objects returned by the library once I finished to use them. But is it required ?

**Comment by lolodomo** [comment] 2018-07-29 09:16
Please try with this new version in which I added some list.clear(). 
[org.openhab.binding.freebox-2.4.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/2238629/org.openhab.binding.freebox-2.4.0-SNAPSHOT.zip)
I am curious to know if it helps or not.

**Comment by lolodomo** [comment] 2018-07-29 09:32
@Orfait : with your settings, we should have after 2 hours:
* 1*6*60*2=720 HTTP calls for the phone status
* 1*6*60*2=720 HTTP calls for the phone calls
* 13*2*60*2=3120 HTTP calls for the other stuff
That is a total of 4560 HTTP calls. Even if we count 10 KB per call, it leads to 45 MB after 2 hours.

**Comment by Orfait** [comment] 2018-07-29 09:48
I deployed the new jar.

In fact, I am running this binding for a long time now, also on a raspberry pi (before current setup).
One thing : I was running the snapshot version of OpenHAB, then moved to stable 2.3. But before that, I (wrongly) updated to 2.4 snapshot.

I will also check the rules, but it is the same : rules have not changed since a long time...

**Comment by lolodomo** [comment] 2018-07-29 09:53
It is possible that the jar I provided is only working well with openHAB snapshot. I don't know if there was some breaking API in the Eclipse SmartHome core framework since the stable v2.3 of openHAB.

**Comment by martinvw** [comment] 2018-07-29 09:57
> I could apply a removeAll to all lists of objects returned by the library once I finished to use them. But is it required ?

Normally garbage collection should take care of this (it should remove the whole list and it’s elements) maybe clearing the lists could change how long it takes but most likely the problem lies deeper.

A heap dump has the most value without additional cleaning code because it will make the problem easier to spot in the dump.

**Comment by lolodomo** [comment] 2018-07-29 10:07
Note that the library we rely on ( https://github.com/MatMaul/freeboxos-java ) is using these libraries:
* Apache HttpCore v4.3
* Apache HttpClient v4.3.1
* jackson-core-asl v1.9.13
* jackson-mapper-asl v1.9.13

Maybe it will not be a bad idea to move to a more recent version of the Apache HTTP components ?

**Comment by lolodomo** [comment] 2018-07-29 10:43
Consumming 1,5 GB in 10 hours, it will mean around 66 KB of data per HTTP call, all this data never released. That is too big. Even if there are few calls that can return a lot of data (list of phone calls or list of network devices), most of them should probably requires less that 1 KB).

**Comment by lolodomo** [comment] 2018-07-29 11:16
When I use the top command, I can see the %MEM is around 32% + this:
```
KiB Mem:    996452 total,   969404 used,    27048 free,    39780 buffers
KiB Swap:   102396 total,     9216 used,    93180 free.   394224 cached Mem
```
And the result of "free -m" gives:
```
             total       used       free     shared    buffers     cached
Mem:           973        946         26          1         38        384
-/+ buffers/cache:        522        450
Swap:           99          9         90
```
As already discussed in another issue, the used mem is very high but in fact there a lot of cached mem.
In my case, 450 MB is in fact available and not only 26 MB.

**Comment by lolodomo** [comment] 2018-07-29 11:20
As discussed here, the right cvommand to use to know the available RAM is: cat /proc/meminfo | grep '^MemAvailable:' | awk '{print $2/1024}' which gives 496.832 in my case.
https://github.com/eclipse/smarthome/issues/4490

**Comment by lolodomo** [comment] 2018-07-29 11:49
20 minutes later: 490.285

**Comment by Orfait** [comment] 2018-07-29 12:32
I installed back the original version. I am waiting until memory is full then make a heap dump.

**Comment by lolodomo** [comment] 2018-07-29 13:29
New value 490.652. Looks stable now.

**Comment by lolodomo** [comment] 2018-07-29 14:14
Using the command `cat /proc/<pid>/status` I can see that I have between 182 and 187 threads for my java process. Is it expected to have so many threads ?

**Comment by lolodomo** [comment] 2018-07-29 15:15
```
cat /proc/meminfo | grep '^MemAvailable:' | awk '{print $2/1024}'
489.512
```
```
top - 17:10:55 up 12 days, 16:26,  1 user,  load average: 0,23, 0,21, 0,18
Tasks: 109 total,   1 running, 108 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,4 us,  0,2 sy,  0,0 ni, 99,3 id,  0,0 wa,  0,0 hi,  0,1 si,  0,0 st
KiB Mem:    996452 total,   967672 used,    28780 free,    40112 buffers
KiB Swap:   102396 total,     9196 used,    93200 free.   384056 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
27989 pi        20   0  513492 327536  14620 S   1,6 32,9 383:58.63 java
```
```
free -m
             total       used       free     shared    buffers     cached
Mem:           973        944         28          1         39        375
-/+ buffers/cache:        530        442
Swap:           99          8         91
```
```
VmPeak:   513524 kB
VmSize:   513492 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:    327828 kB
VmRSS:    327628 kB
VmData:   493928 kB
VmStk:       136 kB
VmExe:         4 kB
VmLib:      9980 kB
VmPTE:       428 kB
VmPMD:         0 kB
VmSwap:        0 kB
Threads:        185
```

**Comment by lolodomo** [comment] 2018-07-29 15:30
It looks very stable at the java process level.
The available memory lost only 2 MB after 4 hours but it might be because of data logs rather than memory leak (even if my openHAB logs and rrdj data are saved on a network share).

At this stage, I doubt there is a memory leak in openHAB.
I am running the snapshot 1320 on a RPI 2.

**Comment by lolodomo** [comment] 2018-07-29 18:08
```
cat /proc/meminfo | grep '^MemAvailable:' | awk '{print $2/1024}'
489.594
```
```
top - 20:03:55 up 12 days, 19:19,  1 user,  load average: 0,35, 0,26, 0,21
Tasks: 109 total,   1 running, 108 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,4 us,  0,3 sy,  0,0 ni, 99,0 id,  0,1 wa,  0,0 hi,  0,3 si,  0,0 st
KiB Mem:    996452 total,   961480 used,    34972 free,    40340 buffers
KiB Swap:   102396 total,     9188 used,    93208 free.   377620 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
27989 xx        20   0  513492 327544  14620 S   2,6 32,9 417:27.81 java
```
```
free -m
             total       used       free     shared    buffers     cached
Mem:           973        942         30          2         39        372
-/+ buffers/cache:        530        442
Swap:           99          8         91
```
```
VmPeak:   514052 kB
VmSize:   513492 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:    327932 kB
VmRSS:    327608 kB
VmData:   493928 kB
VmStk:       136 kB
VmExe:         4 kB
VmLib:      9980 kB
VmPTE:       428 kB
VmPMD:         0 kB
VmSwap:        0 kB
Threads:        190
```
Still stable.

**Comment by lolodomo** [comment] 2018-07-29 20:08
That is weird that your Java process required 6 GB of memory !!!
How openHAB could require so much memory while mine only requires 500 MB ?
Did you change the default startup settings ?

**Comment by Orfait** [comment] 2018-07-29 20:19
I don't remember changing anything. I agree, that's weird...

I did a heap dump right now then disabled the freebox binding.

**Comment by Orfait** [comment] 2018-07-30 05:16
@martinvw : I sent you a link to download the heap dump via your personal website.

**Comment by Orfait** [comment] 2018-07-30 06:31
Yes, I will do it today.

**Comment by Orfait** [comment] 2018-07-30 06:44
I am not sure, but I can check : is there anything to take care inside rules concerning memory ? If I instantiate some variables, should I release hem ? How ?
For me, GC should do it...

**Comment by martinvw** [comment] 2018-07-30 06:47
No GC should indeed take care of it, as long as you don't keep references to for example a list of previous results. So if a (group of) object(s) has no reference anymore it can be removed by the garbage collection, but if there is at least one path remaining which addresses this object it will remain alive.

**Comment by martinvw** [comment] 2018-07-30 13:34
@Orfait I just found how I can disable Eclipse MAT's garbage collection behaviour, now I have the option to do more. Its related to the json conversions.

**Comment by martinvw** [comment] 2018-07-30 16:06
I just created a dump using:

https://stackoverflow.com/questions/407612/how-to-get-a-thread-and-heap-dump-of-a-java-process-on-windows-thats-not-runnin

And I can import it into eclipse MAT tool (and it has much more troubles importing it)

**Comment by Orfait** [comment] 2018-07-30 20:08
I used the same command.

I just created a new LXC container with full fresh install JRE8/Openhab and only freebox binding. Let's see how it is going !

**Comment by Orfait** [comment] 2018-07-31 05:48
The new LXC container does not show any abnormal memory usage.
I will continue the migration of other binding slowly.

**Comment by Orfait** [comment] 2018-08-03 06:26
So, I'm back to initial problem.

Since months, the memory usage is growing slowly. I opened this issue because the "growing rate" has terribly increased. After reinstalling everything on a new LXC container, I am back to the original growing rate".

After analyzing previous data, it seems that the data from "top" is sufficient. If you substract the memory used from the total, you get the memory available returned with /proc/meminfo.

Here is some data from actual install. I don't know how to interpret it. Nothing consumes memory according to the global memory usage increase.
So, I will let run for more days/weeks to see if it stills consume all RAM and eat some swap.
```
top - 08:49:40 up 1 day, 22 min,  1 user,  load average: 0.09, 0.31, 0.37
Tasks:  16 total,   1 running,  15 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.7 us,  2.2 sy,  0.0 ni, 97.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2097152 total,  1185024 free,   681504 used,   230624 buff/cache
KiB Swap:  4194304 total,  4194304 free,        0 used.  1415648 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  112 openhab   20   0 6007004 459116  19884 S   1.7 21.9  58:08.80 java
  110 nodered   30  10 1240404  98748  22912 S   0.0  4.7   0:23.82 node-red
```
```
Tasks:  16 total,   1 running,  15 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.8 us,  1.2 sy,  0.0 ni, 98.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2097152 total,  1157776 free,   696488 used,   242888 buff/cache
KiB Swap:  4194304 total,  4194304 free,        0 used.  1400664 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  112 openhab   20   0 6007004 459740  19884 S   2.7 21.9  62:25.65 java
23109 nodered   30  10 1174664 103704  23224 S   0.0  4.9   0:03.04 node-red
```
```
top - 16:17:45 up 1 day,  5:50,  1 user,  load average: 0.18, 0.15, 0.31
Tasks:  18 total,   1 running,  17 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.7 us,  0.7 sy,  0.0 ni, 98.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2097152 total,  1026052 free,   720568 used,   350532 buff/cache
KiB Swap:  4194304 total,  4194304 free,        0 used.  1376584 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  112 openhab   20   0 6007004 460744  19884 S   1.7 22.0  71:13.14 java
23109 nodered   30  10 1174664 104000  23224 S   0.0  5.0   0:06.45 node-red
```
```
top - 21:07:01 up 1 day, 10:40,  1 user,  load average: 6.87, 1.85, 0.78
Tasks:  18 total,   1 running,  17 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.0 us,  2.3 sy,  0.0 ni, 96.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2097152 total,  1001484 free,   744652 used,   351016 buff/cache
KiB Swap:  4194304 total,  4194304 free,        0 used.  1352500 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  112 openhab   20   0 6007004 461996  19884 S   1.7 22.0  82:41.31 java
23109 nodered   30  10 1175284 102948  23224 S   0.0  4.9   0:10.97 node-red
```
```
top - 08:24:25 up 1 day, 21:57,  1 user,  load average: 0.09, 0.10, 0.16
Tasks:  18 total,   1 running,  17 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.0 us,  1.0 sy,  0.0 ni, 98.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2097152 total,   942420 free,   802424 used,   352308 buff/cache
KiB Swap:  4194304 total,  4194304 free,        0 used.  1294728 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  112 openhab   20   0 6007004 466536  19884 S   1.7 22.2 109:28.25 java
23109 nodered   30  10 1175284 101020  23224 S   0.0  4.8   0:21.19 node-red
```

**Comment by lolodomo** [comment] 2018-08-03 07:17
Maybe a specific problem with your container or JRE  ? 

I will provide my stats after few days but my first results show no problem on a RPI 2 with raspbian and an Oracle JRE.

**Comment by lolodomo** [comment] 2018-08-04 08:11
6 days later.
```
cat /proc/meminfo | grep '^MemAvailable:' | awk '{print $2/1024}'
403.785
```
```
 free -m
             total       used       free     shared    buffers     cached
Mem:           973        915         57          2         39        185
-/+ buffers/cache:        690        282
Swap:           99          8         91
```
```
top - 09:47:19 up 18 days,  9:03,  1 user,  load average: 0,28, 0,25, 0,20
Tasks: 107 total,   1 running, 106 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,3 us,  0,3 sy,  0,0 ni, 99,1 id,  0,1 wa,  0,0 hi,  0,1 si,  0,0 st
KiB Mem:    996452 total,   937128 used,    59324 free,    40188 buffers
KiB Swap:   102396 total,     8776 used,    93620 free.   189960 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
23052 xx        20   0  529700 343456  14952 S   2,0 34,5   1474:51 java
```
```
VmPeak:   531748 kB
VmSize:   529700 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:    344908 kB
VmRSS:    343372 kB
VmData:   510432 kB
VmStk:       136 kB
VmExe:         4 kB
VmLib:      9980 kB
VmPTE:       462 kB
VmPMD:         0 kB
VmSwap:        0 kB
Threads:        192
```

This time, the java process seems to require more RAM than 6 days ago.

Globally my system (RPI2) has lost 87 MB of available memory in 6 days.
If this tendance is correct, it could be a problem for my system in 27 days !
But clearly openHAB (java process) is only responsible for 20% of the RAM I lost. Written files and the system is eating all the remaioning.

I will continue monitoring the tendance in the next days.

**Comment by lolodomo** [comment] 2018-08-04 10:02
Looking at the warnings in Eclipse, I discovered that Eclipse identifies a ressource leak at this line (webhook servlet):
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/webhook/WelcomeWebHookServlet.java#L88

**Comment by Orfait** [comment] 2018-08-04 10:59
I also use Netatmo binding.
I can disable it for testing.

**Comment by lolodomo** [comment] 2018-08-04 11:00
Are you using the webhook ?

**Comment by Orfait** [comment] 2018-08-04 12:29
I don't know what you mean, but I use the Netatmo binding pointed by your link.

**Comment by lolodomo** [comment] 2018-08-04 14:16
The webhook is a special feature for users having a Welcome Camera. If you don't know it, that means you are not concerned by the potential memory leak.
By the way, I have now fixed it.

**Comment by Orfait** [comment] 2018-08-12 06:55
After some days running, I rebooted the container and I am back to initial situation...
```
top - 08:53:59 up 19:19,  1 user,  load average: 0.64, 0.65, 0.67
Tasks:  18 total,   1 running,  17 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.7 us,  0.7 sy,  0.0 ni, 98.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2097152 total,    20672 free,  2050360 used,    26120 buff/cache
KiB Swap:  4194304 total,  3928720 free,   265584 used.    46792 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1305 openhab   20   0 6072432 1.887g   5816 S   2.3 94.3  43:43.46 java
  108 nodered   30  10 1239848  38708   3964 S   0.0  1.8   0:18.93 node-red
```

I have another container with similar config (for influxdb and grafana) without this issue.
Any help would be greatly appreciated...

**Comment by martinvw** [comment] 2018-08-12 07:48
Did you already try setting a max heap size? Because java is one of those things which will only free memory if needed. Maybe it won’t grow / will cleanup better if there is max heap size configured?

**Comment by martinvw** [comment] 2018-08-12 18:40
Note that the `-XX:MaxHeapSize=2074083328` does not match the `-Xmx=1024m` which you state, the params `XX:MaxHeapSize` & `Xmx` are equivalent.

**Comment by Orfait** [comment] 2018-08-12 20:47
@martinvw : yes, I was only checking the settings before modifying to 1024m.
First results are not good, memory usage is still growing very fast. I will wait until tomorrow to confirm it.

**Comment by Orfait** [comment] 2018-08-17 12:47
So, it is working with the Xmx parameter. In fact, java seems to set it to the total RAM amount by default : not a good idea.

Indeed, I am still watching for this disk usage.
I managed to find out using inotify :
`inotifywait -mr --exclude '/dev/pts' -e modify,attrib,close_write,move,create,delete /`
Seems to be related to Discovery result.

@lolodomo : As freebox binding is reporting all network devices discovered (even devices from several years ago... thank you free...), could you add a parameter to disable auto discovery ?

**Comment by lolodomo** [comment] 2018-08-20 07:41
22 days later, I can see that the memory used by the java process has clearly increased.
```
Tasks: 107 total,   1 running, 106 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1,4 us,  0,8 sy,  0,0 ni, 97,9 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem:    996452 total,   966532 used,    29920 free,    31116 buffers
KiB Swap:   102396 total,    10364 used,    92032 free.    59608 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
23052 xxx        20   0  627140 447108   5196 S   6,6 44,9   6054:07 java
```
%MEM is now 44.9.
During this period, I changed one binding but without stopping openHAB.
I have no idea if there is really a problkem in openHAB or if this is simply the way java is managing the memory.

**Comment by lolodomo** [comment] 2018-08-20 07:46
@Orfait : regading auto discovery, first we have to ask if it is possible to disable the auto discoveryu of a binding. Maybe it is already possible. If not, yes I could add a setting.

**Comment by lolodomo** [comment] 2018-08-24 15:01
@Orfait : done https://github.com/openhab/openhab2-addons/pull/3864

**Comment by Orfait** [comment] 2018-08-31 22:16
@lolodomo and @martinvw : I changed my ISP today. So bye bye Freebox.
But : since the exact instant I changed, the high disk usage dropped and memory stopped to grow. I also noticed a serious decrease in network traffic (even if it was low) and same with CPU usage.

I don't know if it was related to Freebox binding or something special in my setup, but clearly, Freebox binding had a special role in my issue.

I will wait tomorrow to post a screenshot of what I have seen.

**Comment by martinvw** [comment] 2018-09-01 06:50
@Orfait also a good way to resolve the problem 😉 

Maybe something related to the number of devices remembered by your modem or something like that which triggers the problems.

**Comment by Orfait** [comment] 2018-09-01 08:10
![capture d ecran 2018-09-01 a 10 06 56](https://user-images.githubusercontent.com/18164882/44943931-ce407880-adce-11e8-9a45-40cb6da02260.png)

You can see by yourself what I observed. The memory dropped when I rebooted, that's why there is a "delay" for it.

The question is : may I close the issue ? I think yes.
If you agree, I re-add the reference to Freebox binding before closing, if someone else have the same problem...

**Closed** 2018-09-03 17:10 UTC
