### ISSUE TITLE
Homematic 2.0 Binding does not support CUXD

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab2-addons#1314] opened 2016-10-11 02:47 UTC
All CUXD device in items files are not served by Homematic 2.0.
As example on the syntax for CUX device:.
Number Energie_bzg                  "Zählerstand v. Zähler [%.1f kWh]"  <energy> (Energie)                                                  {channel="homematic:HM-Sen-EP:ccu:CUX2700001:1#SUM"}
##

**Comment by kaikreuzer** [comment] 2016-10-11 06:54
@gerrieg Could you comment?

**Comment by gerrieg** [comment] 2016-10-12 07:02
Are the devices discovered and available in PaperUI's inbox?

To help, switch the binding to TRACE mode please and send me a full startup logfile.
```
<logger name="org.openhab.binding.homematic" level="TRACE" />
```

**Comment by Marty56** [comment] 2016-10-14 06:09
Sorry for being slow to respond. I will provide the requested trace during the weekend.

**Comment by Marty56** [comment] 2016-10-14 11:36
Hi Gerhard,

I have added some files to demostrate the issue.
For testing purpose I have reduce the number of homematic device to only two.
1. it is a normal homematic switch, 2. is a cux device with calculates the absolut humidity of a temperature sensor.

2. additionally I have added the event and openhab.log files in the ZIP File.

1. All cuxd device do not show up in the inbox in the paper ui.
2. Also the CuxD device I have explicitly defined in the homematic.items and things file never receive any data.
3. Additionally (this seems to be related to my OS which is Windows 10) I am receiving repeatingly a "Nano Server Time out" as you can see in the openhab.log.

Thanks for looking at is.



[homematic_test.zip](https://github.com/openhab/openhab2-addons/files/529366/homematic_test.zip)

**Comment by gerrieg** [comment] 2016-10-14 15:51
Hi Marty!

That's not a TRACE log, it's a normal INFO log. Make sure, the Homematic binding is in TRACE mode, the logfile must be much bigger.

NanoHTTPD:
The 'could not delete file' message is a annoying bug in NanoHTTPD on windows machines, maybe i replace the NanoHTTPD server or i am going to patch it. Needs more time to test.

**Comment by Marty56** [comment] 2016-10-14 17:44
Hi Gerhard,
If used "log:set debug org.openhab.binding.homematic" on the karaf prompt because I did not find the file to enter your proposed statement <logger name="org.openhab.binding.homematic" level="TRACE" />

Hope you find the required info anyway
[logs.zip](https://github.com/openhab/openhab2-addons/files/530113/logs.zip)

**Comment by gerrieg** [comment] 2016-10-14 17:47
Again, i need a trace! 
use log:set trace org.openhab.binding.homematic

**Comment by Marty56** [comment] 2016-10-14 18:23
Ok. Hope it is correct this time.
[logs.zip](https://github.com/openhab/openhab2-addons/files/530171/logs.zip)

**Comment by gerrieg** [comment] 2016-10-15 07:31
Yes, that's a trace log.

CUXD get's initialized but the listDevices method returns a empty list:
```
2016-10-14 20:20:18.312 [TRACE] [nal.communicator.client.XmlRpcClient] - Client XmlRpcRequest (port 8701):
<?xml version="1.0" encoding="ISO-8859-1"?>
<methodCall><methodName>listDevices</methodName>
<params></params></methodCall>
2016-10-14 20:20:18.322 [TRACE] [nal.communicator.client.XmlRpcClient] - Client XmlRpcResponse (port 8701):
<?xml version="1.0" ?><methodResponse><params><param><value><array><data></data></array></value></param></params></methodResponse>
```
Which version of CUXD are you using? Do the CUXD devices work in the CCU?

**Comment by Marty56** [comment] 2016-10-15 08:10
The CUID devices of course work in CCU and they also work using openhab 1.8.
The CUXD Version is Version 1.0

**Comment by gerrieg** [comment] 2016-10-15 08:40
Can you try to update to the latest 1.7? CUXD had some problems with the RPC methods in previous versions.
The 1.x binding uses another method to fetch the devices. The 2.x binding is Homematic-API compliant.

**Comment by Marty56** [comment] 2016-10-15 08:44
done upgrade to 1.7. no change. Would you like the traces again?

**Comment by Marty56** [comment] 2016-10-15 08:53
the RPCHOST=127.0.0.1 the CUXD damon is listening is the localhost so the CCU2 itself. 
I guess you are always to the RPCHOST on the CCU2 and this is then routing to the CUXD damon.

**Comment by gerrieg** [comment] 2016-10-15 10:13
You are right, i installed CUXD 1.7 and added one device. No way to fetch the device via XML-RPC, there is always a empty response.
I'll contact the CUXD developer...

**Comment by MHerbst** [comment] 2016-10-15 18:33
@gerrieg I have tried to replace NanoHTTP with Jetty HTTP server. Seems to be work without changing too much in XmlRpcServer. But I need to do some further testing. I will create a pull request as soon as I am satisfied with the implementation.

**Comment by gerrieg** [comment] 2016-10-16 07:22
@MHerbst 
Thank you, Jetty also would have been my first choice to replace NanoHTTP

@Marty56 
The CUxD developer told me, that he implemented XML-RPC with empty dummy methods and he don't add the necessary methods. CUxD only supports BIN-RPC. I must therefore use a double protocol. I need to take a closer look at how much work this is.

**Comment by Marty56** [comment] 2016-10-22 03:36
@Gerhard,

I am using the offline OH2 version and I am not sure how I can overwrite the already loaded old binding with the test binding you have provided.
Could please provide some instruction.

**Comment by Marty56** [comment] 2016-10-22 05:19
I have added the binding into the addon folder.
There seem to be still issues.
Hopefully the log file contains the trace this time ;-)

[logs.zip](https://github.com/openhab/openhab2-addons/files/545613/logs.zip)

**Comment by gerrieg** [comment] 2016-10-22 06:57
Thank you for testing and for the TRACE logfile ;-) Hmmm ... connection exception on the wired port. In this build i also changed the communicaton from XML-RPC to BIN-RPC (except HMIP). 
Please try this new build: [Download](https://drive.google.com/file/d/0Bw7zjCgsXYnHYm9tZUVyTmpzNHM/view?usp=sharing)
There is again XML-RPC and only for CUxD BIN-RPC.

**Comment by Marty56** [comment] 2016-10-22 07:39
I have tested it. It seems to fetch the first cux device and seems to fail on the second.
Also I have noticed that I cannot shut down OH with crtl D. I am just closing the windows now.

[logs.zip](https://github.com/openhab/openhab2-addons/files/545661/logs.zip)

**Comment by gerrieg** [comment] 2016-10-22 18:51
Found the bug that causes the error in your logfile, new version to [Download](https://drive.google.com/file/d/0Bw7zjCgsXYnHZUNZRGRneC1sN0E/view?usp=sharing)
Make sure the new version is loaded, the logfile should contain the message 'Testversion 1.0.0'

**Comment by Marty56** [comment] 2016-10-22 20:19
Hi Gerhard, 
I have copied your binding into addons but I do not see "testversion 1.0.0" in the log.
What else do I have to do to get the binding loaded?

**Comment by Marty56** [comment] 2016-10-23 04:31
I have resolved loading the lasted version.
It still throws a couple of error messages but seems to be able to read both cuxd channels.
So good progress.
[logs.zip](https://github.com/openhab/openhab2-addons/files/546175/logs.zip)

**Comment by Marty56** [comment] 2016-10-23 06:59
I have meanwhile extended my tests and discovered that only one of my CUXD Temperature devices is updated.

In things I have 

    Thing HM-WDS10-TH-O     CUX9002002
    Thing HM-WDS10-TH-O     CUX9002001
    Thing HM-WDS10-TH-O     CUX9002003
    Thing HM-WDS10-TH-O     CUX9002004

and accordingly in items the same channel definition.

**Comment by gerrieg** [comment] 2016-10-23 07:57
Fixed: [Download](https://drive.google.com/file/d/0Bw7zjCgsXYnHLS1GQkUzRWs5dVU/view?usp=sharing)
Testversion 1.1.0

Disabled virtual datapoint generation for some datapoints for CUxD devices. Since Homematic devices are emulated by CUxD, i can not add some of these virtual datapoints.

**Comment by Marty56** [comment] 2016-10-23 09:36
Not success. Same behavior as described above. Only one CuxD device is updated.
[logs.zip](https://github.com/openhab/openhab2-addons/files/546260/logs.zip)

**Comment by gerrieg** [comment] 2016-10-23 11:22
Accidentally closed?

In your logfile there are two Homematic related errors:
1.) Can't convert STRING value ...
This should be fixed with Testversion 1.2.0: [Download](https://drive.google.com/file/d/0Bw7zjCgsXYnHeGRVR3RqTHAtQm8/view?usp=sharing)

2.) Could not update thing ... Most likely because it is read-only.
Remove the things in your things file, you only need the bridge

Now, all errors should be gone. Let's see.

**Comment by Marty56** [comment] 2016-10-23 12:03
I have remove all things not. My things file now locks like that below:

Bridge homematic:bridge:ccu [ gatewayAddress="192.168.1.110"]
{ }
Hopefully this was the right understanding.
This resulted in not receiving anything. I will switch back to the old things file.

**Comment by gerrieg** [comment] 2016-10-23 12:08
yes, that's all you need. It works for me.

**Comment by Marty56** [comment] 2016-10-23 12:09
Not working: only one CuxD Device is being update.
See log:
Please not the log probably contains to starts. first with the new things file and then with the 
reverted.
Atleast with the reverted I am geting the standard items updated.

I will be out. Probably back in 5 hour. So take your time.
[logs.zip](https://github.com/openhab/openhab2-addons/files/546318/logs.zip)

**Comment by Marty56** [comment] 2016-10-24 06:18
Actually my statement that only one CuxD device is updated is wrong.
The value of this device seems to come from a persistence. So no CUXD device is updated.

If you look at the log only homematic devices are updated.
e.g. CUX9002001 is a device which is assigned to a temperature sensor. Everytime the homematic temperature sensor is updated, CUX9002001 should be updated as well which is never happening.

**Comment by gerrieg** [comment] 2016-10-24 15:58
This is heuristic programming :-)

OK, found another small bug, please use this version now: [Download](https://drive.google.com/file/d/0Bw7zjCgsXYnHOHpUeXhvZ3NyVVk/view?usp=sharing)
Testversion 1.3.0

According to your logfile, the CUxD daemon is not initialized and therefore no events are received. I think the daemon can not be reached during auto detection.
For this test, DEBUG logging is enough

The most important info in the logfile:
```
HomematicConfig[gatewayAddress=ccu,callbackHost=192.168.1.25,xmlCallbackPort=9125,binCallbackPort=9126,gatewayType=auto,rfPort=2001,wiredPort=2000,hmIpPort=2010,cuxdPort=8701,aliveInterval=300,reconnectInterval=0,timeout=15,socketMaxAlive=900]

HmGatewayInfo[id=CCU,type=CCU2,firmware=2.21.10,address=KEQ0112294,wired=true,hmip=true,cuxd=true]

Used Homematic transfer modes: WIRED:BIN_RPC, HMIP:XML_RPC, RF:BIN_RPC, CUXD:BIN_RPC
```
Make sure, that cuxd is true in the HmGatewayInfo. Otherwise the port can not be reached (firewall, CUxD settings, ...). You can see the used port in the HomematicConfig line (Default is 8701)

Regarding to the things file, i can not reproduce, my things file is empty, only the bridge is specified:
```
Bridge homematic:bridge:ccu [ gatewayAddress="ccu" ]
```

**Comment by Marty56** [comment] 2016-10-24 17:01
Hi Gerhard,
The bug is still existing. I have include the items file, the things file, the homematic.cfg and additionally the log file. I have no idea what you mean by 
"Make sure, that cuxd is true in the HmGatewayInfo".
I see no possiblity to configure the above. I would be great if you could check the related files.

[logs.zip](https://github.com/openhab/openhab2-addons/files/548473/logs.zip)

**Comment by gerrieg** [comment] 2016-10-24 17:32
I mean the three entries in your logfile:
```
HomematicConfig[gatewayAddress=192.168.1.110,callbackHost=192.168.1.116,xmlCallbackPort=9125,binCallbackPort=9126,gatewayType=auto,rfPort=2001,wiredPort=2000,hmIpPort=2010,cuxdPort=8701,aliveInterval=300,reconnectInterval=0,timeout=15,socketMaxAlive=900]
HmGatewayInfo[id=CCU,type=CCU2,firmware=2.21.10,address=KEQ0113546,wired=false,hmip=true,cuxd=false]
Used Homematic transfer modes: HMIP:XML_RPC, RF:BIN_RPC
```

In HomematicConfig the configured cuxdPort=8701. OK, that's the default port.
In the HmGatewayInfo there is cuxd=false, so the binding can not connect to the CUxD daemon in the CCU. Either CUxD is not configured correctly or something blocks the connection from 192.168.1.116 to 192.168.1.110 on port 8701
You can try to telnet to the CCU (from 192.168.1.116) via command line to test the connection:
```
telnet 192.168.1.110 8701
```

homematic.cfg: 
you can delete this file, not required for the OH2 binding

homematic.things:
The only entry you need is
```
Bridge homematic:bridge:ccu [ gatewayAddress="192.168.1.110"]
```

What you can post is the Status and Info window from the CUx-Daemon in the CCU.

**Comment by Marty56** [comment] 2016-10-24 17:55
Interestingly cuxd seems not be working properly.
This did not happen since I have installed it first time which is already 4 years ago.
Maybe this was caused by our experiments.
I have restarted CUX Demon and attached a text file containing the info and status window.
[cuxinfo.txt](https://github.com/openhab/openhab2-addons/files/548578/cuxinfo.txt)

**Comment by gerrieg** [comment] 2016-10-24 18:05
That's the binding:
```
  als RPC-Server(INIT) von 192.168.1.116:9126 (CUXD-ccu) angefordert!
```
but:
```
Oct 24 19:51:52 homematic-ccu2 daemon.err cuxd[2598]: sendbinrpc(192.168.1.116:9126) - write() No route to host
```
it seems, that the CUxD daemon in the CCU can not connect to openHab (192.168.1.116:9126)

I'm pretty sure, that the problem is related to the network.

**Comment by Marty56** [comment] 2016-10-25 01:54
For testing purpose I have switch of the windows firewall and it seem that you are right. CUXD Temperature sensor is transfering data!!!

Some minior issue remaining. If I am shorting the things file to just one line, e.g. 
Bridge homematic:bridge:ccu [ gatewayAddress="192.168.1.110"]

I do not see any reaction in OH2 and not data is transferred.

**Comment by gerrieg** [comment] 2016-10-25 14:45
👍  great that it's working now!
I created a PR with alle the changes: https://github.com/openhab/openhab2-addons/pull/1348

I also get theses errors, if i specify a Thing in the things file. Which exact version of OH2 are you using?

**Comment by Marty56** [comment] 2016-10-25 15:04
I am using Build #549.
Still struggling when moving the simple homematic.items file. That no items is being updated.

I have accept two items in the inbox and then those devices are updated. But they are using some generated name which does not fit to my names I have used in items file.
So a really unacceptable workaround would be to rename all items via Paper UI and repeat the procedure everytime the Paper UI data base for some reason is not working. This would be a bit pain in the butt.

Also really do not understand which the windows Firewall not accepting requestes on Port:9126.
I have checked my firewall settings and have given Java access to all ports using UDP and TCP. What else should I do?
I did not have to explicitly change the firewall settings before.

**Comment by gerrieg** [comment] 2016-10-25 16:10
@Marty56 
Aha, now i understand the problem. 

@kaikreuzer 
There is a issue in the Homematic binding i don't understand. If i start OH2 and add a thing from the inbox in PaperUI, everything works as expected.
If i don't use PaperUI and specify the Thing in the things file, i get this exception
```
2016-10-25 17:52:24.090 [WARN ] [.c.c.r.AbstractManagedProvider:138  ] - Could not update element with key homematic:HM-LC-Dim1T-Pl-2:ccu:JEQ0193707 in ManagedThingProvider, because it does not exists.
2016-10-25 17:52:24.090 [WARN ] [s.c.t.binding.BaseThingHandler:475  ] - Error while applying configuration changes: 'IllegalStateException: Could not update thing homematic:HM-LC-Dim1T-Pl-2:ccu:JEQ0193707. Most likely because it is read-only.' - reverting configuration changes on thing 'homematic:HM-LC-Dim1T-Pl-2:ccu:JEQ0193707'.
2016-10-25 17:52:24.093 [INFO ] [smarthome.event.ItemStateEvent:43   ] - Licht_Stehlampe updated to 15
2016-10-25 17:52:24.094 [INFO ] [s.event.ItemStateChangedEvent :43   ] - Licht_Stehlampe changed from NULL to 15
2016-10-25 17:52:24.097 [ERROR] [.o.b.h.h.HomematicThingHandler:110  ] - Could not update thing homematic:HM-LC-Dim1T-Pl-2:ccu:JEQ0193707. Most likely because it is read-only.java.lang.IllegalStateException: Could not update thing homematic:HM-LC-Dim1T-Pl-2:ccu:JEQ0193707. Most likely because it is read-only.
	at org.eclipse.smarthome.core.thing.internal.ThingManager$1.thingUpdated(ThingManager.java:237)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateConfiguration(BaseThingHandler.java:469)
	at org.openhab.binding.homematic.handler.HomematicThingHandler.initialize(HomematicThingHandler.java:101)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.thingUpdated(BaseThingHandler.java:183)
	at org.openhab.binding.homematic.handler.HomematicBridgeHandler$1.run(HomematicBridgeHandler.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

things file:
```
Bridge homematic:bridge:ccu [ gatewayAddress="ccu" ]
{
	Thing	HM-LC-Dim1T-Pl-2 	JEQ0193707
}
```

items file:
```
Dimmer Licht_Stehlampe		"Stehlampe [%d %%]" { channel="homematic:HM-LC-Dim1T-Pl-2:ccu:JEQ0193707:1#LEVEL" }

```
The exception occurs, when i'm [updating the configuration](https://github.com/gerrieg/openhab2-addons/blob/master/addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/handler/HomematicThingHandler.java#L101)
Why?

**Comment by kaikreuzer** [comment] 2016-10-25 18:30
> The exception occurs, when i'm updating the configuration
> Why?

Well, because the configuration is specified by the user already and a binding must not change this.
This might be solved through https://github.com/eclipse/smarthome/issues/1977, though.

**Comment by Marty56** [comment] 2016-10-25 18:34
@Gerhard,

I am using the offline OH2 version and I am not sure how I can overwrite 
the already loaded old binding with the test binding you have provided.
Could please provide some instruction.


------ Originalnachricht ------
Von: "Gerhard R." <notifications@github.com>
An: "openhab/openhab2-addons" <openhab2-addons@noreply.github.com>
Cc: "Marty56" <martin.klimke@outlook.com>; "Mention" 
<mention@noreply.github.com>
Gesendet: 21.10.2016 18:44:25
Betreff: Re: [openhab/openhab2-addons] Homematic 2.0 Binding does not 
support CUXD (#1314)

**Comment by gerrieg** [comment] 2016-10-26 06:10
@kaikreuzer 
OK, but why do i need a thing definition in this case? Without the thing the item is not updated.

@Marty56 
just copy the new file to /runtime/karaf/system/org/openhab/binding/org.openhab.binding.homematic/2.0.0-SNAPSHOT

**Comment by kaikreuzer** [comment] 2016-10-29 18:23
> OK, but why do i need a thing definition in this case?

Not sure if I understand this question. Does [this](http://docs.openhab.org/tutorials/migration#understanding-things) maybe answer it?

**Comment by gerrieg** [comment] 2016-11-01 08:47
The question is, is it a must to declare all things i want to use in a things file or is a item enough? 
A item to a thing that is not declared in the things file is not updated. I don't know if this is the correct behavior, or i forgot something to implement in the binding. I thought, a item 'activates' a thing automatically.

**Comment by Baumi1245** [comment] 2016-11-22 11:13
One or two weeks ago CUxD devices where shown.

But i don´t have them with the latest snapshot - i also updated CUxD to 1.8 and the CCU to 2.25.14.
So i can´t tell when they disapeared...

Should they be there?

**Comment by MHerbst** [comment] 2017-05-21 08:39
@Marty56 @Baumi1245 Is this issue still open? If yes can to retest it with the latest snapshot release?

**Comment by Marty56** [comment] 2017-05-23 05:44
@MHerbst 
I presently have no setup using the 2.0 binding. Potentially I only find time next weekend.
Sorry.

**Comment by Baumi1245** [comment] 2017-06-12 14:55
CUxD is working fine with the latest snapshot.

**Comment by martinvw** [comment] 2017-06-13 05:24
Thanks for reporting back

**Closed by martinvw** 2017-06-13 05:24 UTC
Labels: homematic
