### ISSUE TITLE
[miele] New 2019 Miele devices are not detected

### ISSUE THREAD

**Issue by penguin242** [openhab/openhab2-addons#5943] opened 2019-08-17 11:49 UTC
New 2019 Miele devices are not discovered.
The gateway is, but not the, in my case, new combi oven.

Log entry:
```
2019-08-17 10:31:45.171 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: Not valid value selector
java.lang.IllegalArgumentException: Not valid value selector
at org.openhab.binding.miele.internal.handler.MieleApplianceHandler.getValueSelectorFromChannelID(MieleApplianceHandler.java:85) ~[?:?]
at org.openhab.binding.miele.internal.handler.OvenHandler.handleCommand(OvenHandler.java:45) ~[?:?]
at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:233) ~[?:?]
at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:300) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
at java.lang.Thread.run(Thread.java:748) [?:?]
```

ID 001d63fffe020390#210 is not working

Model of device:
Miele XGW3000
miele:xgw3000:Miele_DGC7865_R01

## Expected Behavior
Discovery of Oven

## Current Behavior
No new device discovered. 
Manual adding the oven works, shows online, but no data can be read.
In fact, any manual added thing, with a random ID will show online

## Possible Solution
New UID's needed?

## Your Environment
Openhab 2.4 running on Ubuntu 18.04 with zulu java 8

**Comment by wborn** [comment] 2019-08-17 15:53
Maybe @kgoderis knows how to add support for this oven?

**Comment by kaikreuzer** [comment] 2019-08-17 19:25
Does your device communicate through Wifi or Zigbee? If the former, I would claim that this issue is a duplicate of https://github.com/openhab/openhab2-addons/issues/2359. If that's the case, I have good news: I was told that we will get a PR that addresses https://github.com/openhab/openhab2-addons/issues/2359 within the next days 😎 .

**Comment by penguin242** [comment] 2019-08-17 19:59
Very similar.

Would be great to have it working!

Thanks for the info.

**Comment by kaikreuzer** [comment] 2019-08-17 20:01
> Very similar.

Ok, then let me close this here as a duplicate of #2359.

**Closed by kaikreuzer** 2019-08-17 20:01 UTC
