### ISSUE TITLE
Exec Binding Number output channel 

### ISSUE THREAD

**Issue by Josar** [openhab/openhab2-addons#2891] opened 2017-11-27 12:17 UTC
using openhab 2 and the exec Binding i tried to follow the Documentation and used this as an example:
`Number APCExitValue {channel="exec:command:apc:exit"}`

but could not get it to run. Does this really work?

The output channel is defined as string so is it possible to assigne it to a number item and the conversion is done automatically?

[A Discussion ](https://community.openhab.org/t/items-with-channels-regex-and-jsonpath/35211)
[One more](https://community.openhab.org/t/jsonpath-transformation-get-sting-not-number/35952)
[Two more](https://community.openhab.org/t/help-jsonpath-transformation-drives-me-mad/35473)
[I stop here](https://community.openhab.org/t/how-to-store-output-from-exec-binding-as-numbers/24556)

**Comment by udo1toni** [comment] 2017-11-27 18:22
There is an open issue: https://github.com/openhab/openhab2-addons/issues/2149

**Comment by wborn** [comment] 2018-03-24 19:01
Closing this issue because it is a duplicate of https://github.com/openhab/openhab2-addons/issues/2149.

**Closed by wborn** 2018-03-24 19:01 UTC
