### ISSUE TITLE
[hueemulation] Some Alexa devices do not discover all tags

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab2-addons#4293] opened 2018-11-29 11:32 UTC
I updated from 1415 to 1445, excited to test #4216, and lost control of most of my items. None of my Items tagged as Switchable are being discovered. Sorry if this is not enough information, but I'm guessing this should be easily reproducible. If any more detail is required, please let me know. I am in the US and use 2nd gen Dots. This is [also being reported outside the US](https://github.com/openhab/openhab2-addons/issues/4293#issuecomment-449027517).

[community discussion](https://community.openhab.org/t/hue-emulation-items-with-switchable-tag-are-not-discovered/58250)

**Comment by davidgraeff** [comment] 2018-11-29 14:21
Group items are not supported because the hue emulation has no support for groups yet. Everything is in place but somebody need to sit down and finalise group support. It did work before by accident because the implementation didn't really care about item types.

**Comment by gdgeist** [comment] 2018-11-30 11:56
build 1446 and same experience.  Items tagged with "Switchable" not discovered.  "ColorLight" discovered as a non color light.  No tagged groups and read the community thread related to this.

**Comment by davidgraeff** [comment] 2018-11-30 13:21
> Alexa marks it as a Color Capabilities = None

Alexa does not natively (within the local network) support coloured hue bulbs. This is only possible via skills unfortunately. Try with hue compatible apps and it should be presented as a coloured bulb.

> Switchable Item

It works with my alexa (German firmware, which usually lacks behind the US version).

> Null pointer exceptions

That should not happen. What do you mean by "item that is not reachable"? An item does not have a reachable state. Did I miss something?

**Comment by gdgeist** [comment] 2018-11-30 23:58
Thanks.  The null pointer exceptions are for real world hue bulbs things that are "unreachable" i.e. hue bulb switched off by a hard wired light switch.

**Comment by dainosan** [comment] 2018-12-01 08:55
BUILD 1446 I have similar issues. reduced to 1 THING, 1 ITEM and still not being discoverable by the 3rd Gen echo Dot.

ITEM:
Switch         Luce_disimpegno_bagno        "Disimpegno Bagno"                 <light>          (gLivingRoom)                ["Lighing"]  { channel="openwebnet:bus_on_off_switch:mybridge:Luce_disimpegno_bagno:switch" }

 
rest API : 
[{"link":"http://192.168.1.22/rest/items/Luce_disimpegno_bagno","state":"OFF","editable":false,"type":"Switch","name":"Luce_disimpegno_bagno","label":"Disimpegno Bagno","category":"light","tags":["Lighing"],"groupNames":["gLivingRoom"]}]

**Comment by dainosan** [comment] 2018-12-01 09:38
this could help (or not)but i noticed that every time i change the configuration in paperUI
the config file 

/var/lib/openhab2/config/org/openhab/hueemulation.config

contains a "B" in the string

pairingEnabled=B"true"

**Comment by davidgraeff** [comment] 2018-12-01 10:34
You can use a REST addon for your favourite browser and verify that the xml generated by the hue emulation are correct. Alexa is also picky about the port nowadays, openhab should be running on port 80, or a reverse proxy forwards traffic from :80 to :8080

**Comment by dainosan** [comment] 2018-12-01 10:50
aware of the port forwarding and that is in place. 80 to 8080 via Iptables. 

i get data back from both  : 
http://192.168.1.22/api/config 
AND
http://192.168.1.22/api/description.xml

**Comment by gdgeist** [comment] 2018-12-01 12:46
> BUILD 1446 I have similar issues. reduced to 1 THING, 1 ITEM and still not being discoverable by the 3rd Gen echo Dot.
> 
> ITEM:
> Switch Luce_disimpegno_bagno "Disimpegno Bagno" (gLivingRoom) ["Lighing"] { channel="openwebnet:bus_on_off_switch:mybridge:Luce_disimpegno_bagno:switch" }
> 
> rest API :
> [{"link":"http://192.168.1.22/rest/items/Luce_disimpegno_bagno","state":"OFF","editable":false,"type":"Switch","name":"Luce_disimpegno_bagno","label":"Disimpegno Bagno","category":"light","tags":["Lighing"],"groupNames":["gLivingRoom"]}]

**Lighting is mispelled.**

**Comment by dainosan** [comment] 2018-12-01 12:56
no that was probably one of the latest copy and paste. this is how the item appears in rest API


[{"link":"http://192.168.1.22/rest/items/Luce_disimpegno_bagno","state":"NULL","editable":false,"type":"Switch","name":"Luce_disimpegno_bagno","label":"Disimpegno Bagno","tags":["Lighting"],"groupNames":["gLivingRoom"]}]

**Comment by gdgeist** [comment] 2018-12-01 13:11
@dainosan I was hoping it was an easy fix for you ;)

**Comment by gdgeist** [comment] 2018-12-01 13:38
> > Alexa marks it as a Color Capabilities = None
> 
> Alexa does not natively (within the local network) support coloured hue bulbs. This is only possible via skills unfortunately. Try with hue compatible apps and it should be presented as a coloured bulb.
> 
> >

@davidgraeff This one stumps me as I have a Hue hub and have never used the Hue cloud account i.e. Alexa/Echo has only ever been connected locally and before I deleted the pairing in order to use the hue emulation the color bulb worked just fine i.e. the only way Alexa would have discovered my color bulb was local discovery....

**Comment by davidgraeff** [comment] 2018-12-01 13:51
@gdgeist Maybe in non European firmware versions? I read about non color support in various forums and that Amazon is never intending to add support to the local hue support. The hue emulation is emulating a A14 extended color bulb from 2014, I think. My alexa is not recognising it as color bulb. If anybody knows what to emulate to make this work, I'd happy to make the necessary changes.

**Comment by davidgraeff** [comment] 2018-12-01 13:53
> no that was probably one of the latest copy and paste. this is how the item appears in rest API

It doesn't help to post the OH rest response. Alexa is using the hue emulation rest API under /api. You need to generate an api-key and then post /api/[api-key]/lights

**Comment by dainosan** [comment] 2018-12-01 14:15
we can figure this out.

here is the long output of the /api/[api-key]/lights

api key is created but nothing is returned to alexa 

{"1":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-1","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Disimpegno Bagno"},"2":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-2","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Bagno Ospiti"},"3":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-3","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Lavanderia"},"4":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-4","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Camera"},"5":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-5","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Cameretta"},"6":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-6","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Cabina Armadio"},"7":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-7","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Specchio Cabina Armadio"},"8":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-8","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Cucina"},"9":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-9","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Bagno Notte"},"10":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-10","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Specchio Bagno Notte"},"11":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-11","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Divano"},"12":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-12","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Tavolo Sala"},"13":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-13","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Led Divano"},"14":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-14","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Ingresso"},"15":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-15","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Disimpegno Scala"},"16":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-16","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Studio"},"17":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-17","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Balcone Studio"},"18":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-18","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Scala"},"19":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-19","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Corridoio"},"20":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-20","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Balcone Sala"},"21":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-21","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Balcone Cucina"},"22":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-22","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Balcone Bagno"},"23":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-23","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Balcone Bagno Notte"},"24":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-24","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Balcone Cameretta"},"25":{"state":{"on":false,"reachable":true},"type":"On/Off plug-in unit","modelid":"Plug 01","uniqueid":"a27e0501-03e1-4671-8a80-487d5cabc93f-25","manufacturername":"OSRAM","swversion":"66012040","friendsOfHue":true,"hascolor":false,"name":"Balcone Camera"}}

**Comment by ScottKinSF** [comment] 2018-12-02 17:32
I too have existing rules and items that use group items to control dimmer items in the same area. As noted by @5iver, the updated version of Hue Emulation breaks that functionality.

I have also noted that the commands ON and OFF when issued from Alexa to my dimmer items, no longer function the way they did before this update. The devices now receive a '1' or a '0' respectively, which my devices see as 1% and 0%, which is certainly not the desired behavior. Setting these dimmer items to a percentage value from 0 to 100% does work.

**Comment by davidgraeff** [comment] 2018-12-03 10:18
Please everyone test if switchables work for you with #4312 and #4313 applied. Please also perform the test with different Alexas (voice command in English might be something like: Alexa, discover new devices). I have the strong feeling that different Echo types support different sets of hue devices.

**Comment by gdgeist** [comment] 2018-12-05 03:47
2.4.0.201812042313     │ Hue Emulation Service

No devices discoverable at all.  I cleared the discovered devices in Alexa.  Cleared cache, upgraded, device pairing mode multiple times.

Ran out of time tonight.  Will see if anything useful can come from the logs

**Comment by davidgraeff** [comment] 2018-12-05 09:13
One of the commits made the main api endpoint (/api/user-name/lights) a 404. At the moment it does not work. I'm on this right now.

**Comment by davidgraeff** [comment] 2018-12-05 19:39
I have created PR #4324 to fix this and added a test bundle as well for catching breaking commits next time.

For Alexas that are not able to identify an OSRAM plug as a switchable, I have this workaround:

Go to the service configuration on Paper UI and change the tag for white lights to "Lighting, Switchable". This emulates all switchables as white lights, like the former code did.

**Comment by davidgraeff** [comment] 2018-12-08 19:37
![bildschirmfoto vom 2018-12-08 20-34-29](https://user-images.githubusercontent.com/66436/49689915-c3615680-fb28-11e8-8caf-490f79181727.png)

This is a screenshot from the Alexa app. You see devices appear two times. The echo dot finds them as "Royal Philips Electronics intelligentes Gerät" including switches. The echo finds them as as "Dimmable Light" and "Color Light" without switches. Summing this up: The local hue support is a mess, somehow.

**Comment by openhab-5iver** [comment] 2018-12-12 19:15
Alexa still cannot discover any Switchable tagged Items with S1459 using an Echo Dot in the US. The API shows them as OSRAM:

state |  
-- | --
on | true
reachable | true
mode | "homeautomation"
alert | "none"
type | "On/Off plug-in unit"
modelid | "Plug 01"
uniqueid | "105f4eff-156d-4535-a5c6-2511a57e494d-2"
manufacturername | "OSRAM"
productname | "On/Off plug"
swversion | "V1.04.12"
hascolor | false
name | "Family Room TV"
config |  
archetype | "classicbulb"
function | "functional"
direction | "omnidirectional"
capabilities |  
certified | false
streaming |  
renderer | false
proxy | false
control | {}

**Comment by openhab-5iver** [comment] 2018-12-12 21:01
> This particular issue is of category "cannot fix" for US citizens. 

OK... thank you for the info. I've tried adding Switchable to the 'White item tags', but they were still not discoverable. I'll change all of my Switchable to LIghting for now. ColorLighting did also show up.

> You can help by finding out if any ZigBee plugs work with US Alexa firmware in a local network environment. Depending on the local different plugs could be emulated.

I'll help in any way I can! I have a Zigbee plug, but I suspect you are asking me to pair it with an Echo Plus, which I do not own. Did I read you right? I could also setup [ha-bridge](https://github.com/bwssytems/ha-bridge) again (used this before OH hueemulation), if it would have anything that would help. Or maybe there is something in their code that could help? Although, I do not recall how they were being identified by Alexa... they may have all been dimmable lights.

**Comment by davidgraeff** [comment] 2018-12-12 21:11
Did your plug work with ha-bridge? Then we only need to find out what device is emulated.

**Comment by openhab-5iver** [comment] 2018-12-12 21:57
> Did your plug work with ha-bridge? Then we only need to find out what device is emulated.

Everything I have with the tag Switchable worked prior to your changes, but IIRC, they all showed up as Dimmable Light in the Alexa app.

> Even worse. I'd ask you to pair it with an original Hue Bridge and find out if the plug is recognised by Alexa.

Nope... hub here. Do you have a list of possible devices? I looked on the Hue developer site, but didn't spot one. If you have one, I can build the bundle and try them out... maybe we can find one that works. For now I have everything set to Lighting, which seems to be working... except 3 of 84 devices didn't show up... just not sure which ones.

**Comment by davidgraeff** [comment] 2018-12-12 22:11
I only own the Osram Plugs. Soon there will be IKEA wall plugs available as well in Germany, but I doubt that newer devices are of any help here. 

> Everything I have with the tag Switchable worked prior to your changes, but IIRC, they all showed up as Dimmable Light in the Alexa app.

Yes of course that was the only device that the old hue code could emulate, which resulted in Alexa thinking that she could turn a wall plug to 50% brightness.

There must be a Zigbee wall plug from around 2015 or so on the American market that was Alexa compatible at that time until Amazon stopped the development of the local Hue bridge support.

**Comment by openhab-5iver** [comment] 2018-12-12 22:34
The old SmartThings plug (actually Centalite 4257050-RZHAC) fits that description. I have one too.

**Comment by davidgraeff** [comment] 2018-12-12 23:15
I do not have a Philips developer/forum account and not too keen on getting one. Could you copy the important parts over if possible?

Osram <> Sylvania? Who came up with this. The smart things plug sounds like a good idea. I need the hue rest API response for this device. If it works in Europe too I replace the Osram device entirely.

**Comment by davidgraeff** [comment] 2018-12-12 23:36
> How do you read the API docs without an account?!

Simple. I don't read them on the Philips site. Google cache has most of the pages. If I stumble over an issue that can only be solved with the API docs I will register, but why bother if it works without. 

> That requires the hub?

Yes I'm afraid so. Alternatively it can be found on the internet

**Comment by gdgeist** [comment] 2018-12-13 13:51
I have a HUE developer account but you wont find the Sylvania response - you need someone with an actual Sylvania outlet tied to a hue hub for that.  Ikea Tradfri Outlets.....just skip and buy SONOFF/WEMO.
@openhab-5iver You said your color bulb comes up color now - mine doesnt - my category description shows up as Color Light but no color capabilities in the Alexa app.
As usual @davidgraeff -Thanks!

**Comment by ScottKinSF** [comment] 2018-12-13 14:51
I don't know if it helps, but the following PDF provides the current information on Hue supported devices.
[Philips Hue Supported Devices.pdf](https://github.com/openhab/openhab2-addons/files/2676477/Philips.Hue.Supported.Devices.pdf)

**Comment by davidgraeff** [comment] 2018-12-13 15:33
Interesting document. Unfortunately no example for an On/Off device.

**Comment by ngrodum** [comment] 2018-12-17 14:46
@kaikreuzer  Why is this issue closed? For me this is still an issue (in the 2.4 release version).

**Comment by kaikreuzer** [comment] 2018-12-17 14:52
It was auto-closed because https://github.com/openhab/openhab2-addons/pull/4339 claimed that it fixed it.

**Comment by davidgraeff** [comment] 2018-12-17 15:05
The title need to be changed and be more specific. It works for Europeans and doesn't for US citizens, so it is untestable and not reproducible for a good part of the developers.

**Comment by openhab-5iver** [comment] 2018-12-17 15:39
@davidgraeff , is the tiel better for you? If you'd like it more specific, please let me know what you suggest.

**Comment by davidgraeff** [comment] 2018-12-17 15:53
@openhab-5iver Thanks. Could you reopen the issue?

**Comment by ScottKinSF** [comment] 2018-12-17 15:56
Last week I ordered a used SYLVANIA SMART+ ZigBee Indoor Smart Plug, which, although there are many reports that the newer version will not pair with a Hue hub, I thought I would try based on a handful of reports that, with the right procedure, pairing can be successful.

I found a relatively cheap one on ebay that I should receive this week. I'll let you know what I find.

**Comment by xsnrg** [comment] 2018-12-18 01:35
This is still broken in the release version 2.4.0, which I believe we all know.  If I might summarize where we are, hue emulation used to work for people in the US because a defect (in the eyes of the dev team) allowed it to work.  This defect was fixed, along with some new code that allowed better handling of color lights. In fixing this defect, the US based(1) Alexa devices no longer recognise the hue emulator hub and therefore do not find any exposed devices.  

1) above - is this generally accepted?  Hue emulation works with non-US Alexa devices for everyone that has tried it?

If the above is the case, and we understand the defect that was changed, would it be possible to introduce code that is no longer considered a defect that allows the US devices to work again?  I am not asking to have the same defect re-introduced to the code, but I am asking if what we know about the defect that was fixed can be used to allow US devices to again do device discovery in some way?

Thank you for all the time and effort that has gone in to making this better, but my family wants Alexa back.

Jim

**Comment by openhab-5iver** [comment] 2018-12-18 02:16
As a workaround, change your tags to Lighting, or in the Hue Emulation config, add Switchable to the White item tags. This will provide the exact same functionality as before, since all Items were added as DimmableLight. More info in the forum discussion.

**Comment by davidgraeff** [comment] 2018-12-18 09:12
Could someone add this workaround and a little description of the current situation to the binding readme? 

Jim: I guess you cross read related topics and confused some subjects here. The hue emulation itself works for US citizens, too. It just differentiates exposed device types. And one of the emulated types, the wall plug, happen to not exist in the US so Alexa does not recognise it.

**Comment by openhab-5iver** [comment] 2018-12-18 19:17
> Could someone add this workaround and a little description of the current situation to the binding readme?

I'll add this to the readme, but do you think it would be best to wait until @ScottKinSF reports back his findings, on the chance we find a device type that works in the US?

**Comment by ScottKinSF** [comment] 2018-12-18 22:02
I've done some more research and came across [this](https://www.smartplus.community/t/how-to-reset-your-smart-plug/48/3) and [this](https://iconnecthue.com/supported-devices/#osram), neither of which sounds very promising. The device is used, so it's possible I'll luck out and get the earlier version, we shall see.

**Comment by xsnrg** [comment] 2018-12-19 01:51
> 
> Jim: I guess you cross read related topics and confused some subjects here. The hue emulation itself works for US citizens, too. It just differentiates exposed device types. And one of the emulated types, the wall plug, happen to not exist in the US so Alexa does not recognise it.

While it is true, I seem to have read nearly everything nearly everywhere, and have tried most of the workarounds, I only this evening seem to have stumbled across a combination that allowed the  insteon devices to be discovered.  My items file contains "Switchable", switch item tags "Lighting", and White item tags "Switchable".  They all appear as "Dimmable Light" now, but they work.

**Comment by davidgraeff** [comment] 2018-12-20 14:05
@cee-dee Which makes it super confusing now. Does your Alexa enabled device (you did not specify which one you have) support colors?

**Comment by davidgraeff** [comment] 2018-12-20 15:03
Yes I'm referring to this. I have three different types of Echos. The dot 1st gen and normal echo 2nd gen perform different discoveries and the Amazon Alexa website picks a random device to perform the discovery. One of the devices finds color and switchable devices, the other only dimmable ones. So yes, there are different firmware versions even in one country.

Please perform the discovery with different devices.

**Comment by davidgraeff** [comment] 2018-12-20 15:45
Amazon is not officially supporting Hue bridges locally, are they?

**Comment by cee-dee** [comment] 2018-12-20 16:07
I've checked discovery with all of my Echo devices: The large Amazon Echo discovers only those devices which are directly exposed through the Hue Bridge, all other Echo Dots discover all devices, including those exposed by openHAB. The web version via alexa.amazon.com discovers all devices, too. (Tests have been performed using the tags "Lighting,Switchable" configured in the binding.

**Comment by davidgraeff** [comment] 2018-12-20 16:18
> Tests have been performed using the tags "Lighting,Switchable" configured in the binding.

Can you assign "Lighting" to the Coloured bulb and test if coloured bulbs are supported by your Echos?
And test "Switchable" as well with the different Echos, that would help.

**Comment by cee-dee** [comment] 2018-12-20 16:49
@davidgraeff : Can you elaborate on the exact scenario which I shall test? I assume you want this:
a) remove the configuration "Switchable" from the white tags setting
b) editing one my items-file to assign the tag "Lighting" to a single light
c) re-discover the items with web service, Echo and Echo Dot separately
d) verify if the adjusted item is discovered with a certain tag

Is this basically what you want? If so, which tags should be reported?

I don't have a clue what I should test regarding Switchable, since step a) will cause the items to be not discovered.

**Comment by davidgraeff** [comment] 2018-12-20 17:00
@cee-dee  Exactly. I like to know if any/some devices of your setup support colors and switches and how they discovered devices are reported. The label differs for me depending on the discover-performing device.

@openhab-5iver  Regarding to the Amazon document

> Philips Hue devices can connect to Alexa with the V1 Hue Bridge (circle-shaped). To connect these devices, say, "Discover devices," and then press the button on the bridge.

I'm emulating a 2nd gen bridge and it works for me and for you.

> Note: Your Echo device can only be associated with one Phillips Hue bridge at a time.

I have two emulated bridges and both are recognised. But maybe they mean, that each Echo can associate to one bridge.

> Phillips Hue devices with the V1 Hue Bridge can only turn on/off or brighten lights on compatible Echo devices.

Color and switches are working for me. But that document might be for the US market of course. In the German help center there is no such document at all.

All in all I think this is a relict and nobody noticed that the document is outdated by now. It would be really good to know where Amazon is heading to and what their plans are for local protocols.

**Comment by openhab-5iver** [comment] 2018-12-20 18:00
> I'm emulating a 2nd gen bridge and it works for me and for you.

That stands out to me. It was my understanding that a v2 bridge required the Hue skill to work with Alexa. Is this just a configuration setting (like firmware version), or would changes be needed in the API calls to emulate a v1? I ask, because I could try making the changes and testing it out to see if this helps at all.

**Comment by ScottKinSF** [comment] 2018-12-20 19:12
5iver, the following statement from the 2nd link you provided above contradicts the statement from your 1st link about Alexa local control only being available for Philips Hue V1 bridges:

> Note: Basic lighting functionality (on / off / dimming) is available without the Smarthome skill and is compatible with Philips Hue V1 (round) and V2 (square) bridges.

I think David is right, the information in the 1st link is out-of-date.

**Comment by openhab-5iver** [comment] 2018-12-20 19:30
> the following statement from the 2nd link you provided above contradicts the statement from your 1st link

I guess I can see that, but I was taking it to mean that this functionality is only available/compatible with a v1 bridge. But this is must be outdated (or incorrect), if hueemulation is emulating a v2 bridge. I'm tempted to call in and ask...

**Comment by davidgraeff** [comment] 2018-12-21 00:10
The Alexa support team is required to say whatever the company policy is. And if the tech team is slowly starting to fade out local protocol support, the support will always tell you to use the skill of course.

We need to find out what still works. I have already learned to add as section to the readme telling people to try all different Alexa devices to perform discovery and to add all tags to the dimmable bulb if color and plugs are not recognized.

**Comment by ScottKinSF** [comment] 2018-12-21 20:58
Update on the _SYLVANIA SMART+ Smart Plug_:

I received the device this afternoon and have tried numerous times to pair it with my Hue Hub V1 without success. It appears to use a ZigBee HA 1.2 profile rather than the ZLL profile required for compatibility with a Hue Hub.

I would still like to hear from anyone in the US who has one of the older SYLVANIA Lightify versions of this device paired with their Hue Hub. I think I will post an inquiry on one of the Hue Developers forums.

**Comment by gdgeist** [comment] 2018-12-23 13:13
So trying to understand where I could instrument this in order to cure my ColorLight issue and this Switchable thing.
The discovery exchange questions i have:

1. Initiate discovery from web/app/device
2. Since there isn't a "skill" involved - discovery must ask the Hue hub for a current list of devices.
2a. web/app initiated:do all devices devices ask the known hue bridge for the list or is one chosen randomly, ranked?
2b. device initiated: does it still call amazon and ask for the hue token/url for the action or does it have this stored locally?

Answers here would help me understand where to start sniffing the exchange.

**Comment by davidgraeff** [comment] 2018-12-23 14:04
> 2a. web/app initiated:do all devices devices ask the known hue bridge for the list or is one chosen randomly, ranked?

One random device.

> 2b. device initiated: does it still call amazon

An Echo stores its Hue bridge API key locally. It is not stored anywhere at Amazon. Each Echo creates its own Api Key. That's why you usually need to put your bridge into pairing mode if you have multiple Echos even if you have performed a discovery before. A random Echo that does not have an API key yet, could be chosen to perform the request to the Hue bridge.

**Comment by DubZyy** [comment] 2018-12-28 16:54
Same issue here for another german person. I'm running different echo dot v2 and v3. Workaround with hue emulation config does work, but only for switchs. I couldnt manage my roller shutter to work with percentages like "alexa, open roller shutter 60%"... that's very disappointing that such changes got implemented in stable releases :/

**Comment by VitoDeCarlo** [comment] 2019-01-16 06:11
I'm also unable to use Alexa to control the color of my lights (here in the U.S.).  I cannot use a direct connection between Alexa and Hue, as I need Alexa to control my Z-Wave devices as well (and I use Google Home to control my Hue lights, also).  So this puts me in the situation of not being able to control the color with Alexa for my 60 or so Hue lights on two Hue bridges.  Of of my Alexa devices are the Echo Dot v2.

**Comment by davidgraeff** [comment] 2019-01-16 06:43
Google Home supports local Hue bridges (and hue emulation therefore) as well. Was a bit more tricky if I remember correctly, they also prefer the cloud connection of course.

There is nothing we can do if Amazon is not supporting certain features like color on all their devices.

**Comment by ersingencturk** [comment] 2019-01-22 23:09
I'm using misc-hueemulation - 2.4.0 

item defined as:

`Rollershutter LivingRoom_Shutter3 "Kitchen Curtain" <rollershutter>(LivingRoom, gShutter) ["Switchable"]   { channel="knx:device:bridge:generic:LivingRoom_Shutter3" }`

But It's not visible in http://192.168.1.100/api/discovery hence alexa not finding it.

Is there a workaround ?

**Comment by davidgraeff** [comment] 2019-01-22 23:19
Yes. Using OH 2.5M1 :)

**Comment by davidgraeff** [comment] 2019-01-22 23:30
There is not much that happened from OH2.4 to OH2.5M1. It is relatively safe to just upgrade.

But you can always just download the "Milestone Add-ons" offline bundle and extract the `kar` file (it's a normal zip file) and and put the correct `.jar` file into your addons directory. Up to you.

**Comment by DubZyy** [comment] 2019-01-22 23:32
Workaround  is to setup the item as dimmer instead of rollershutter

**Comment by ersingencturk** [comment] 2019-01-22 23:46
thanks for your fast responses.will try both

**Comment by davidgraeff** [comment] 2019-02-09 16:10
Closing, because we have no control over Amazon and their Echo support for local Hue bridges.

**Closed by davidgraeff** 2019-02-09 16:10 UTC
Labels: won't fix

**Comment by openhab-5iver** [comment] 2019-02-09 23:16
For completeness, Amazon claims to only support V1 Hue hubs without a skill. This service was "upgraded" to emulate a V2 hub, but the features that were added are unusable. Previously, the Switchable and Lighting tags did the same thing. That was changed, and the Switchable tag no longer works. ColorLight will turn on/off the light, but color and temperature cannot be changed. Currently, only the Lighting tag works properly.
