### ISSUE TITLE
[Homematic] HM-Disp-EP-WM55 - E-Paper-Display - no supported thing

### ISSUE THREAD

**Issue by turbolift** [openhab/openhab2-addons#1874] opened 2017-02-09 09:28 UTC
I tried to get the homematic HM-Disp-EP-WM55 (Firmware 1.1) working. At boot-up i got the following warning. 

2017-02-09 10:03:57.405 [WARN ] [ternal.communicator.HomematicGateway] - Can't load device with address 'NEQ1462966' from gateway 'c7b4ed9e': -3 Unknown paramset (sending getParamsetDescription()
NEQ1462966:4
VALUES
)

If I start to scan for new items for the homematic binding I get the same warning.

2017-02-09 10:14:49.256 [WARN ] [ternal.communicator.HomematicGateway] - Can't load device with address 'NEQ1462966' from gateway 'c7b4ed9e': -3 Unknown paramset (sending getParamsetDescription()
NEQ1462966:4
VALUES
)

This is the view to my homematic-ccu2

![2017-02-09 10_19_24-homematic webui](https://cloud.githubusercontent.com/assets/2904717/22776919/dab531f6-eeb1-11e6-9771-d71de2de452a.png)

trace.log

[trace.zip](https://github.com/openhab/openhab2-addons/files/763352/trace.zip)

**Comment by overrunner** [comment] 2017-02-09 09:32
Same here. 
An integration would ne nice.

**Comment by MHerbst** [comment] 2017-02-10 19:17
@gerrieg I have checked the description properties files but did not find this device. So probably this is the cause of this problem.

**Comment by gerrieg** [comment] 2017-02-11 11:18
Thank you for the trace log. This is another bug in the CCU firmware 😬. Instead of sending the description of the channel parameters, the CCU sends a error. I will try to find a workaround and let you know.

@MHerbst 
The missing description is only for the device name, it has nothing todo with the functionality, but i will add the description too.

**Comment by gerrieg** [comment] 2017-02-12 16:39
I added a workaround with the linked PR. I simulated the exception with my devices and it works for me. Once it has been merged, please let me know if it works for you too. If it does not work, please post a TRACE log again.

**Comment by turbolift** [comment] 2017-02-12 23:33
@gerrieg : I build your PR (https://github.com/openhab/openhab2-addons/tree/5a9110681362674482434f7479d42c64f86f861f) and put the resulting binding in /usr/share/openhab2/addons/

Finally that thing is showing up in my inbox.

![2017-02-13 00_23_24-filme tv](https://cloud.githubusercontent.com/assets/2904717/22867158/bab33d02-f182-11e6-9af4-6ced48520dc8.png)

But in my opinion, something is still wrong:

![2017-02-13 00_28_33-neue benachrichtigung](https://cloud.githubusercontent.com/assets/2904717/22867205/ca198750-f183-11e6-881e-eae9200ed47a.png)

[openhab.zip](https://github.com/openhab/openhab2-addons/files/769736/openhab.zip)

**Comment by turbolift** [comment] 2017-02-13 15:41
I tried to dig into the problem and analyzed the log:

The Device has the address NEQ1462966	
	
	{
		ADDRESS=NEQ1462966
		AVAILABLE_FIRMWARE=1.1
		CHILDREN=
		[
			NEQ1462966:0
			NEQ1462966:1
			NEQ1462966:2
			NEQ1462966:3
			NEQ1462966:4
			NEQ1462966:5
			NEQ1462966:6
			NEQ1462966:7
			NEQ1462966:8
		]
    ...
	}

The Device has 9 Children, amongst others NEQ1462966:3, NEQ1462966:4

The Child with the address NEQ1462966:3 has the paramsets MASTER and VALUE
The Child with the address NEQ1462966:4 has only the paramsets MASTER

	{
		ADDRESS=NEQ1462966:3
    ...
		PARAMSETS=
		[
			MASTER
			VALUES
		]
		PARENT=NEQ1462966
		PARENT_TYPE=HM-Dis-EP-WM55
    ...
		}
	{
		ADDRESS=NEQ1462966:4
    ...
		PARAMSETS=
		[
			MASTER
		]
		PARENT=NEQ1462966
		PARENT_TYPE=HM-Dis-EP-WM55
    ...
		}

For the address NEQ1462966:3 the MASTER and VALUES ParametersetDescription are being queried and successfull results are being returned.
For the address NEQ1462966:4 the MASTER and VALUES ParametersetDescription is being queried, but only for the MASTER a successfull result is being returned. The ParametersetDescription for VALUES is "Unknown paramset"

But as earlier mentioned the address NEQ1462966:4 has no VALUES

**Comment by gerrieg** [comment] 2017-02-13 16:04
I analysed your trace logfile and i think i know what i have to change, will fix it soon

**Comment by gerrieg** [comment] 2017-02-13 18:44
I've updated my PR now. Because i don't have this device, i can not reproduce the problem. So my changes are assumptions.

Therefore, @turbolift thanks for testing and your trace logs. They are very helpful.

**Comment by turbolift** [comment] 2017-02-13 21:34
@gerrieg : Thanks again for your effort. I build your PR (https://github.com/openhab/openhab2-addons/tree/60c753ff114860af2aab818aaab5b2edf337ed2a) and put the resulting binding in /usr/share/openhab2/addons/

Now the Status is online.

![2017-02-13 22_17_08-neue benachrichtigung](https://cloud.githubusercontent.com/assets/2904717/22903811/4bfa7c78-f23a-11e6-8130-3c3ac9eb596d.png)

I tested the switches on PRESS_SHORT and everything works fine.

[openhab-trace.zip](https://github.com/openhab/openhab2-addons/files/772444/openhab-trace.zip)

I think this issue can be closed.

An once again. Thanx.

**Comment by maagges** [comment] 2017-02-14 10:00
Hello,
Do you know if this workaround will also make the hm-dis-wm55 working? It is not listed in the inbox.
Thanks,
Markus

**Comment by gerrieg** [comment] 2017-02-14 15:58
@maagges I think so, please try it and let me know

**Comment by turbolift** [comment] 2017-02-18 12:21
Submitting text to the display is also working.

**Comment by maagges** [comment] 2017-02-18 13:49
@gerrieg I would like, but I got stuck on installing the Binding. This is what I did:
- I compiled your source
- uninstalled the homematic binding (I am using the 2.0 release)
- Moved the jar to the addons folder
- when I check the bundle list in Karaf, it shows me the new one as "active", but Paper UI shows the binding of the 2.0 release.

What am I doing wrong?

**Comment by turbolift** [comment] 2017-02-18 14:51
It's important to check the file rights so that the openhab user can access the file.

pi@openhab:~ $ ls -la /usr/share/openhab2/addons/
insgesamt 284
drwxr-xr-x 2 openhab openhab   4096 Feb 13 00:17 .
drwxr-xr-x 5 openhab openhab   4096 Feb  7 19:16 ..
-rw-r--r-- 1 openhab openhab 275943 Feb 13 21:40 org.openhab.binding.homematic-2.1.0-SNAPSHOT.jar
-rw-rw-r-- 1 openhab openhab     70 Feb  5 13:57 README

**Comment by MHerbst** [comment] 2017-02-18 17:31
@turbolift can you close this issue if everything is working now.

**Closed** 2017-02-18 18:23 UTC

**Comment by maagges** [comment] 2017-02-19 09:54
thanks @turbolift, openhab seems to use the compiled binding now. It does not show up in Paper UI (there is just the 2.0.0 binding as "not installed"), but all homematic device work. Except the hm-dis-wm55. Auto discovery does not find it, when I add it manually via "things"-file, It shows up as "UNINITIALIZED - HANDLER_MISSING_ERROR". I will attach a trace log.
[openhab.log.zip](https://github.com/openhab/openhab2-addons/files/785705/openhab.log.zip)

**Comment by gerrieg** [comment] 2017-02-19 10:16
You are still using the old jar file
```
2017-02-19 10:45:00.743 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcRequest:
getParamsetDescription()
NEQ0103719:3
VALUES

2017-02-19 10:45:00.744 [TRACE] [al.communicator.client.SocketHandler] - Returning socket for port 2001
2017-02-19 10:45:00.747 [TRACE] [nal.communicator.client.BinRpcClient] - Client BinRpcResponse:
{
	faultCode=-3
	faultString=Unknown paramset
}

2017-02-19 10:45:00.749 [WARN ] [ternal.communicator.HomematicGateway] - Can't load device with address 'NEQ0103719' from gateway '487f79cb': -3 Unknown paramset (sending getParamsetDescription()
```

**Comment by maagges** [comment] 2017-02-19 20:50
Thanks, for the hint, @gerrieg! I copied the wrong compiled jar. With the correct one from your PR, the HM-Dis-WM55 works. Thanks a lot!

**Comment by overrunner** [comment] 2017-03-05 17:18
@turbolift key events work great. How did you set text from openhab? PaperUI does not have a possibility for ghat, right?

**Comment by MHerbst** [comment] 2017-03-05 17:33
You will probably have to write a rule to set the text. I can tell more next week when I get this device.

**Comment by turbolift** [comment] 2017-03-05 18:36
@overrunner: the script ist NOT bugfree

[epaper.zip](https://github.com/openhab/openhab2-addons/files/819617/epaper.zip)

**Comment by overrunner** [comment] 2017-03-05 18:42
Thank you. It'll give me some ideas and a lot of knowledge!

**Comment by gerrieg** [comment] 2017-03-12 08:57
fyi (see readme): https://github.com/openhab/openhab2-addons/pull/2024

**Comment by gerrieg** [comment] 2017-03-12 09:01
Is the HM-Dis-EP-WM55 the same as HM-Dis-WM55? My PR only supports the HM-Dis-WM55, but i can easily add the HM-Dis-EP-WM55 too.

**Comment by MHerbst** [comment] 2017-03-12 09:12
@gerrieg As far as I know it is very similar. I has 5 text lines with icons and also a signal LED. I will try your new code with the device and will give you feedback.

**Comment by MHerbst** [comment] 2017-03-12 18:47
@gerrieg I have tried the add-on with the HM-DIS-EP-WM55. First the good news :-): settings text and icon for line 1, 2 and 3 works. I first had some problems because I have tried to use the channel SUBMIT instead of DISPLAY_SUBMIT. After reading the README.md a second time it was clear, but maybe an explicit hint would be good.

Now to the smaller problems: The display auf EP-EM55 has got the following structure:
```
<Button 2 - Line 1>
--------------------------
<Line 1 | Button 2 - Line 2>      <Icon 1>
<Line 2>                          <Icon 2>
<Line 3 | Button 1 - Line 1>      <Icon 3>
--------------------------
<Button 1 - Line 2>
```
As you can see the texts above the upper line and below the lower line are the "Button Labels" and they seem to be set differently. Both button labels have to lines and these lines are overlapping with Line 1 resp. Line 3.
Until now I did not figure out how to set the button labels via API.

The device maybe needs two additional channels:

- LED flash: the device contains a LED and you can send a command to make the LED flash in different colors: 0xf0 (off), 0xf1 (red), 0xf2 (green), 0xf3 (orange); the color is set at the end of the message right before the STOP
- beeper: the device contains a little beeper and you can send commands for different signals: 0xC0 (off),  0xC1 (long, long), 0xC2 (long, short), 0xC3 (long, short, short), 0xC4 (short), 0xC5 (short, short), 0xC6 (long); the command sequend seems to be `0x14 beepcode  0x1C` before the LED color
 LANG

**Comment by gerrieg** [comment] 2017-03-13 17:45
Thank you for the info. I don't have this device, so i can not play with it to find the correct codes. But i will add the LED flash and the beeper.

**Comment by MHerbst** [comment] 2017-03-13 18:11
@gerrieg LED flash and beeper would be fine and proabably sufficient. 
I have tried to find out how to set the texts for the button label programmatically but without success. None of the sample scripts I found can do it.

**Comment by turbolift** [comment] 2017-03-13 18:58
@MHerbst I have added an script (epaper.zip) that is working for me with my HM-Dis-WM55 epaper Display (8 days before).

**Comment by MHerbst** [comment] 2017-03-13 19:46
I looked into it but then I looked into the CCU script that (I assume) was the basis of your script. I took the information about the LEAD and the beeps from there. 
Did you manage to set all texted lines with your script?

**Comment by turbolift** [comment] 2017-03-14 11:37
"Coming Home" and "Leaving Home" has been set by WebUI, the inner part like "Willkommen <LOCK>", "Mo 13.3.17" and "7C" has been set by the script.

![img_20170314_001044](https://cloud.githubusercontent.com/assets/2904717/23898762/993c8f06-08b2-11e7-8fa9-35597a8047c1.jpg)

**Comment by MHerbst** [comment] 2017-03-14 13:51
This is exactly what I did with the enhanced and slightly modified add-on. I think normally it will be sufficient to set the inner text in a rule und set the other texts in the Web UI.
