### ISSUE TITLE
[samsungTV] 

### ISSUE THREAD

**Issue by Dan1001** [openhab/openhab2-addons#1881] opened 2017-02-11 10:08 UTC
Small issue with the Samsung TV binding. I have our TV defined in a Things file, and everything works fine - but every so often the binding autodiscovers the same TV and puts it in the inbox. Presumably that shouldn't happen...

**Comment by MHerbst** [comment] 2017-02-11 10:19
Can you check whether the machine where openHAB is running as two IP addresses? In this case it is probably a duplicate of #1667

**Comment by Dan1001** [comment] 2017-02-11 10:54
definitely not - openHAB is running on a linux PC (not a virtual box) and one IP address

**Comment by whopperg** [comment] 2017-02-16 14:21
Or maybe your tv gets a new IP address from time to time?

**Comment by Dan1001** [comment] 2017-02-16 14:53
nope - all devices on my network get a static lease.

But if I'm the only one with this problem it suggests there is something wrong at my end!

**Comment by whopperg** [comment] 2017-02-16 16:13
Well i got 2 TV's in my network and didn't had any problems. But I'm using wired connection with both tv's...

**Comment by martinvw** [comment] 2017-06-03 13:58
It's expected that it also discovers the tv, most likely detection of duplicates is based on a certain name, you can ignore it by clicking one the eye instead of clicking on the bin. Then it will not pop up again.

If you want to improve the detection of duplicates relative to manually configured things, you are welcome to create a PR for it. But note that most bindings I have seen do not contain logic for that.

**Closed by martinvw** 2017-06-03 13:58 UTC
