### ISSUE TITLE
[Kostal Inverter] Add missing configuration parameters

### ISSUE THREAD

**Issue by pedeho** [openhab/openhab2-addons#1021] opened 2016-06-13 07:12 UTC
Hello
I have been monitoring all Kostal parameters with Openhab. I recently installed Openhab 2 with the new Kostal binding with only 4 parameters!??  I have added the rest of the missing parameters to a snapshot version which I'm using now.
Now everything is working the way I want it but I'm aware that this is not exactly the right way to go about it.

Please add all parameters to a upcoming version. Thanks.  
##

**Comment by thopiekar** [comment] 2016-06-13 09:14
+1 for this.

I'm also missing some parameters.
I guess the maintainer/owner of the code never needed more than these 4 parameters, so these are missing.

Would be great, if you could invest some time to add them to the binding.

**Comment by kaikreuzer** [comment] 2016-06-13 16:35
@cschneider Could you have a look, please?

**Comment by cschneider** [comment] 2016-06-13 16:48
@pedeho Can you create a pull request?

**Comment by pedeho** [comment] 2016-06-13 17:13
@cschneider A little guide please. I'm unfortunately not at home here

**Comment by cschneider** [comment] 2016-06-14 10:34
Basically you clone the openhab2-addons repository, check it out on your machine, create a branch named like the issue. Then you do the changes in your branch, commit them and push to your own repo. You can then create a pull request in github for it.

At the start this can be a little overwhelming. Can you just post which parameters you added?

**Comment by pedeho** [comment] 2016-06-14 12:02
Hmm. Have been working on netbeans for almost 20 years. Compiled "my" 
updated version on netbeans. I'm a retired programmer, very busy and 
will be for a long time and simply have no time nor desire to start 
working with this or any other subject. I only solved a little problem 
and wrote som feedback. Sorry about that. if wanted/needed I can post 
the added parameters and/or code changes

Paul Dhaene


Den 14-06-2016 kl. 12:34 skrev Christian Schneider:
>
> Basically you clone the openhab2-addons repository, check it out on 
> your machine, create a branch named like the issue. Then you do the 
> changes in your branch, commit them and push to your own repo. You can 
> then create a pull request in github for it.
>
> At the start this can be a little overwhelming. Can you just post 
> which parameters you added?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/openhab/openhab2-addons/issues/1021#issuecomment-225843073>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ACy8wFlEg33MSm2G9Pa-EsYrsE1RIVJVks5qLoOfgaJpZM4I0DQl>.
>



---
Denne e-mail blev kontrolleret for virusser af Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by cschneider** [comment] 2016-06-14 12:05
That is fine. After all this is an open source project. Everyone helps as far as he can and wants.

**Comment by pedeho** [comment] 2016-06-14 17:46
@cschneider additions/changes made in kostal binding.

[WebscrapeHandler-java-changes.pdf](https://github.com/openhab/openhab2-addons/files/314588/WebscrapeHandler-java-changes.pdf)
[thing-types.xml-changes.pdf](https://github.com/openhab/openhab2-addons/files/314591/thing-types.xml-changes.pdf)

**Comment by cschneider** [comment] 2016-06-14 18:01
Looks good. I should be able to work with this.

**Comment by CWempe** [comment] 2017-02-13 23:22
Any progress on this?

**Comment by kaikreuzer** [comment] 2017-09-18 06:05
@pedeho Could you please leave a comment when closing an issue to give the reason? Thanks!

**Comment by pedeho** [comment] 2017-09-18 10:28
Sorry for that. The reason is simple. Back on the 13 jun 2106 I opened a thread. On the 14 jun 2016 I expressed that I was not really interested in participating. I offered therefore to upload the changes I made to the Kostal addon. cschneiner's reaction? "Looks good. I should be able to work with this." . Excellent but that is a long time since. I do not know where any progress should come from. Not from me. cschneider does not seem to be interested.. More than a year has past. I lost interest

**Comment by kaikreuzer** [comment] 2017-09-18 12:24
That's fair enough @pedeho. So let's ask @cschneider if he'd think he could make a binding PR out of that - if not, closing the issue is just fine.

**Comment by cschneider** [comment] 2017-09-18 13:08
The code changes required are quite minimal. For me the problem is that I currently do not have a setup to build and test the changes. I am on vacation next week. If I find some time then I will do a PR.

**Comment by kaikreuzer** [comment] 2017-09-18 14:13
Sounds good, no rush!
I can help you creating an IDE setup at ECE ;-)
Leave your time and enjoy your vacation!

**Comment by martinvw** [comment] 2017-11-03 15:20
Any updates on this?

**Comment by cschneider** [comment] 2018-10-30 07:10
PR is done https://github.com/openhab/openhab2-addons/pull/4175

**Comment by cweitkamp** [comment] 2018-11-05 11:20
Codes by #4175

**Closed by cweitkamp** 2018-11-05 11:20 UTC
