### ISSUE TITLE
[netatmo binding] netatmo.handler.NetatmoBridgeHandler

### ISSUE THREAD

**Issue by wollyd** [openhab/openhab2-addons#2379] opened 2017-06-18 07:38 UTC
## Current Behavior

2017-05-31 20:42:34.268 [ERROR] [netatmo.handler.NetatmoBridgeHandler] - An error occured while calling thermostat API : com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 352 path $.body.devices[0].plug_connected_boiler

the parameter plug_connected_boiler seems to be a NUMBER now, in the old documentation is was a BOOLEAN.

## Your Environment

* Version used: (e.g., openhab and addon versions) :  openhab2-online 2.0.0~b5
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...)
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie
(no local bindings)

**Comment by hmerk** [comment] 2017-06-18 22:36
Your Java version is outdated (1.8.0_65), please update and try again.

**Comment by wollyd** [comment] 2017-06-19 09:15
Hi,

I updated my java to the latest version available on the oracle website.

java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) Client VM (build 25.131-b11, mixed mode)

but still the same problem :
2017-06-19 11:07:18.860 [ERROR] [netatmo.handler.NetatmoBridgeHandler] -
An error occured while calling thermostat API :
com.google.gson.JsonSyntaxExcep
tion: java.lang.IllegalStateException: Expected a boolean but was NUMBER
at line 1 column 352 path $.body.devices[0].plug_connected_boiler

kind regards

willy

**Comment by wollyd** [comment] 2017-06-26 14:22
Hi,

Anyone any idea's about this. Since I get this error, it is not possible to read any values from the netatmo thermostat

kind regards

willy

**Comment by wollyd** [comment] 2017-07-18 14:16
Hi,

is there a way to debug this issue, it can be solved ?
All help is welcome ...

kind regards
willy

**Comment by wollyd** [comment] 2017-07-27 11:52
Getting the json from netatmo shows a number for the plug_connected_boiler, so whats wrong ?

 "body": {
    "devices": [
      {
        "_id": "70:ee:50:98:e0:f6",
        "firmware": 140,
        "last_bilan": {
          "y": 2017,
          "m": 6
        },
        "last_setup": 1441622847,
        "last_status_store": 1501154340,
        "place": {
          "altitude": 16,
          "city": "XXX",
          "country": "XX",
          "improveLocProposed": true,
          "location": [
            0.0,
            1.003084580126
          ],
          "timezone": "Europe/Brussels",
          "trust_location": true
        },
        **"plug_connected_boiler": 0,**
        "type": "NAPlug",
        "udp_conn": true,
        "wifi_status": 63,
        "modules": [
          {
            "_id": "04:00:00:55:34:56",
            "module_name": "Thermostaat",
            "type": "NATherm1",
            "firmware": 59,
            "last_message": 1501154330,
            "rf_status": 54,

**Comment by cweitkamp** [comment] 2017-07-30 21:14
@clinique Can you help?

**Comment by Orfait** [comment] 2017-07-31 07:40
Hi,
I have the same issue. I tried 2.1 release and 2.2 snapshot.
On build 998, the error is:
`09:32:37.067 [ERROR] [netatmo.handler.NetatmoBridgeHandler] - An error occurred while calling thermostat API : com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 312 path $.body.devices[0].plug_connected_boiler`

I am not a developper but I can do my best to help resolving this issue.

Regards

**Comment by wollyd** [comment] 2017-07-31 12:23
hi,

it seems to be defined in : https://github.com/cbornet/netatmo-swagger-api/blob/master/generated/netatmo/client/java-retrofit/src/main/java/io/swagger/client/model/NAThermStateBody.java

  @SerializedName("plug_connected_boiler")
  private Boolean plugConnectedBoiler = null;

**Comment by cweitkamp** [comment] 2017-07-31 14:36
Good catch. Meaning this problem is caused by the underlying library used to read those values. We should report thus issue to the related Github report, shouldn't we?

**Comment by clinique** [comment] 2017-07-31 14:40
I can take care of the change in swagger library, I'll give a look at issue #2505 in the same time

**Comment by clinique** [comment] 2017-08-01 07:00
It's rather weird because in my dev.netatmo interface, when I query it I get plug_connected_boiler as a boolean, while you receive it as an integer. Modifying the swagger definition to integer seems to accept boolean as well, so I'll head with that. Netatmo API documentation is really poor, this variable isn't documented but I'll push it in the binding by the way.

**Comment by clinique** [comment] 2017-08-01 07:42
I suspect it depends upon the firmware version of the station that may give back different answers from the API.

**Comment by cweitkamp** [comment] 2017-08-01 08:17
Thanks for your work. Is it possible to implement a firmware version check and with it a different handling for this value?

Just for my personal interest. Where can I find the code of the swagger library and how to build it? Can it be found in the [https://github.com/cbornet/netatmo-swagger-api](https://github.com/cbornet/netatmo-swagger-api) repo? Where can I have a look at the Netatmo API documentation? Thanks in advance.

**Comment by clinique** [comment] 2017-08-01 08:25
With the modification I made (changing plug_connected_boiler to int32 instead of boolean), it appears to accept boolean value (what I get from the api) without error. So you should be good on your side also.

I'm not 100% sure it comes from the firmware version, but suspect it. In the past, we already faced different behaviour of Netatmo API depending upon the user.

I'll push my modifications on the swagger netatmo definition in a few minutes also. So it'll be available on cbornet repository. You need both swagger-decl and swagger api from his repository in order to build the java-retrofit jar that is used in the netatmo binding.

**Comment by clinique** [comment] 2017-08-01 08:25
Netatmo API documentation is available at dev.netatmo.com

**Comment by wollyd** [comment] 2017-08-01 10:06
Hi,

This is the firmware I am using :

Thermostat : 59
Relais station : 140

Hope this helps...

regards

willy

**Comment by wollyd** [comment] 2017-08-03 08:14
Hi,

Where can i find the updated jar file ?
How do I install this file ?

regards
willy

**Comment by cweitkamp** [comment] 2017-08-03 08:57
I think xou can download the .jar file here https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.netatmo/2.2.0-SNAPSHOT/.

For installation follow this [documentation.](http://docs.openhab.org/installation/linux.html#installing-add-ons). Be aware to remove the old binding version first.

**Comment by wollyd** [comment] 2017-08-03 09:42
Hi,

I copied the new jarfile to /usr/share/openhab2/addons
then tried to install via the GUI, but got the following error 
2017-08-03 11:39:54.608 [WARN ] [url.mvn.internal.AetherBasedResolver] - Error resolving artifact org.openhab.binding:org.openhab.binding.network:jar:2.1.0: [Could not find artifact org.openhab.binding:org.openhab.binding.network:jar:2.1.0]
java.io.IOException: Error resolving artifact org.openhab.binding:org.openhab.binding.network:jar:2.1.0: [Could not find artifact org.openhab.binding:org.openhab.binding.network:jar:2.1.0]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:720)[7:org.ops4j.pax.url.mvn:2.5.2]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:659)[7:org.ops4j.pax.url.mvn:2.5.2]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:600)[7:org.ops4j.pax.url.mvn:2.5.2]
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:567)[7:org.ops4j.pax.url.mvn:2.5.2]
        at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:36)[8:org.apache.karaf.features.core:4.0.8]
        at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)[8:org.apache.karaf.features.core:4.0.8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.openhab.binding:org.openhab.binding.network:jar:2.1.0
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:705)[7:org.ops4j.pax.url.mvn:2.5.2]
        ... 12 more

**Comment by cweitkamp** [comment] 2017-08-03 10:22
You don't need to install anything via the GUI. After dropping the .jar file into the addons folder it is installed automatically.  I have no clue, why that error occurres and since it says something about the network binding, I assume it has nothing to do with the changes of the netatmo binding. Please restart the openhab2 service and look if the error disappears or not.

**Comment by wollyd** [comment] 2017-08-03 10:40
I think there was something wrong with my internet...
but I still get the following error 
2017-08-03 12:38:07.730 [ERROR] [netatmo.handler.NetatmoBridgeHandler] - An error occurred while calling thermostat API : com.google.gson.JsonSyntaxExce
ption: java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 352 path $.body.devices[0].plug_connected_boiler
in the jar file lib/netatmo-java-retrofit-1.0.7.jar = the same version as the old one ?

**Comment by cweitkamp** [comment] 2017-08-03 11:26
Silly question, I know, but did you uninstall the old version?

**Comment by wollyd** [comment] 2017-08-03 11:31
yes I did, I uninstalled, restarted, then copied the file to the addons directory.
![image](https://user-images.githubusercontent.com/29516657/28919903-d526d5dc-784f-11e7-82a7-a7675ecf5d9f.png)

**Comment by cweitkamp** [comment] 2017-08-03 11:44
OK, you did everything right. Maybe the .jar file I pointed contains not the latest changes. Then we have to wait until #2510 got merged - unless you build it in your own ;-).

**Comment by wollyd** [comment] 2017-08-03 12:04
ok 
thanks for your help
willy

**Closed** 2017-08-15 15:41 UTC

**Comment by RickyTR** [comment] 2017-08-21 13:55
I tried the latest kar from build 1020 (8-20-2017) with no luck. I still have the same error. Any suggestion?

**Comment by RickyTR** [comment] 2017-08-21 15:01
Thanks for your work...

**Comment by clinique** [comment] 2017-08-21 15:12
Updated PR #2560

**Comment by RickyTR** [comment] 2017-08-21 16:03
I tried to put the jar files in addon dir but I cannot see the 2.2 snapshot version in addons screen. Am I missing something?

**Comment by clinique** [comment] 2017-08-21 16:06
Have you removed previous version ?

**Comment by RickyTR** [comment] 2017-08-21 16:08
I uninstalled 2.1 using the addons interface in paper UI.
I have this error:
Could not resolve module: org.openhab.binding.netatmo [215]
  Another singleton bundle selected: osgi.identity; osgi.identity="org.openhab.binding.netatmo"; type="osgi.bundle"; version:Version="2.2.0.201708201100"; singleton:="true"

**Comment by clinique** [comment] 2017-08-21 16:19
Well, I don't know where it comes from. I understand that the module is already loaded. Maybe try restarting OH. I saw in OH user forum that this message seems to be quite frequent but did not had time to identify where it comes from.

**Comment by Orfait** [comment] 2017-08-21 16:37
Hi,
I tried with the jar (linked above), the version is 2.2.0.201708211619 and I still have this message :
`18:35:36.103 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'netatmo:netatmoapi:home' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): An error occurred while calling thermostat API : com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 312 path $.body.devices[0].plug_connected_boiler`

**Comment by RickyTR** [comment] 2017-08-22 08:01
I deleted the cache folder under userdata and restarted openhab and now it seems that everything is working!

**Comment by Orfait** [comment] 2017-08-22 08:50
@RickyTR : which version do you have ? Where do you download it ?
I also deleted the cache folder & restarted but I don't have same result.

**Comment by RickyTR** [comment] 2017-08-22 09:37
I downloaded the jar here: 
https://openhab.ci.cloudbees.com/job/PR-openHAB2-Addons/ws/addons/binding/org.openhab.binding.netatmo/target/
I don't know exactly which version it is. How can I check the version?

**Comment by Orfait** [comment] 2017-08-22 09:45
In karaf console, type
`bundle:list | grep Netatmo`

Indeed, I was using the jfrog jar
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.netatmo/2.2.0-SNAPSHOT/

So, I download the jar from you link, version is `2.2.0.201708220434` and I still get the message.
`cache` and `tmp` folder were cleared and openhab restarted.

I am using openhab 2.2 snapshot.

**Comment by RickyTR** [comment] 2017-08-22 09:52
I'm using 2.2.0.201708211425. If I remember correctly I downloaded this version from the link above. But maybe I'm wrong because I tried several different things yesterday...

**Comment by Orfait** [comment] 2017-08-22 09:58
So, in my openhab 2.2 snapshot installation, none of jfrog or cloudbees works.
Still having the same issue with boolean / number.

Maybe @clinique can help to understand.

**Comment by RickyTR** [comment] 2017-08-22 10:48
Just for clarification: I'm using opnehab 2.1 relaese build.

**Comment by wollyd** [comment] 2017-08-22 11:04
Hi,

I did also the test with the cloudbees jar file.
I get also the same issue with the boolean/number.

kind regards

willy

**Comment by clinique** [comment] 2017-08-22 13:20
The jar provided here https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.netatmo/2.2.0-SNAPSHOT/ is not the good one. If you uncompress it you'll see that it contains netatmo-java-retrofit-1.0.8.jar in the lib directory, while the last PR I made includes v 1.0.9 of this jar.

**Comment by Orfait** [comment] 2017-08-22 15:34
You are right, v 1.0.8 is included but PR #2560 include is 1.0.9.
Do you want us to try with v1.0.9 ? Where can we find it ?

**Comment by clinique** [comment] 2017-08-22 16:01
@Orfait : can you please try to download the jar [here](https://www.lhopital.org/nextcloud/s/FDIoJkTPdjQSxnv/download)

**Comment by Orfait** [comment] 2017-08-22 16:51
@clinique : That's strange, the jar does not get installed when I pu it inside addons folder. Am I missing something ?

**Comment by clinique** [comment] 2017-08-22 17:03
Honestly, I don't know - I generated the jar from my dev environment. Maybe I made a mistake

Envoyé de mon iPhone

**Comment by clinique** [comment] 2017-08-23 06:44
@Orfait can you try this new one : https://www.lhopital.org/nextcloud/s/3FeikJfRGnSyt3n

**Comment by Orfait** [comment] 2017-08-23 07:09
@clinique : just for your info, I have something which went wrong because I cannot install any addons. I am checking.

**Comment by Orfait** [comment] 2017-08-23 14:40
Unfortunately, adding this binding kills openhab.
Can someone else try ?

**Comment by Orfait** [comment] 2017-08-24 06:48
@clinique & @ martinvw : the updated 'pull requested" binding in jfrog is working for me.
`openhab> bundle:list| grep Netatmo`
`195 │ Active   │  80 │ 2.2.0.201708231238     │ Netatmo Binding`

No error, no warning.

**Comment by wollyd** [comment] 2017-08-24 07:03
Hi,

I tried to add the binding 2.2.0PR2560 but it does not load.
I am running openhab 2.1.0

kind regards

willy

**Comment by Orfait** [comment] 2017-08-24 07:04
@wollyd : use this one :
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.netatmo/2.2.0-SNAPSHOT/

**Comment by wollyd** [comment] 2017-08-24 08:33
Yes this one is working fine, no errors about the boiler_plug... :+1:
Thanks a lot

willy

**Comment by RickyTR** [comment] 2017-08-29 14:15
After some days of checking I noticed that the addons seems to not update values (temperature, for example) after some hours. Is there a way to set the frequency of updates?

**Comment by Orfait** [comment] 2017-08-29 19:26
@RickyTR : you can add a refresh interval to the parent item (NAPlug) like this :
`Thing NAPlug    plugtherm  [ equipmentId="70:EE:50:XX:XX:XX", refreshInterval=600000 ]`

In my setup, I don't have refresh issue but I noticed that the Netatmo service (not the addon) was down a few hours ago.
