### ISSUE TITLE
Pioneer AVR Binding:  Zone 2 Control

### ISSUE THREAD

**Issue by Spilota** [openhab/openhab2-addons#1206] opened 2016-08-28 13:55 UTC
Has anyone looked at implementing Zone 2 control with the Pioneer AVR binding, or is it already possible?
##

**Comment by Stratehm** [comment] 2016-10-13 21:21
I should have some time next week to implement multi-zone control.

**Comment by Stratehm** [comment] 2016-12-03 09:22
The multi zone implementation is now merged on master. Could you test the new version of the binding ?

**Comment by Spilota** [comment] 2016-12-03 17:01
Zone 1 works perfectly so far.

I cannot control anything from Openhab in Zone 2.  Openhab does receive a status update for power and mute if it is changed locally on the receiver, but it does not update the volume slider.

**Comment by Spilota** [comment] 2016-12-10 19:43
Thanks for all the work on this.

I tried again with the 12-10 snapshot.  The dimmer in openhab is not controlling volume.  Openhab is, however, controlling power, mute, and input correctly.  

Communication from the receiver to Openhab is working good.  Openhab is getting correct status of power, mute, and input.  It is also updating the zone 2 volume % and dB correctly.

**Comment by Spilota** [comment] 2016-12-11 19:34
It looks like the zone 2 volume control command is never getting through to the receiver.  I'm not getting anything in my pioneer.log file.  I am seeing this in my openhab.log:

```
2016-12-11 13:28:51.950 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling handler: org.openhab.binding.pioneeravr.protocol.AvrConnectionException: The parameter v does not match the pattern [0-9]{3}
 does not match the pattern [0-9]{3}ion: org.openhab.binding.pioneeravr.protocol.AvrConnectionException: The parameter value 57 of the command ZV
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_65]
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_65]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:186)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:79)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:63)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:352)[103:org.eclipse.smarthome.core.thing:0.9.0.201612010841]
        at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:46)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)[96:org.eclipse.smarthome.core:0.9.0.201612010841]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
 does not match the pattern [0-9]{3}eravr.protocol.AvrConnectionException: The parameter value 57 of the command ZV
        at org.openhab.binding.pioneeravr.internal.protocol.ParameterizedCommand.getCommand(ParameterizedCommand.java:84)[223:org.openhab.binding.pioneeravr:2.0.0.201612101322]
        at org.openhab.binding.pioneeravr.internal.protocol.StreamAvrConnection.sendCommand(StreamAvrConnection.java:244)[223:org.openhab.binding.pioneeravr:2.0.0.201612101322]
        at org.openhab.binding.pioneeravr.internal.protocol.StreamAvrConnection.setVolume(StreamAvrConnection.java:403)[223:org.openhab.binding.pioneeravr:2.0.0.201612101322]
        at org.openhab.binding.pioneeravr.internal.protocol.StreamAvrConnection.sendVolumeCommand(StreamAvrConnection.java:373)[223:org.openhab.binding.pioneeravr:2.0.0.201612101322]
        at org.openhab.binding.pioneeravr.internal.handler.AbstractAvrHandler.handleCommand(AbstractAvrHandler.java:265)[223:org.openhab.binding.pioneeravr:2.0.0.201612101322]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:355)[103:org.eclipse.smarthome.core.thing:0.9.0.201612010841]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$3.call(ThingManager.java:1)[103:org.eclipse.smarthome.core.thing:0.9.0.201612010841]
        ... 5 more
```

**Comment by Spilota** [comment] 2016-12-11 19:34
Should the VSX-1122 be listed in the support receivers set?  It supports the same commands (2012 version).  

Thanks

**Comment by Stratehm** [comment] 2016-12-13 10:56
Zone 2 volume control whould work with this [version](https://github.com/Stratehm/openhab2-addons/releases/tag/2016-12-13)

**Comment by Andirs55** [comment] 2017-07-17 16:47
@Stratehm is is possible to implement Zone2Control for the VSX-924?
I am on 2.1 stable. At the moment when triggering the Zone2 Power i get the folling log entry:

`2017-07-17 18:46:21.493 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while calling handler: java.lang.ArrayIndexOutOfBoundsException: -1
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: -1
	at org.eclipse.smarthome.core.common.SafeMethodCaller.executeDirectly(SafeMethodCaller.java:220)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:189)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:374)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:47)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181)[98:org.eclipse.smarthome.core:0.9.0.b5]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at org.openhab.binding.pioneeravr.internal.protocol.SimpleCommand$SimpleCommandType.getCommand(SimpleCommand.java:50)[209:org.openhab.binding.pioneeravr:2.1.0]
	at org.openhab.binding.pioneeravr.internal.protocol.SimpleCommand.getCommand(SimpleCommand.java:64)[209:org.openhab.binding.pioneeravr:2.1.0]
	at org.openhab.binding.pioneeravr.internal.protocol.StreamAvrConnection.sendCommand(StreamAvrConnection.java:151)[209:org.openhab.binding.pioneeravr:2.1.0]
	at org.openhab.binding.pioneeravr.internal.protocol.StreamAvrConnection.sendPowerCommand(StreamAvrConnection.java:217)[209:org.openhab.binding.pioneeravr:2.1.0]
	at org.openhab.binding.pioneeravr.internal.handler.AbstractAvrHandler.handleCommand(AbstractAvrHandler.java:167)[209:org.openhab.binding.pioneeravr:2.1.0]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:377)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:1)[105:org.eclipse.smarthome.core.thing:0.9.0.b5]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.executeDirectly(SafeMethodCaller.java:218)[98:org.eclipse.smarthome.core:0.9.0.b5]
	... 12 more`

**Closed** 2017-08-04 13:21 UTC
